<?php
/**
 * Products, Quotations & Invoices modules.
 * Extensions to SugarCRM
 * @package Advanced OpenSales for SugarCRM
 * @subpackage Products
 * @copyright SalesAgility Ltd http://www.salesagility.com
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author Salesagility Ltd <support@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/

$mod_strings = array (
    'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
    'LBL_CONTRACT_ACCOUNT' => 'Контрагент',
    'LBL_OPPORTUNITY' => 'Сделка',
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Дата создания',
    'LBL_DATE_MODIFIED' => 'Дата изменения',
    'LBL_MODIFIED' => 'Изменено',
    'LBL_MODIFIED_ID' => 'Изменено(ID)',
    'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
    'LBL_CREATED' => 'Создано',
    'LBL_CREATED_ID' => 'Создано(ID)',
    'LBL_DESCRIPTION' => 'Описание',
    'LBL_DELETED' => 'Удалён',
    'LBL_NAME' => 'Договор',
    'LBL_CREATED_USER' => 'Создано',
    'LBL_MODIFIED_USER' => 'Изменено',
    'LBL_LIST_NAME' => 'Название',
    'LBL_LIST_FORM_TITLE' => 'Список договоров',
    'LBL_MODULE_NAME' => 'Договоры',
    'LBL_MODULE_TITLE' => 'Договоры',
    'LBL_HOMEPAGE_TITLE' => 'Мои договоры',
    'LNK_NEW_RECORD' => 'Создать договор',
    'LNK_LIST' => 'Договоры',
    'LNK_IMPORT_AOS_CONTRACTS' => 'Импорт договоров',
    'LBL_SEARCH_FORM_TITLE' => 'Поиск договоров',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
    'LBL_AOS_CONTRACTS_SUBPANEL_TITLE' => 'Договоры',
    'LBL_NEW_FORM_TITLE' => 'Новый договор',
    'LBL_CONTRACT_NAME' => 'Название договора',
    'LBL_REFERENCE_CODE ' => '№ договора ',
    'LBL_START_DATE' => 'Дата начала',
    'LBL_END_DATE' => 'Дата окончания',
    'LBL_TOTAL_CONTRACT_VALUE' => 'Сумма договора',
    'LBL_STATUS' => 'Статус',
    'LBL_CUSTOMER_SIGNED_DATE' => 'Дата подписания клиентом',
    'LBL_COMPANY_SIGNED_DATE' => 'Дата подписания контрагентом',
    'LBL_RENEWAL_REMINDER_DATE' => 'Уведомление об окончании срока действия',
    'LBL_CONTRACT_TYPE' => 'Тип договора',
	
    'LBL_CONTACT' => 'Контакт',
	
  'LBL_ADD_GROUP' => 'Добавить группу',
  'LBL_DELETE_GROUP' => 'Удалить группу',
  'LBL_GROUP_NAME' => 'Группа',
  'LBL_GROUP_TOTAL' => 'ИТОГО С НДС',

  'LBL_PRODUCT_QUANITY' => 'Количество',
  'LBL_PRODUCT_NAME' => 'Товар',
  'LBL_PART_NUMBER' => 'Артикул',
  'LBL_PRODUCT_NOTE' => 'Заметка',
  'LBL_PRODUCT_DESCRIPTION' => 'Описание',
  'LBL_LIST_PRICE' => 'Цена по прайсу',
  'LBL_DISCOUNT_TYPE' => 'Тип скидки',
  'LBL_DISCOUNT_AMT' => 'Скидка',
  'LBL_UNIT_PRICE' => 'Цена за единицу',
  'LBL_TOTAL_PRICE' => 'СУММА',
  'LBL_VAT' => 'НДС (%)',
  'LBL_VAT_AMT' => 'НДС',

  'LBL_SERVICE_NAME' => 'Услуга',
  'LBL_SERVICE_LIST_PRICE' => 'Стоимость по прайсу',
  'LBL_SERVICE_PRICE' => 'Стоимость',
  'LBL_SERVICE_DISCOUNT' => 'Скидка',

  'LBL_LINE_ITEMS' => 'Позиции',
  'LBL_SUBTOTAL_AMOUNT' => 'Итого со скидкой',
  'LBL_DISCOUNT_AMOUNT' => 'Скидка',
  'LBL_TAX_AMOUNT' => 'Всего НДС',
  'LBL_SHIPPING_AMOUNT' => 'Доставка',
  'LBL_TOTAL_AMT' => 'Итого без скидки',
  'LBL_GRAND_TOTAL' => 'ВСЕГО К ОПЛАТЕ',
  'LBL_SHIPPING_TAX' => 'НДС доставки (%)',
  'LBL_SHIPPING_TAX_AMT' => 'НДС доставки',
  'LBL_ADD_PRODUCT_LINE' => 'Добавить товар',
  'LBL_ADD_SERVICE_LINE' => 'Добавить услугу ',
);
?>
