<?php
$module_name = 'stic_Security_Groups_Rules';
$searchdefs[$module_name] =
array(
    'layout' => array(
        'basic_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'active' => array(
                'type' => 'bool',
                'studio' => array(
                    'quickcreate' => false,
                    'editview' => false,
                ),
                'label' => 'LBL_ACTIVE',
                'width' => '10%',
                'default' => true,
                'name' => 'active',
            ),
            'inherit_assigned' => array(
                'name' => 'inherit_assigned',
                'label' => 'LBL_INHERIT_ASSIGNED',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'inherit_creator' => array(
                'name' => 'inherit_creator',
                'label' => 'LBL_INHERIT_CREATOR',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'inherit_parent' => array(
                'type' => 'bool',
                'default' => true,
                'studio' => 'visible',
                'label' => 'LBL_INHERIT_PARENT',
                'width' => '10%',
                'name' => 'inherit_parent',
            ),
            'inherit_from_modules' => array(
                'default' => true,
                'studio' => 'visible',
                'type' => 'multienum',
                'label' => 'LBL_INHERIT_FROM_MODULES',
                'width' => '10%',
                'name' => 'inherit_from_modules',
            ),
            'non_inherit_from_security_groups' => array(
                'type' => 'multienum',
                'studio' => 'visible',
                'label' => 'LBL_NON_INHERIT_FROM_SECURITY_GROUPS',
                'width' => '10%',
                'default' => true,
                'name' => 'non_inherit_from_security_groups',
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
        ),
        'advanced_search' => array(
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'active' => array(
                'type' => 'bool',
                'studio' => array(
                    'quickcreate' => false,
                    'editview' => false,
                ),
                'label' => 'LBL_ACTIVE',
                'width' => '10%',
                'default' => true,
                'name' => 'active',
            ),
            'inherit_assigned' => array(
                'name' => 'inherit_assigned',
                'label' => 'LBL_INHERIT_ASSIGNED',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'inherit_creator' => array(
                'name' => 'inherit_creator',
                'label' => 'LBL_INHERIT_CREATOR',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'inherit_parent' => array(
                'type' => 'bool',
                'default' => true,
                'studio' => 'visible',
                'label' => 'LBL_INHERIT_PARENT',
                'width' => '10%',
                'name' => 'inherit_parent',
            ),
            'inherit_from_modules' => array(
                'default' => true,
                'studio' => 'visible',
                'type' => 'multienum',
                'label' => 'LBL_INHERIT_FROM_MODULES',
                'width' => '10%',
                'name' => 'inherit_from_modules',
            ),
            'non_inherit_from_security_groups' => array(
                'type' => 'multienum',
                'studio' => 'visible',
                'label' => 'LBL_NON_INHERIT_FROM_SECURITY_GROUPS',
                'width' => '10%',
                'default' => true,
                'name' => 'non_inherit_from_security_groups',
            ),
            'current_user_only' => array(
                'name' => 'current_user_only',
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
            ),
            'name' => array(
                'name' => 'name',
                'default' => true,
                'width' => '10%',
            ),
            'assigned_user_id' => array(
                'name' => 'assigned_user_id',
                'label' => 'LBL_ASSIGNED_TO',
                'type' => 'enum',
                'function' => array(
                    'name' => 'get_user_array',
                    'params' => array(
                        0 => false,
                    ),
                ),
                'default' => true,
                'width' => '10%',
            ),
            'date_entered' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_ENTERED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_entered',
            ),
            'date_modified' => array(
                'type' => 'datetime',
                'label' => 'LBL_DATE_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'date_modified',
            ),
            'modified_user_id' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_MODIFIED',
                'width' => '10%',
                'default' => true,
                'name' => 'modified_user_id',
            ),
            'created_by' => array(
                'type' => 'assigned_user_name',
                'label' => 'LBL_CREATED',
                'width' => '10%',
                'default' => true,
                'name' => 'created_by',
            ),
            'description' => array(
                'type' => 'text',
                'label' => 'LBL_DESCRIPTION',
                'sortable' => false,
                'width' => '10%',
                'default' => true,
                'name' => 'description',
            ),
            'current_user_only' => array(
                'label' => 'LBL_CURRENT_USER_FILTER',
                'type' => 'bool',
                'default' => true,
                'width' => '10%',
                'name' => 'current_user_only',
            ),
        ),
    ),
    'templateMeta' => array(
        'maxColumns' => '3',
        'maxColumnsBasic' => '4',
        'widths' => array(
            'label' => '10',
            'field' => '30',
        ),
    ),
);
