<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Security_Groups_Rules'] = array(
    'table' => 'stic_security_groups_rules',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'enum',
            'options' => 'dynamic_filtered_module_list',
            'link' => false,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'full_text_search' => array(
                'boost' => 3,
            ),
            'required' => true,
            'importable' => 'required',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'massupdate' => 0,
            'default' => '',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => true,
            'inline_edit' => false,
            'reportable' => true,
            'size' => '20',
        ),
        'name_label' => array(
            'name' => 'name_label',
            'vname' => 'LBL_NAME_LABEL',
            'type' => 'varchar',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => false,
            'required' => false,
            'importable' => false,
            'duplicate_merge' => 'disabled',
            'merge_filter' => 'disabled',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => false,
            'size' => '20',
        ),
        'active' => array(
            'required' => false,
            'name' => 'active',
            'vname' => 'LBL_ACTIVE',
            'type' => 'bool',
            'no_default' => false,
            'massupdate' => 1,
            'inline_edit' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '2',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'popupHelp' => 'LBL_ACTIVE_INFO',
            'studio' => array(
                'quickcreate' => false,
                'editview' => false,
            ),
        ),
        'inherit_from_modules' => array(
            'audited' => false,
            'comments' => '',
            'duplicate_merge_dom_value' => '0',
            'duplicate_merge' => 'disabled',
            'help' => '',
            'importable' => 'true',
            'inline_edit' => false,
            'isMultiSelect' => true,
            'default' => '^^',
            'massupdate' => 0,
            'merge_filter' => 'disabled',
            'name' => 'inherit_from_modules',
            'no_default' => 0,
            'options' => 'dynamic_related_module_list',
            'reportable' => true,
            'required' => false,
            'studio' => 'visible',
            'type' => 'multienum',
            'unified_search' => false,
            'vname' => 'LBL_INHERIT_FROM_MODULES',
            'popupHelp' => 'LBL_INHERIT_FROM_MODULES_INFO',
        ),

        'non_inherit_from_security_groups' => array(
            'required' => false,
            'name' => 'non_inherit_from_security_groups',
            'vname' => 'LBL_NON_INHERIT_FROM_SECURITY_GROUPS',
            'type' => 'multienum',
            'massupdate' => 1,
            'isMultiSelect' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'options' => 'dynamic_security_group_list',
            'merge_filter' => 'disabled',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_NON_INHERIT_FROM_SECURITY_GROUPS_INFO',
        ),

        'inherit_assigned' => array(
            'required' => false,
            'name' => 'inherit_assigned',
            'vname' => 'LBL_INHERIT_ASSIGNED',
            'type' => 'bool',
            'massupdate' => '1',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_INHERIT_ASSIGNED_CUSTOM_INFO',
        ),
        'inherit_creator' => array(
            'required' => false,
            'name' => 'inherit_creator',
            'vname' => 'LBL_INHERIT_CREATOR',
            'type' => 'bool',
            'massupdate' => '1',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_INHERIT_CREATOR_CUSTOM_INFO',
        ),
        'inherit_parent' => array(
            'required' => false,
            'name' => 'inherit_parent',
            'vname' => 'LBL_INHERIT_PARENT',
            'type' => 'bool',
            'massupdate' => '1',
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_INHERIT_PARENT_CUSTOM_INFO',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'unified_search_default_enabled' => false,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Security_Groups_Rules', 'stic_Security_Groups_Rules', array('basic'));
