<?php
function install_gmaps() {

    require_once('ModuleInstall/ModuleInstaller.php');
    $ModuleInstaller = new ModuleInstaller();
    $ModuleInstaller->install_custom_fields(getCustomFields());

}

function getCustomFields(){
    $custom_fields =
  array (
      'Accountsjjwg_maps_lng_c' =>
      array (
          'id' => 'Accountsjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Accounts',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Accountsjjwg_maps_lat_c' =>
      array (
          'id' => 'Accountsjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Accounts',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Accountsjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Accountsjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Accounts',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Accountsjjwg_maps_address_c' =>
      array (
          'id' => 'Accountsjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Accounts',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Casesjjwg_maps_lng_c' =>
      array (
          'id' => 'Casesjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Cases',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Casesjjwg_maps_lat_c' =>
      array (
          'id' => 'Casesjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Cases',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Casesjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Casesjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Cases',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Casesjjwg_maps_address_c' =>
      array (
          'id' => 'Casesjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Cases',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Contactsjjwg_maps_lng_c' =>
      array (
          'id' => 'Contactsjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Contacts',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Contactsjjwg_maps_lat_c' =>
      array (
          'id' => 'Contactsjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Contacts',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Contactsjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Contactsjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Contacts',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Contactsjjwg_maps_address_c' =>
      array (
          'id' => 'Contactsjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Contacts',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Leadsjjwg_maps_lng_c' =>
      array (
          'id' => 'Leadsjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Leads',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Leadsjjwg_maps_lat_c' =>
      array (
          'id' => 'Leadsjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Leads',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Leadsjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Leadsjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Leads',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Leadsjjwg_maps_address_c' =>
      array (
          'id' => 'Leadsjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Leads',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Meetingsjjwg_maps_lng_c' =>
      array (
          'id' => 'Meetingsjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Meetings',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Meetingsjjwg_maps_lat_c' =>
      array (
          'id' => 'Meetingsjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Meetings',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Meetingsjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Meetingsjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Meetings',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default_value' => NULL,
          'date_modified' => '2012-08-17 22:06:01',
          'deleted' => '0',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Meetingsjjwg_maps_address_c' =>
      array (
          'id' => 'Meetingsjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Meetings',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Opportunitiesjjwg_maps_lng_c' =>
      array (
          'id' => 'Opportunitiesjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Opportunities',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Opportunitiesjjwg_maps_lat_c' =>
      array (
          'id' => 'Opportunitiesjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Opportunities',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Opportunitiesjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Opportunitiesjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Opportunities',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Opportunitiesjjwg_maps_address_c' =>
      array (
          'id' => 'Opportunitiesjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Opportunities',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Projectjjwg_maps_lng_c' =>
      array (
          'id' => 'Projectjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Project',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Projectjjwg_maps_lat_c' =>
      array (
          'id' => 'Projectjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Project',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Projectjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Projectjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Project',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Projectjjwg_maps_address_c' =>
      array (
          'id' => 'Projectjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Project',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2010-09-18 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Prospectsjjwg_maps_lng_c' =>
      array (
          'id' => 'Prospectsjjwg_maps_lng_c',
          'name' => 'jjwg_maps_lng_c',
          'label' => 'LBL_JJWG_MAPS_LNG',
          'comments' => NULL,
          'help' => 'Longitude',
          'module' => 'Prospects',
          'type' => 'float',
          'max_size' => '11',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Prospectsjjwg_maps_lat_c' =>
      array (
          'id' => 'Prospectsjjwg_maps_lat_c',
          'name' => 'jjwg_maps_lat_c',
          'label' => 'LBL_JJWG_MAPS_LAT',
          'comments' => NULL,
          'help' => 'Latitude',
          'module' => 'Prospects',
          'type' => 'float',
          'max_size' => '10',
          'require_option' => '0',
          'default' => '0.00000000',
          'default_value' => '0.00000000',
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'precision' => '8',
          'ext1' => '8',
      ),
      'Prospectsjjwg_maps_geocode_status_c' =>
      array (
          'id' => 'Prospectsjjwg_maps_geocode_status_c',
          'name' => 'jjwg_maps_geocode_status_c',
          'label' => 'LBL_JJWG_MAPS_GEOCODE_STATUS',
          'comments' => 'Geocode Status',
          'help' => 'Geocode Status',
          'module' => 'Prospects',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
      'Prospectsjjwg_maps_address_c' =>
      array (
          'id' => 'Prospectsjjwg_maps_address_c',
          'name' => 'jjwg_maps_address_c',
          'label' => 'LBL_JJWG_MAPS_ADDRESS',
          'comments' => 'Address',
          'help' => 'Address',
          'module' => 'Prospects',
          'type' => 'varchar',
          'max_size' => '255',
          'require_option' => '0',
          'default' => NULL,
          'default_value' => NULL,
          'date_modified' => '2012-08-17 22:06:01',
          'audited' => '0',
          'mass_update' => '0',
          'duplicate_merge' => '0',
          'reportable' => '1',
          'importable' => 'true',
          'ext1' => NULL,
      ),
  );

	return $custom_fields;
}
