<?php
/**
 * Products, Quotations & Invoices modules.
 * Extensions to SugarCRM
 * @package Advanced OpenSales for SugarCRM
 * @copyright SalesAgility Ltd http://www.salesagility.com
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author Salesagility Ltd <support@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/

$mod_strings = array (
  'LBL_ID' => 'ID',
  'LBL_MODULE_NAME' => 'Группы',
  'LBL_DATE_ENTERED' => 'Создано',
  'LBL_DATE_MODIFIED' => 'Изменено',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалена',
  'LBL_NAME' => 'Группа',
  'LBL_TOTAL_AMT' => 'Итого без скидки',
  'LBL_DISCOUNT_AMOUNT' => 'Скидка',
  'LBL_SUBTOTAL_AMOUNT' => 'Итого со скидкой',
  'LBL_TAX_AMOUNT' => 'Всего НДС',
  'LBL_SUBTOTAL_TAX_AMOUNT' => 'Итого учётом скидки и НДС',
  'LBL_GROUP_TOTAL' => 'ИТОГО С НДС',
  'LBL_LIST_NUM' => '№',
);
?>
