--
-- This file contains the data needed to create the custom fields of the SuiteCRM native modules. The data is contained inside the 
-- fields_meta_data sql table
--


INSERT INTO `fields_meta_data` (`id`, `custom_module`, `name`) VALUES
-- Accounts
('Accountsstic_acronym_c', 'Accounts', 'stic_acronym_c'),
('Accountsstic_shipping_address_type_c', 'Accounts', 'stic_shipping_address_type_c'),
('Accountsstic_shipping_address_county_c', 'Accounts', 'stic_shipping_address_county_c'),
('Accountsstic_shipping_address_region_c', 'Accounts', 'stic_shipping_address_region_c'),
('Accountsstic_category_c', 'Accounts', 'stic_category_c'),
('Accountsstic_identification_number_c', 'Accounts', 'stic_identification_number_c'),
('Accountsstic_language_c', 'Accounts', 'stic_language_c'),
('Accountsstic_billing_address_type_c', 'Accounts', 'stic_billing_address_type_c'),
('Accountsstic_billing_address_county_c', 'Accounts', 'stic_billing_address_county_c'),
('Accountsstic_billing_address_region_c', 'Accounts', 'stic_billing_address_region_c'),
('Accountsstic_relationship_type_c', 'Accounts', 'stic_relationship_type_c'),
('Accountsstic_postal_mail_return_reason_c', 'Accounts', 'stic_postal_mail_return_reason_c'),
('Accountsstic_182_error_c', 'Accounts', 'stic_182_error_c'),
('Accountsstic_182_excluded_c', 'Accounts', 'stic_182_excluded_c'),
('Accountsstic_subcategory_c', 'Accounts', 'stic_subcategory_c'),
('Accountsstic_tax_name_c', 'Accounts', 'stic_tax_name_c'),
('Accountsstic_total_annual_donations_c', 'Accounts', 'stic_total_annual_donations_c'),
('Accountsinc_id_c', 'Accounts', 'inc_id_c'),
('Accountsinc_activity_sector_c', 'Accounts', 'inc_activity_sector_c'),
('Accountsinc_address_block_c', 'Accounts', 'inc_address_block_c'),
('Accountsinc_address_district_c', 'Accounts', 'inc_address_district_c'),
('Accountsinc_address_door_c', 'Accounts', 'inc_address_door_c'),
('Accountsinc_address_floor_c', 'Accounts', 'inc_address_floor_c'),
('Accountsinc_address_num_a_c', 'Accounts', 'inc_address_num_a_c'),
('Accountsinc_address_num_b_c', 'Accounts', 'inc_address_num_b_c'),
('Accountsinc_address_postal_code_c', 'Accounts', 'inc_address_postal_code_c'),
('Accountsinc_address_street_c', 'Accounts', 'inc_address_street_c'),
('Accountsinc_address_street_type_c', 'Accounts', 'inc_address_street_type_c'),
('Accountsinc_agreement_avail_c', 'Accounts', 'inc_agreement_avail_c'),
('Accountsinc_agreement_inc_person_c', 'Accounts', 'inc_agreement_inc_person_c'),
('Accountsinc_agreement_inc_position_c', 'Accounts', 'inc_agreement_inc_position_c'),
('Accountsinc_agreement_comp_position_c', 'Accounts', 'inc_agreement_comp_position_c'),
('Accountsinc_agreement_signed_with_c', 'Accounts', 'inc_agreement_signed_with_c'),
('Accountsinc_agreement_territory_scop_c', 'Accounts', 'inc_agreement_territory_scop_c'),
('Accountsinc_agreement_comp_person_c', 'Accounts', 'inc_agreement_comp_person_c'),
('Accountsinc_agreement_start_date_c', 'Accounts', 'inc_agreement_start_date_c'),
('Accountsinc_cnae_n1_c', 'Accounts', 'inc_cnae_n1_c'),
('Accountsinc_cnae_n2_c', 'Accounts', 'inc_cnae_n2_c'),
('Accountsinc_cnae_n3_c', 'Accounts', 'inc_cnae_n3_c'),
('Accountsinc_collection_origin_c', 'Accounts', 'inc_collection_origin_c'),
('Accountsinc_communications_language_c', 'Accounts', 'inc_communications_language_c'),
('Accountsinc_company_territory_scop_c', 'Accounts', 'inc_company_territory_scop_c'),
('Accountsinc_contact_date_c', 'Accounts', 'inc_contact_date_c'),
('Accountsinc_contact_name_c', 'Accounts', 'inc_contact_name_c'),
('Accountsinc_contact_position_c', 'Accounts', 'inc_contact_position_c'),
('Accountsinc_contact_telephone_c', 'Accounts', 'inc_contact_telephone_c'),
('Accountsinc_employees_c', 'Accounts', 'inc_employees_c'),
('Accountsinc_location_c', 'Accounts', 'inc_location_c'),
('Accountsstic_incorpora_locations_id_c', 'Accounts', 'stic_incorpora_locations_id_c'),
('Accountsinc_observations_c', 'Accounts', 'inc_observations_c'),
('Accountsinc_occupations_c', 'Accounts', 'inc_occupations_c'),
('Accountsinc_size_c', 'Accounts', 'inc_size_c'),
('Accountsinc_status_c', 'Accounts', 'inc_status_c'),
('Accountsinc_country_c', 'Accounts', 'inc_country_c'),
('Accountsinc_type_c', 'Accounts', 'inc_type_c'),
('Accountsinc_incorpora_record_c', 'Accounts', 'inc_incorpora_record_c'),
('Accountsinc_synchronization_log_c', 'Accounts', 'inc_synchronization_log_c'),
('Accountsinc_synchronization_errors_c', 'Accounts', 'inc_synchronization_errors_c'),
('Accountsinc_synchronization_date_c', 'Accounts', 'inc_synchronization_date_c'),
('Accountsinc_reference_group_c', 'Accounts', 'inc_reference_group_c'),
('Accountsinc_reference_entity_c', 'Accounts', 'inc_reference_entity_c'),
('Accountsinc_reference_officer_c', 'Accounts', 'inc_reference_officer_c'),
('Accountsinc_state_code_c', 'Accounts', 'inc_state_code_c'),
('Accountsinc_municipality_code_c', 'Accounts', 'inc_municipality_code_c'),
('Accountsinc_town_code_c', 'Accounts', 'inc_town_code_c'),
('Accountsinc_state_c', 'Accounts', 'inc_state_c'),
('Accountsinc_municipality_c', 'Accounts', 'inc_municipality_c'),
('Accountsinc_town_c', 'Accounts', 'inc_town_c'),
-- Campaigns
('Campaignsparent_id', 'Campaigns', 'parent_id'),
('Campaignsparent_name', 'Campaigns', 'parent_name'),
('Campaignsparent_type', 'Campaigns', 'parent_type'),
('Campaignsstic_notification_prospect_list_names_c', 'Campaigns', 'stic_notification_prospect_list_names_c'),
-- Contacts
('Contactsstic_acquisition_channel_c', 'Contacts', 'stic_acquisition_channel_c'),
('Contactsstic_age_c', 'Contacts', 'stic_age_c'),
('Contactsstic_alt_address_county_c', 'Contacts', 'stic_alt_address_county_c'),
('Contactsstic_alt_address_region_c', 'Contacts', 'stic_alt_address_region_c'),
('Contactsstic_alt_address_type_c', 'Contacts', 'stic_alt_address_type_c'),
('Contactsstic_do_not_send_postal_mail_c', 'Contacts', 'stic_do_not_send_postal_mail_c'),
('Contactsstic_employment_status_c', 'Contacts', 'stic_employment_status_c'),
('Contactsstic_gender_c', 'Contacts', 'stic_gender_c'),
('Contactsstic_identification_number_c', 'Contacts', 'stic_identification_number_c'),
('Contactsstic_identification_type_c', 'Contacts', 'stic_identification_type_c'),
('Contactsstic_language_c', 'Contacts', 'stic_language_c'),
('Contactsstic_postal_mail_return_reason_c', 'Contacts', 'stic_postal_mail_return_reason_c'),
('Contactsstic_preferred_contact_channel_c', 'Contacts', 'stic_preferred_contact_channel_c'),
('Contactsstic_primary_address_county_c', 'Contacts', 'stic_primary_address_county_c'),
('Contactsstic_primary_address_region_c', 'Contacts', 'stic_primary_address_region_c'),
('Contactsstic_primary_address_type_c', 'Contacts', 'stic_primary_address_type_c'),
('Contactsstic_professional_sector_c', 'Contacts', 'stic_professional_sector_c'),
('Contactsstic_professional_sector_other_c', 'Contacts', 'stic_professional_sector_other_c'),
('Contactsstic_referral_agent_c', 'Contacts', 'stic_referral_agent_c'),
('Contactsstic_relationship_type_c', 'Contacts', 'stic_relationship_type_c'),
('Contactsstic_182_error_c', 'Contacts', 'stic_182_error_c'),
('Contactsstic_182_excluded_c', 'Contacts', 'stic_182_excluded_c'),
('Contactsstic_tax_name_c', 'Contacts', 'stic_tax_name_c'),
('Contactsstic_total_annual_donations_c', 'Contacts', 'stic_total_annual_donations_c'),
('Contactsstic_professional_profile_c', 'Contacts', 'stic_professional_profile_c'),
('Contactssepe_benefit_perceiver_c', 'Contacts', 'sepe_benefit_perceiver_c'),
('Contactssepe_disability_c', 'Contacts', 'sepe_disability_c'),
('Contactssepe_education_level_c', 'Contacts', 'sepe_education_level_c'),
('Contactssepe_immigrant_c', 'Contacts', 'sepe_immigrant_c'),
('Contactssepe_insertion_difficulties_c', 'Contacts', 'sepe_insertion_difficulties_c'),
('Contactsstic_incorpora_locations_id_c', 'Contacts', 'stic_incorpora_locations_id_c'),
('Contactsinc_address_block_c', 'Contacts', 'inc_address_block_c'),
('Contactsinc_address_district_c', 'Contacts', 'inc_address_district_c'),
('Contactsinc_address_door_c', 'Contacts', 'inc_address_door_c'),
('Contactsinc_address_floor_c', 'Contacts', 'inc_address_floor_c'),
('Contactsinc_address_num_a_c', 'Contacts', 'inc_address_num_a_c'),
('Contactsinc_address_num_b_c', 'Contacts', 'inc_address_num_b_c'),
('Contactsinc_address_postal_code_c', 'Contacts', 'inc_address_postal_code_c'),
('Contactsinc_address_street_c', 'Contacts', 'inc_address_street_c'),
('Contactsinc_address_street_type_c', 'Contacts', 'inc_address_street_type_c'),
('Contactsinc_car_use_c', 'Contacts', 'inc_car_use_c'),
('Contactsinc_children_c', 'Contacts', 'inc_children_c'),
('Contactsinc_collectives_c', 'Contacts', 'inc_collectives_c'),
('Contactsinc_communications_language_c', 'Contacts', 'inc_communications_language_c'),
('Contactsinc_country_c', 'Contacts', 'inc_country_c'),
('Contactsinc_derivation_c', 'Contacts', 'inc_derivation_c'),
('Contactsinc_disability_cert_id_c', 'Contacts', 'inc_disability_cert_id_c'),
('Contactsinc_disability_degree_c', 'Contacts', 'inc_disability_degree_c'),
('Contactsinc_disabled_children_c', 'Contacts', 'inc_disabled_children_c'),
('Contactsinc_driving_licenses_c', 'Contacts', 'inc_driving_licenses_c'),
('Contactsinc_economic_benefits_c', 'Contacts', 'inc_economic_benefits_c'),
('Contactsinc_employment_status_c', 'Contacts', 'inc_employment_status_c'),
('Contactsinc_employ_office_reg_time_c', 'Contacts', 'inc_employ_office_reg_time_c'),
('Contactsinc_geographical_proximity_c', 'Contacts', 'inc_geographical_proximity_c'),
('Contactsinc_id_c', 'Contacts', 'inc_id_c'),
('Contactsinc_incorporation_date_c', 'Contacts', 'inc_incorporation_date_c'),
('Contactsinc_incorpora_record_c', 'Contacts', 'inc_incorpora_record_c'),
('Contactsinc_job_characteristics_c', 'Contacts', 'inc_job_characteristics_c'),
('Contactsinc_location_c', 'Contacts', 'inc_location_c'),
('Contactsinc_lopd_consent_c', 'Contacts', 'inc_lopd_consent_c'),
('Contactsinc_max_commuting_time_c', 'Contacts', 'inc_max_commuting_time_c'),
('Contactsinc_nationality_c', 'Contacts', 'inc_nationality_c'),
('Contactsinc_observations_c', 'Contacts', 'inc_observations_c'),
('Contactsinc_own_vehicle_c', 'Contacts', 'inc_own_vehicle_c'),
('Contactsinc_people_in_charge_c', 'Contacts', 'inc_people_in_charge_c'),
('Contactsinc_requested_employment_c', 'Contacts', 'inc_requested_employment_c'),
('Contactsinc_requested_employment_det_c', 'Contacts', 'inc_requested_employment_det_c'),
('Contactsinc_requested_workday_c', 'Contacts', 'inc_requested_workday_c'),
('Contactsinc_travel_availability_c', 'Contacts', 'inc_travel_availability_c'),
('Contactsinc_unwanted_employments_c', 'Contacts', 'inc_unwanted_employments_c'),
('Contactsinc_synchronization_log_c', 'Contacts', 'inc_synchronization_log_c'),
('Contactsinc_synchronization_errors_c', 'Contacts', 'inc_synchronization_errors_c'),
('Contactsinc_synchronization_date_c', 'Contacts', 'inc_synchronization_date_c'),
('Contactsinc_reference_group_c', 'Contacts', 'inc_reference_group_c'),
('Contactsinc_reference_entity_c', 'Contacts', 'inc_reference_entity_c'),
('Contactsinc_reference_officer_c', 'Contacts', 'inc_reference_officer_c'),
('Contactsinc_state_code_c', 'Contacts', 'inc_state_code_c'),
('Contactsinc_municipality_code_c', 'Contacts', 'inc_municipality_code_c'),
('Contactsinc_town_code_c', 'Contacts', 'inc_town_code_c'),
('Contactsinc_state_c', 'Contacts', 'inc_state_c'),
('Contactsinc_municipality_c', 'Contacts', 'inc_municipality_c'),
('Contactsinc_town_c', 'Contacts', 'inc_town_c'),
-- Leads
('Leadsstic_acquisition_channel_c','Leads','stic_acquisition_channel_c'),
('Leadsstic_alt_address_county_c','Leads','stic_alt_address_county_c'),
('Leadsstic_alt_address_region_c','Leads','stic_alt_address_region_c'),
('Leadsstic_alt_address_type_c','Leads','stic_alt_address_type_c'),
('Leadsstic_do_not_send_postal_mail_c','Leads','stic_do_not_send_postal_mail_c'),
('Leadsstic_employment_status_c','Leads','stic_employment_status_c'),
('Leadsstic_gender_c','Leads','stic_gender_c'),
('Leadsstic_identification_number_c','Leads','stic_identification_number_c'),
('Leadsstic_identification_type_c','Leads','stic_identification_type_c'),
('Leadsstic_language_c','Leads','stic_language_c'),
('Leadsstic_primary_address_county_c','Leads','stic_primary_address_county_c'),
('Leadsstic_primary_address_region_c','Leads','stic_primary_address_region_c'),
('Leadsstic_primary_address_type_c','Leads','stic_primary_address_type_c'),
('Leadsstic_postal_mail_return_reason_c','Leads','stic_postal_mail_return_reason_c'),
('Leadsstic_professional_sector_c','Leads','stic_professional_sector_c'),
('Leadsstic_professional_sector_other_c','Leads','stic_professional_sector_other_c'),
('Leadsstic_referral_agent_c','Leads','stic_referral_agent_c'),
-- Opportunities
('Opportunitiesstic_advance_date_c', 'Opportunities', 'stic_advance_date_c'),
('Opportunitiesstic_amount_awarded_c', 'Opportunities', 'stic_amount_awarded_c'),
('Opportunitiesstic_amount_received_c', 'Opportunities', 'stic_amount_received_c'),
('Opportunitiesstic_target_c', 'Opportunities', 'stic_target_c'),
('Opportunitiesstic_documentation_to_deliver_c', 'Opportunities', 'stic_documentation_to_deliver_c'),
('Opportunitiesstic_justification_date_c', 'Opportunities', 'stic_justification_date_c'),
('Opportunitiesstic_payment_date_c', 'Opportunities', 'stic_payment_date_c'),
('Opportunitiesstic_presentation_date_c', 'Opportunities', 'stic_presentation_date_c'),
('Opportunitiesstic_resolution_date_c', 'Opportunities', 'stic_resolution_date_c'),
('Opportunitiesstic_status_c', 'Opportunities', 'stic_status_c'),
('Opportunitiesstic_type_c', 'Opportunities', 'stic_type_c'),
('Opportunitiesstic_opportunity_url_c', 'Opportunities', 'stic_opportunity_url_c'),
('Opportunitiesstic_additional_information_c', 'Opportunities', 'stic_additional_information_c'),
-- FP_Event_Locations
('FP_Event_Locationsstic_address_county_c','FP_Event_Locations','stic_address_county_c'),
('FP_Event_Locationsstic_address_region_c','FP_Event_Locations','stic_address_region_c'),
-- Documents
('Documentsstic_shared_document_link_c','Documents','stic_shared_document_link_c'),
-- Project
('Projectstic_location_c','Project','stic_location_c'),
-- Users
('Usersinc_reference_entity_c', 'Users', 'inc_reference_entity_c'),
('Usersinc_reference_group_c', 'Users', 'inc_reference_group_c'),
('Usersinc_reference_officer_c', 'Users', 'inc_reference_officer_c'),
('Usersinc_incorpora_user_c', 'Users', 'inc_incorpora_user_c'),
('Userssda_allowed_c', 'Users', 'sda_allowed_c'),
('Usersstic_work_calendar_c', 'Users', 'stic_work_calendar_c'),
('Usersstic_clock_c', 'Users', 'stic_clock_c');
