<?php
/**
 * Advanced OpenWorkflow, Automating SugarCRM.
 * @package Advanced OpenWorkflow for SugarCRM
 * @copyright SalesAgility Ltd http://www.salesagility.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author SalesAgility <info@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/


$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Краткое описание',
  'LBL_MODULE_NAME' => 'Действия',
  'LBL_MODULE_TITLE' => 'Действия',
  'LBL_AOW_WORKFLOW_ID' => 'AOW_WorkFlow Id',
  'LBL_ACTION' => 'Действие',
  'LBL_PARAMETERS' => 'Параметры',
  'LBL_SENDEMAIL' => 'Отправить E-mail',
  'LBL_CREATERECORD' => 'Создать запись',
  'LBL_MODIFYRECORD' => 'Изменить запись',
  'LBL_SELECT_ACTION' => 'Выберите действие',
  'LBL_CREATE_EMAIL_TEMPLATE' => 'Создать',
  'LBL_RECORD_TYPE' =>  'Тип записи',
  'LBL_ADD_FIELD' => 'Добавить поле',
  'LBL_ADD_RELATIONSHIP' => 'Добавить связь',
  'LBL_EDIT_EMAIL_TEMPLATE' => 'Изменить',
  'LBL_EMAIL' => 'Указать E-mail',
  'LBL_EMAIL_TEMPLATE' => 'Шаблон E-mail',
  'LBL_SETAPPROVAL' => 'Set Approval',
  'LBL_RELATE_WORKFLOW' => 'Связать с записью в контролируемом модуле',

);
