<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_MODULE_NAME' => 'Список адресатов' ,
'LBL_MODULE_ID'   => 'Списки адресатов',
'LBL_MODULE_TITLE' => 'Адресаты - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск списка адресатов' ,
'LBL_LIST_FORM_TITLE' => 'Список адресатов' ,
'LBL_PROSPECT_LIST_NAME' => 'Список адресатов' ,
'LBL_NAME' => 'Название' ,
'LBL_ENTRIES' => 'Всего записей' ,
'LBL_LIST_PROSPECT_LIST_NAME' => 'Список адресатов' ,
'LBL_LIST_ENTRIES' => 'Записи' ,
'LBL_LIST_DESCRIPTION' => 'Описание' ,
'LBL_LIST_TYPE_NO' => 'Тип' ,
'LBL_LIST_END_DATE' => 'Дата окончания' ,
'LBL_DATE_ENTERED' => 'Дата создания' ,
  'LBL_MARKETING_ID' => 'Маркет. кампания (ID)',
'LBL_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_MODIFIED' => 'Исправлено' ,
'LBL_CREATED' => 'Создано' ,
'LBL_TEAM' => 'Группа' ,
'LBL_ASSIGNED_TO' => 'Ответственный(ая)' ,
'LBL_DESCRIPTION' => 'Описание' ,
'LNK_NEW_CAMPAIGN' => 'Создать маркет. кампанию' ,
'LNK_CAMPAIGN_LIST' => 'Маркетинговые кампании' ,
'LNK_NEW_PROSPECT_LIST' => 'Создать список адресатов' ,
'LNK_PROSPECT_LIST_LIST' => 'Списки адресатов' ,
'LBL_MODIFIED_BY' => 'Кем исправлено' ,
'LBL_CREATED_BY' => 'Кем создано' ,
'LBL_DATE_CREATED' => 'Дата создания' ,
'LBL_DATE_LAST_MODIFIED' => 'Дата изменения' ,
'LNK_NEW_PROSPECT' => 'Создать адресата' ,
'LNK_PROSPECT_LIST' => 'Адресаты' ,

'LBL_PROSPECT_LISTS_SUBPANEL_TITLE' => 'Адресаты' ,
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_LEADS_SUBPANEL_TITLE' => 'Предварительные контакты' ,
'LBL_PROSPECTS_SUBPANEL_TITLE'=> 'Адресаты' ,
'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'Контрагенты',
'LBL_COPY_PREFIX' => 'Копия для' ,
'LBL_USERS_SUBPANEL_TITLE' => 'Пользователи' ,
'LBL_TYPE' => 'Тип' ,
'LBL_LIST_TYPE' => 'Тип:' ,
'LBL_LIST_TYPE_LIST_NAME'=> 'Тип' ,
'LBL_NEW_FORM_TITLE'=> 'Новый список адресатов' ,
'LBL_MARKETING_NAME'=> 'Название маркетинговой кампании',
'LBL_MARKETING_MESSAGE'=> 'Отправить маркетинговое сообщение' ,
'LBL_DOMAIN_NAME'=> 'Имя домена' ,
'LBL_DOMAIN'=> 'Нет писем в домене:'  ,
'LBL_LIST_PROSPECTLIST_NAME'=> 'Название',
'LBL_MORE_DETAIL' => 'Подробнее' /*for 508 compliance fix*/,
);


?>
