#!/usr/bin/env php
<?php
exec('cp tests/config_si.php config_si.php');
$_SERVER['HTTP_HOST'] = 'localhost';
$_SERVER['SERVER_NAME'] = 'localhost';
$_SERVER['SERVER_PORT'] = '80';
$_SERVER['REQUEST_URI'] = 'install.php';
$_REQUEST = array('goto' => 'SilentInstall', 'cli' => true);
require_once 'install.php';