<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_STEP_1' => 'Шаг 1: Выбор модуля и шаблона' ,
'LBL_MAILMERGE_MODULE' => 'Выбор модуля: ' ,
'LBL_MAILMERGE_SELECTED_MODULE' => 'Выбор модуля: ' ,
'LBL_MAILMERGE_TEMPLATES' => 'Выбор шаблона: ' ,
'LBL_STEP_2' => 'Шаг 2: Выбор объектов для слияния' ,
'LBL_MAILMERGE_OBJECTS' => 'Выбор объектов: ' ,
'LBL_STEP_3' => 'Установка контактных связей' ,
'LBL_STEP_4' => 'Просмотр и завершение' ,
'LBL_SELECTED_MODULE' => 'Выбранный модуль: ' ,
'LBL_SELECTED_TEMPLATE' => 'Выбранный шаблон: ' ,
'LBL_SELECTED_ITEMS' => 'Выбранные записи: ' ,
'LBL_STEP_5' => 'Слияние завершено' ,
'LBL_MERGED_FILE' => 'Файл слияния: ' ,
'LNK_NEW_MAILMERGE' => 'Новое слияние' ,
'LNK_UPLOAD_TEMPLATE' => 'Загрузить шаблон' ,
'LBL_DOC_NAME' => 'Название документа:' ,
'LBL_FILENAME' => 'Имя файла:' ,
'LBL_DOC_VERSION' => 'Версия:' ,
'LBL_DOC_DESCRIPTION'=> 'Описание:' ,
'LBL_LIST_NAME' => 'Название' ,
'LBL_LIST_RELATIONSHIP' => 'Установка контактных связей' ,
'LBL_FINISH' => 'Начать слияние' ,
'LBL_NEXT' => 'Вперёд >' ,
'LBL_BACK' => '< Назад' ,
'LBL_START' => 'Продолжить >>' ,
'LBL_TEMPLATE_NOTICE' => 'Шаблоны являются документами Microsoft Word, содержащими поля слияния, которые были загружены и сохранены в модуле "Документы". Подробности о процессе слияния Вы также можете узнать в справочной системе MS Word.' ,
'LBL_CONTAINS_CONTACT_INFO' => 'Выбранный шаблон содержит контактную информацию.' ,
'LBL_ADDIN_NOTICE' => 'Для работы данной функции требуется установленный плагин Sugar для Microsoft Word.' ,
'LBL_BROWSER_NOTICE' => 'Вы должны запустить IE 6.0 или старше для выполнения слияния.'  ,
'LBL_REMOVE' => 'Удалить' /*for 508 compliance fix*/,
'LBL_ADD' => 'Добавить' /*for 508 compliance fix*/,
'LBL_BROWSER_REQUIREMENT' => 'Необходим Internet Explorer версии 6.0 или выше.',
'LBL_FORM_SELECT_TEMPLATE' => 'Вы не выбрали шаблон.',
'LBL_SELECT_ONE' => 'Выберите как минимум одно значение.',
'LBL_AVAILABLE' => 'Доступные',
'LBL_SELECTED' => 'Выбранные',
'LBL_RELATED_INFO_SELECTION' => 'Используйте выбранные данные для определения соответствующей информации, которая должна быть отображена в конечном документе.<br> Пропустите этот шаг, если шаблон слияния не содержит необходимой информации.',

);


?>
