<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'ERR_NO_OPPS' => 'Ни одной сделки не найдено' ,
'LBL_ALL_OPPORTUNITIES' => 'Общая сумма по всем сделкам: ' ,
'LBL_CHART_TYPE' => 'Тип диаграммы:',
'LBL_CREATED_ON' => 'Создано: ' ,
'LBL_CLOSE_DATE_START' => 'Ожидаемая дата закрытия - С:',
'LBL_CLOSE_DATE_END'   => 'Ожидаемая дата закрытия - По:',
'LBL_DATE_END' => 'Дата окончания:' ,
'LBL_DATE_RANGE_TO' => 'по' ,
'LBL_DATE_RANGE' => 'Временной диапазон: с ' ,
'LBL_DATE_START' => 'Дата начала:' ,
'LBL_EDIT' => 'Править' ,
'LBL_LEAD_SOURCE_BY_OUTCOME_DESC' => 'Показ общей кумулятивной суммы по выбранным предварительным контактам по итоговой продукции для выбранных сотрудников.  Итог основан на продажах c результатами "Закрыто с выигрышем", "Закрыто с потерями" или любой другой величины.' ,
'LBL_LEAD_SOURCE_BY_OUTCOME' => 'Итоговые сделки по предварительным контактам' ,
'LBL_LEAD_SOURCE_FORM_DESC' => 'Показ накапливаемой суммы сделок, выбранной по предварительным контактам и выбранным сотрудникам.' ,
'LBL_LEAD_SOURCE_FORM_TITLE' => 'Все сделки по источникам предварительных контактов' ,
'LBL_LEAD_SOURCE_OTHER' => 'Другое' ,
'LBL_LEAD_SOURCES' => 'Источники предварительных контактов:' ,
'LBL_MODULE_NAME' => 'Диаграммы' ,
'LBL_MODULE_TITLE' => 'Диаграммы - ГЛАВНАЯ' ,
'LBL_MONTH_BY_OUTCOME_DESC' => 'Показ накопленных сумм сделок по месяцам по итогам для выбранных сотрудников, где дата закрытия находится внутри выбранного интервала дат.  Итог основан  на продажах c результатами "Закрыто с выигрышем", "Закрыто с потерями" или любой другой величины.' ,
'LBL_NUMBER_OF_OPPS' => 'Количество сделок',
'LBL_OPP_SIZE' => 'Размеры сделок в' ,
'LBL_OPP_THOUSANDS'=> ' тыс.' ,
'LBL_OPPS_IN_LEAD_SOURCE' => 'сделки, где предварительные контакты взяты из' ,
'LBL_OPPS_IN_STAGE' => ', в стадии продажи' ,
'LBL_OPPS_OUTCOME' => ', с результатом' ,
'LBL_OPPS_WORTH' => ', общей суммой' ,
'LBL_PIPELINE_FORM_TITLE_DESC' => 'Показ накопленных сумм по выбранным стадиям продаж для Ваших сделок, где ожидаемая дата закрытия находится внутри определённого интервала дат.' ,
'LBL_CAMPAIGN_ROI_TITLE_DESC' => 'Полученный доход от инвестиций.',
'LBL_REFRESH' => 'Обновить' ,
'LBL_ROLLOVER_DETAILS' => 'Наведите мышку на необходимую часть диаграммы для просмотра подробностей',
'LBL_ROLLOVER_WEDGE_DETAILS' => 'Нажмите на соотв. часть диаграммы для просмотра подробностей' ,
'LBL_SALES_STAGE_FORM_DESC' => 'Показ накопленных сумм сделок по выбранным стадиям продаж для выбранных сотрудников, где даты закрытия находятся внутри определённого интервала дат.' ,
'LBL_SALES_STAGE_FORM_TITLE' => 'Статистика по стадиям продаж' ,
'LBL_SALES_STAGES' => 'Стадии продаж:' ,
'LBL_TOTAL_PIPELINE' => 'Общая сумма: ' ,
'LBL_USERS' => 'Пользователи:' ,
'LBL_YEAR_BY_OUTCOME' => 'Итоговая статистика по месяцам' ,
'LBL_YEAR' => 'Год:' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_CALL' => 'Запланировать звонок' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_ISSUE' => 'Описать ошибку' ,
'LNK_NEW_LEAD' => 'Создать предв. контакт' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_NOTE' => 'Создать заметку или вложение' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_QUOTE' => 'Создать предложение' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'NTC_NO_LEGENDS' => 'Нет'  ,

'LBL_TITLE' => 'Заголовок: ',
'LBL_MY_MODULES_USED_SIZE' => 'Access Count', ///

'LBL_CHART_ACTION' => 'Action', ///
'LBL_CHART_PIPELINE_BY_SALES_STAGE' => 'Диаграмма стадий общих продаж',
'LBL_CHART_LEAD_SOURCE_BY_OUTCOME' => 'Диаграмма источников предварительных контактов',
'LBL_CHART_OUTCOME_BY_MONTH' => 'Итоговая статистика по месяцам',
'LBL_CHART_PIPELINE_BY_LEAD_SOURCE' => 'Диаграмма источников предварительных контактов',
'LBL_CHART_MY_PIPELINE_BY_SALES_STAGE' => 'Диаграмма стадий моих продаж',
'LBL_CHART_PIPELINE_BY_SALES_STAGE_FUNNEL' => 'Pipeline by Sales Stage Funnel', ///
'LBL_CHART_OPPORTUNITIES_THIS_QUARTER' => 'Opportunities this Quarter', ///
'LBL_CHART_MY_MODULES_USED_30_DAYS' => 'My Modules Used (Last 30 Days)', ///
'LBL_CHART_MODULES_USED_DIRECT_REPORTS_30_DAYS' => 'Modules Used By My Direct Reports (Last 30 Days)', ///
'LBL_CHART_DCE_ACTIONS_MONTH' => 'DCE Actions By Types (Current Month)', ///

);


?>
