<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
//DON'T CONVERT THESE THEY ARE MAPPINGS
'db_last_name' => 'LBL_LIST_LAST_NAME',
'db_first_name' => 'LBL_LIST_FIRST_NAME',
'db_title' => 'LBL_LIST_TITLE',
'db_email1' => 'LBL_LIST_EMAIL_ADDRESS',
'db_email2' => 'LBL_LIST_OTHER_EMAIL_ADDRESS',
//END DON'T CONVERT
'ERR_DELETE_RECORD' => 'Для удаления контакта необходимо указать номер записи.' ,
'LBL_ACCOUNT_ID' => 'ID контрагента:' ,
'LBL_ACCOUNT_NAME' => 'Контрагент:' ,
'LBL_CAMPAIGN'     => 'Маркет. кампания:',
'LBL_ACTIVITIES_SUBPANEL_TITLE'=> 'Мероприятия' ,
'LBL_ADD_BUSINESSCARD' => 'Ввести визитку' ,
'LBL_ADDMORE_BUSINESSCARD' => 'Добавить другую визитку' ,
'LBL_ADDRESS_INFORMATION' => 'Адресная информация' ,
'LBL_ALT_ADDRESS_CITY' => 'Другой адрес - город:' ,
'LBL_ALT_ADDRESS_COUNTRY' => 'Другой адрес - страна:' ,
'LBL_ALT_ADDRESS_POSTALCODE' => 'Другой адрес - индекс:' ,
'LBL_ALT_ADDRESS_STATE' => 'Другой адрес - область:' ,
'LBL_ALT_ADDRESS_STREET_2' => 'Другой адрес - улица 2:' ,
'LBL_ALT_ADDRESS_STREET_3' => 'Другой адрес - улица 3:' ,
'LBL_ALT_ADDRESS_STREET' => 'Другой адрес - улица:' ,
'LBL_ALTERNATE_ADDRESS' => 'Другой адрес:' ,
'LBL_ALT_ADDRESS' => 'Другой адрес:' ,
'LBL_ANY_ADDRESS' => 'Любой адрес:' ,
'LBL_ANY_EMAIL' => 'Любой E-mail:' ,
'LBL_ANY_PHONE' => 'Любой тел.:' ,
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)' ,
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая):',
'LBL_ASSISTANT_PHONE' => 'Помощник - тел.:' ,
'LBL_ASSISTANT' => 'Помощник:' ,
'LBL_BIRTHDATE' => 'День рождения:' ,
'LBL_BUSINESSCARD' => 'Визитка' ,
'LBL_CITY' => 'Город:' ,
'LBL_CAMPAIGN_ID' => 'Маркет. кампания(ID)',
'LBL_CONTACT_INFORMATION' => 'Основная информация' ,
'LBL_CONTACT_NAME' => 'Контактное лицо:' ,
'LBL_CONTACT_OPP_FORM_TITLE' => 'Сделки контакта:' ,
'LBL_CONTACT_ROLE' => 'Роль:' ,
'LBL_CONTACT' => 'Контакт:' ,
'LBL_COUNTRY' => 'Страна:' ,
'LBL_CREATED_ACCOUNT' => 'Создан новый контрагент' ,
'LBL_CREATED_CALL' => 'Создан новый звонок' ,
'LBL_CREATED_CONTACT' => 'Создан новый контакт' ,
'LBL_CREATED_MEETING' => 'Создана новая встреча' ,
'LBL_CREATED_OPPORTUNITY' => 'Создана новая сделка' ,
'LBL_DATE_MODIFIED' => 'Дата изменения:' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_DEPARTMENT' => 'Отдел:' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_DIRECT_REPORTS_SUBPANEL_TITLE'=> 'Подчинённые' ,
'LBL_DO_NOT_CALL' => 'Не звонить:' ,
'LBL_DUPLICATE' => 'Возможные дублирующие контакты' ,
'LBL_EMAIL_ADDRESS' => 'E-mail:' ,
'LBL_EMAIL_OPT_OUT' => 'Не писать на E-mail' ,
'LBL_EXISTING_ACCOUNT' => 'Использован существующий контрагент' ,
'LBL_EXISTING_CONTACT' => 'Использован существующий контакт' ,
'LBL_EXISTING_OPPORTUNITY'=> 'Использование существующей сделки' ,
'LBL_FAX_PHONE' => 'Факс:' ,
'LBL_FIRST_NAME' => 'Имя:' ,
'LBL_FULL_NAME' => 'Полное имя:' ,
'LBL_HISTORY_SUBPANEL_TITLE'=> 'История' ,
'LBL_HOME_PHONE' => 'Тел. (дом.):' ,
'LBL_ID' => 'ID:' ,
'LBL_IMPORT_VCARD' => 'Импортирование vCard' ,
'LBL_VCARD' => 'vCard',
'LBL_IMPORT_VCARDTEXT' => 'Автоматическое создание нового контакта при импортировании файла vCard.' ,
'LBL_INVALID_EMAIL'=> 'Неверный E-mail:' ,
'LBL_INVITEE' => 'Отчёты' ,
'LBL_LAST_NAME' => 'Фамилия:' ,
'LBL_LEAD_SOURCE' => 'Источник предв. контакта:' ,
'LBL_LIST_ACCEPT_STATUS' => 'Статус' ,
'LBL_LIST_ACCOUNT_NAME' => 'Контрагент' ,
'LBL_LIST_CONTACT_NAME' => 'Контактное лицо' ,
'LBL_LIST_CONTACT_ROLE' => 'Роль' ,
'LBL_LIST_EMAIL_ADDRESS' => 'E-mail' ,
'LBL_LIST_FIRST_NAME' => 'Имя' ,
'LBL_LIST_FORM_TITLE' => 'Список контактов' ,
'LBL_VIEW_FORM_TITLE' => 'Обзор контакта',
'LBL_LIST_LAST_NAME' => 'Фамилия' ,
'LBL_LIST_NAME' => 'ФИО' ,
'LBL_LIST_OTHER_EMAIL_ADDRESS' => 'Другой E-mail' ,
'LBL_LIST_PHONE' => 'Тел.' ,
'LBL_LIST_TITLE' => 'Должность' ,
'LBL_MOBILE_PHONE' => 'Тел. (моб.):' ,
'LBL_MODIFIED' => 'Изменено:' ,
'LBL_MODULE_NAME' => 'Контакты' ,
'LBL_MODULE_TITLE' => 'Контакты - ГЛАВНАЯ' ,
'LBL_NAME' => 'ФИО:' ,
'LBL_NEW_FORM_TITLE' => 'Новый контакт' ,
'LBL_NEW_PORTAL_PASSWORD' => 'Новый пароль портала:' ,
'LBL_NOTE_SUBJECT' => 'Заметки по теме' ,
'LBL_OFFICE_PHONE' => 'Тел. (раб.):' ,
'LBL_OPP_NAME' => 'Название сделки:' ,
'LBL_OPPORTUNITY_ROLE_ID'=> 'ID роли сделки:' ,
'LBL_OPPORTUNITY_ROLE'=> 'Роль в сделке:' ,
'LBL_OTHER_EMAIL_ADDRESS' => 'Другой E-mail:' ,
'LBL_OTHER_PHONE' => 'Другой тел.:' ,
'LBL_PHONE' => 'Тел.:' ,
'LBL_PORTAL_ACTIVE' => 'Портал включён:' ,
'LBL_PORTAL_APP'=> 'Портальные приложения' ,
'LBL_PORTAL_INFORMATION' => 'Портальная информация' ,
'LBL_PORTAL_NAME' => 'Название портала:' ,
'LBL_PORTAL_PASSWORD_ISSET' => 'Портальный пароль установлен:' ,
'LBL_STREET' => 'Улица',
'LBL_POSTAL_CODE' => 'Индекс:' ,
'LBL_PRIMARY_ADDRESS_CITY' => 'Основной адрес - город:' ,
'LBL_PRIMARY_ADDRESS_COUNTRY' => 'Основной адрес - страна:' ,
'LBL_PRIMARY_ADDRESS_POSTALCODE' => 'Основной адрес - индекс:' ,
'LBL_PRIMARY_ADDRESS_STATE' => 'Основной адрес - область:' ,
'LBL_PRIMARY_ADDRESS_STREET_2' => 'Основной адрес - улица 2:' ,
'LBL_PRIMARY_ADDRESS_STREET_3' => 'Основной адрес - улица 3:' ,
'LBL_PRIMARY_ADDRESS_STREET' => 'Основной адрес - улица:' ,
'LBL_PRIMARY_ADDRESS' => 'Основной адрес:' ,
'LBL_PRODUCTS_TITLE'=> 'Продукты' ,
'LBL_RELATED_CONTACTS_TITLE'=> 'Связанные контакты' ,
'LBL_REPORTS_TO_ID'=> 'Руководитель(ID)' ,
'LBL_REPORTS_TO' => 'Руководитель:' ,
'LBL_RESOURCE_NAME' => 'Название ресурса',
'LBL_SALUTATION' => 'Приветствие' ,
'LBL_SAVE_CONTACT' => 'Сохранить контакт' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск контактов' ,
'LBL_SELECT_CHECKED_BUTTON_LABEL' => 'Выбрать отмеченные контакты' ,
'LBL_SELECT_CHECKED_BUTTON_TITLE' => 'Выбрать отмеченные контакты' ,
'LBL_STATE' => 'Область:' ,
'LBL_SYNC_CONTACT' => 'Синхронизация с Outlook:' ,
'LBL_PROSPECT_LIST' => 'Список адресатов',
'LBL_TITLE' => 'Должность:' ,
'LNK_CONTACT_LIST' => 'Контакты' ,
'LNK_IMPORT_VCARD' => 'Создать контакт из vCard' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LNK_NEW_CALL' => 'Назначить звонок' ,
'LNK_NEW_CASE' => 'Создать обращение' ,
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_EMAIL' => 'Отправить E-mail в архив' ,
'LNK_NEW_MEETING' => 'Назначить встречу' ,
'LNK_NEW_NOTE' => 'Создать заметку' ,
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_SELECT_ACCOUNT' => 'Выбор контрагента' ,
'MSG_DUPLICATE' => 'Создаваемый вами контакт, возможно, дублирует уже имеющуюся запись. Контакты, содержащие схожие имена показаны ниже. <br>Нажмите на кнопку <b>Создать контакт</b> для создания новой записи или выберите существующую запись из списка.' ,
'MSG_SHOW_DUPLICATES' => 'Создаваемый вами контакт, возможно, дублирует уже имеющуюся запись. Контакты, содержащие схожие имена показаны ниже. Нажмите кнопку "Сохранить"  для продолжения создания нового контакта или кнопку "Отказаться" для возврата в модуль.',
'NTC_COPY_ALTERNATE_ADDRESS' => 'Копировать дополнительный адрес в основной' ,
'NTC_COPY_PRIMARY_ADDRESS' => 'Копировать основной адрес в дополнительный' ,
'NTC_DELETE_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись?' ,
'NTC_OPPORTUNITY_REQUIRES_ACCOUNT' => 'Создание сделки требует контрагента.\n Пожалуйста, или создайте нового контрагента или выберите из уже существующих.' ,
'NTC_REMOVE_CONFIRMATION' => 'Вы уверены, что хотите удалить этот контакт из данного обращения?' ,
'NTC_REMOVE_DIRECT_REPORT_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись из личных отчётов?' ,

'LBL_USER_PASSWORD' => 'Пароль:',

'LBL_LEADS_SUBPANEL_TITLE' => 'Предварительные контакты' ,
'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => 'Сделки' ,
'LBL_DOCUMENTS_SUBPANEL_TITLE' => 'Документы',
'LBL_COPY_ADDRESS_CHECKED_PRIMARY' => 'Копировать в основной адрес',
'LBL_COPY_ADDRESS_CHECKED_ALT' => 'Копировать в другой адрес' ,

'LBL_CASES_SUBPANEL_TITLE' => 'Обращения' ,
'LBL_BUGS_SUBPANEL_TITLE' => 'Ошибки' ,
'LBL_PROJECTS_SUBPANEL_TITLE' => 'Проекты' ,
'LBL_PROJECTS_RESOURCES' => 'Projects Resources', ///
'LBL_TARGET_OF_CAMPAIGNS' => 'Адресат маркет. кампании:' ,
'LBL_CAMPAIGNS'=> 'Маркет. кампании' ,
'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE'=> 'Маркет. кампании',
'LBL_LIST_CITY' => 'Город',
'LBL_LIST_STATE' => 'Область',
'LBL_HOMEPAGE_TITLE' => 'Мои контакты',
'LBL_OPPORTUNITIES' => 'Сделки',

'LBL_CHECKOUT_DATE'=> 'Дата проверки',
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты',
'LBL_PROJECT_SUBPANEL_TITLE' => 'Проекты',
'LBL_CAMPAIGNS_SUBPANEL_TITLE' => 'Маркетинговые кампании',
'LNK_IMPORT_CONTACTS' => 'Импорт контактов',

//For export labels
'LBL_PHONE_HOME' => 'Тел. (дом.)',
'LBL_PHONE_MOBILE' => 'Тел. (моб.)',
'LBL_PHONE_WORK' => 'Тел. (раб.)',
'LBL_PHONE_OTHER' => 'Другой тел.',
'LBL_PHONE_FAX' => 'Факс',
'LBL_CAMPAIGN_ID' => 'Маркет. кампания(ID)',

'LBL_EXPORT_ASSIGNED_USER_NAME' => 'Ответственный(ая)',
'LBL_EXPORT_ASSIGNED_USER_ID' => 'Ответственный(ая)-ID',
'LBL_EXPORT_MODIFIED_USER_ID' => 'Изменено(ID)',
'LBL_EXPORT_CREATED_BY' => 'Создано (ID)',
'LBL_EXPORT_PHONE_HOME' => 'Тел. (дом.)',
'LBL_EXPORT_PHONE_MOBILE' => 'Тел. (моб.)',
// SNIP
'LBL_CONTACT_HISTORY_SUBPANEL_TITLE' => 'Related Contacts\' Emails',
'LBL_USER_SYNC' => 'User Sync'
);

$mod_strings['LBL_AOP_CASE_UPDATES'] = 'Обновления обращения';
$mod_strings['LBL_CREATE_PORTAL_USER'] = "Создать пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER'] = "Включить пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER'] = "Отключить пользователя портала";
$mod_strings['LBL_CREATE_PORTAL_USER_FAILED'] = "Ошибка создания пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER_FAILED'] = "Ошибка включения пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER_FAILED'] = "Ошибка отключения пользователя портала";
$mod_strings['LBL_CREATE_PORTAL_USER_SUCCESS'] = "Создать пользователя портала";
$mod_strings['LBL_ENABLE_PORTAL_USER_SUCCESS'] = "Включить пользователя портала";
$mod_strings['LBL_DISABLE_PORTAL_USER_SUCCESS'] = "Отключить пользователя портала";
$mod_strings['LBL_NO_JOOMLA_URL'] = "Не указан URL портала";
$mod_strings['LBL_PORTAL_USER_TYPE'] = "Пользователь портала";



$mod_strings['LBL_FP_EVENTS_CONTACTS_FROM_FP_EVENTS_TITLE'] = 'События';
$mod_strings['LBL_FP_EVENT_DELEGATES_CONTACTS_1_FROM_FP_EVENT_DELEGATES_TITLE'] = 'Участники';



$mod_strings = array_merge($mod_strings,
	array(
		 'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => "Группы пользователей",
	)
	
	);
?>
