<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Goals'] = array(
    'table' => 'stic_goals',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'start_date' => array(
            'required' => true,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'expected_end_date' => array(
            'required' => false,
            'name' => 'expected_end_date',
            'vname' => 'LBL_EXPECTED_END_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'status' => array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_goals_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'origin' => array(
            'required' => true,
            'name' => 'origin',
            'vname' => 'LBL_ORIGIN',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_goals_origins_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'level' => array(
            'required' => false,
            'name' => 'level',
            'vname' => 'LBL_LEVEL',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_goals_levels_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'area' => array(
            'required' => false,
            'name' => 'area',
            'vname' => 'LBL_AREA',
            'type' => 'enum',
            'massupdate' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_goals_areas_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'subarea' => array(
            'required' => false,
            'name' => 'subarea',
            'vname' => 'LBL_SUBAREA',
            'type' => 'dynamicenum',
            'parentenum' => 'area',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_goals_subareas_list',
            'studio' => 'visible',
            'dbType' => 'enum',

        ),
        'actual_end_date' => array(
            'required' => false,
            'name' => 'actual_end_date',
            'vname' => 'LBL_ACTUAL_END_DATE',
            'type' => 'date',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'follow_up' => array(
            'required' => false,
            'name' => 'follow_up',
            'vname' => 'LBL_FOLLOW_UP',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '2',
        ),
        'stic_goals_contacts' => array(
            'name' => 'stic_goals_contacts',
            'type' => 'link',
            'relationship' => 'stic_goals_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_GOALS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_goals_contactscontacts_ida',
        ),
        'stic_goals_contacts_name' => array(
            'name' => 'stic_goals_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GOALS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => 1,
            'id_name' => 'stic_goals_contactscontacts_ida',
            'link' => 'stic_goals_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
        ),
        'stic_goals_contactscontacts_ida' => array(
            'name' => 'stic_goals_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_goals_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_CONTACTS_FROM_CONTACTS_TITLE',
        ),
        'stic_goals_project' => array(
            'name' => 'stic_goals_project',
            'type' => 'link',
            'relationship' => 'stic_goals_project',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_STIC_GOALS_PROJECT_FROM_PROJECT_TITLE',
            'id_name' => 'stic_goals_projectproject_ida',
        ),
        'stic_goals_project_name' => array(
            'name' => 'stic_goals_project_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GOALS_PROJECT_FROM_PROJECT_TITLE',
            'save' => 1,
            'id_name' => 'stic_goals_projectproject_ida',
            'link' => 'stic_goals_project',
            'table' => 'project',
            'module' => 'Project',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
        ),
        'stic_goals_projectproject_ida' => array(
            'name' => 'stic_goals_projectproject_ida',
            'type' => 'link',
            'relationship' => 'stic_goals_project',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_PROJECT_FROM_PROJECT_TITLE',
        ),
        'stic_goals_stic_registrations' => array(
            'name' => 'stic_goals_stic_registrations',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_registrations',
            'source' => 'non-db',
            'module' => 'stic_Registrations',
            'bean_name' => 'stic_Registrations',
            'vname' => 'LBL_STIC_GOALS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'id_name' => 'stic_goals_stic_registrationsstic_registrations_ida',
        ),
        'stic_goals_stic_registrations_name' => array(
            'name' => 'stic_goals_stic_registrations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GOALS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'save' => 1,
            'id_name' => 'stic_goals_stic_registrationsstic_registrations_ida',
            'link' => 'stic_goals_stic_registrations',
            'table' => 'stic_registrations',
            'module' => 'stic_Registrations',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
        ),
        'stic_goals_stic_registrationsstic_registrations_ida' => array(
            'name' => 'stic_goals_stic_registrationsstic_registrations_ida',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_registrations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
        ),
        'stic_goals_stic_assessments' => array(
            'name' => 'stic_goals_stic_assessments',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_assessments',
            'source' => 'non-db',
            'module' => 'stic_Assessments',
            'bean_name' => 'stic_Assessments',
            'vname' => 'LBL_STIC_GOALS_STIC_ASSESSMENTS_FROM_STIC_ASSESSMENTS_TITLE',
            'id_name' => 'stic_goals_stic_assessmentsstic_assessments_ida',
        ),
        'stic_goals_stic_assessments_name' => array(
            'name' => 'stic_goals_stic_assessments_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GOALS_STIC_ASSESSMENTS_FROM_STIC_ASSESSMENTS_TITLE',
            'save' => 1,
            'id_name' => 'stic_goals_stic_assessmentsstic_assessments_ida',
            'link' => 'stic_goals_stic_assessments',
            'table' => 'stic_assessments',
            'module' => 'stic_Assessments',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
            'inline_edit' => 0,
        ),
        'stic_goals_stic_assessmentsstic_assessments_ida' => array(
            'name' => 'stic_goals_stic_assessmentsstic_assessments_ida',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_assessments',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_STIC_ASSESSMENTS_FROM_STIC_ASSESSMENTS_TITLE',
        ),
        'stic_goals_stic_followups' => array(
            'name' => 'stic_goals_stic_followups',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_followups',
            'source' => 'non-db',
            'module' => 'stic_Goals',
            'bean_name' => 'stic_Goals',
            'vname' => 'LBL_STIC_GOALS_STIC_FOLLOWUPS_FROM_STIC_FOLLOWUPS_TITLE',
        ),
        'stic_goals_stic_goals' => array(
            'name' => 'stic_goals_stic_goals',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_goals',
            'source' => 'non-db',
            'module' => 'stic_Goals',
            'bean_name' => 'stic_Goals',
            'vname' => 'LBL_STIC_GOALS_STIC_GOALS_FROM_STIC_GOALS_R_TITLE',
        ),
        'stic_families_stic_goals' => array(
            'name' => 'stic_families_stic_goals',
            'type' => 'link',
            'relationship' => 'stic_families_stic_goals',
            'source' => 'non-db',
            'module' => 'stic_Families',
            'bean_name' => false,
            'vname' => 'LBL_STIC_FAMILIES_STIC_GOALS_FROM_STIC_FAMILIES_TITLE',
            'id_name' => 'stic_families_stic_goalsstic_families_ida',
        ),
        'stic_families_stic_goals_name' => array(
            'name' => 'stic_families_stic_goals_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FAMILIES_STIC_GOALS_FROM_STIC_FAMILIES_TITLE',
            'save' => true,
            'id_name' => 'stic_families_stic_goalsstic_families_ida',
            'link' => 'stic_families_stic_goals',
            'table' => 'stic_families',
            'module' => 'stic_Families',
            'rname' => 'name',
        ),
        'stic_families_stic_goalsstic_families_ida' => array(
            'name' => 'stic_families_stic_goalsstic_families_ida',
            'type' => 'link',
            'relationship' => 'stic_families_stic_goals',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FAMILIES_STIC_GOALS_FROM_STIC_GOALS_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Goals', 'stic_Goals', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Goals']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
