<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_FollowUps'] = array(
    'table' => 'stic_followups',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'channel' => array(
            'required' => false,
            'name' => 'channel',
            'vname' => 'LBL_CHANNEL',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_followups_channels_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'type' => array(
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_followups_types_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_followups_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'start_date' => array(
            'required' => true,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'datetimecombo',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
            'dbType' => 'datetime',
        ),
        'duration' => array(
            'required' => true,
            'name' => 'duration',
            'vname' => 'LBL_DURATION',
            'type' => 'int',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'numeric_range_search_dom',
            'disable_num_format' => '',
            'min' => 0,
            'max' => false,
            'validation' => array(
                'type' => 'range',
                'min' => 0,
                'max' => false,
            ),
        ),
        'subtype' => array(
            'required' => false,
            'name' => 'subtype',
            'vname' => 'LBL_SUBTYPE',
            'type' => 'dynamicenum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_followups_subtypes_list',
            'studio' => 'visible',
            'dbType' => 'enum',
            'parentenum' => 'type',
        ),
        'attendees' => array(
            'required' => false,
            'name' => 'attendees',
            'vname' => 'LBL_ATTENDEES',
            'type' => 'multienum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'options' => 'stic_followups_attendees_list',
            'studio' => 'visible',
            'isMultiSelect' => true,
        ),
        'pending_actions' => array(
            'required' => false,
            'name' => 'pending_actions',
            'vname' => 'LBL_PENDING_ACTIONS',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '2',
            'cols' => '40',
        ),
        'contact_id_c' => array(
            'required' => false,
            'name' => 'contact_id_c',
            'vname' => 'LBL_EXTERNAL_CONTACT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 36,
            'size' => '20',
        ),
        'external_contact' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'external_contact',
            'vname' => 'LBL_EXTERNAL_CONTACT',
            'type' => 'relate',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'contact_id_c',
            'ext2' => 'Contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'account_id_c' => array(
            'required' => false,
            'name' => 'account_id_c',
            'vname' => 'LBL_EXTERNAL_ACCOUNT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 36,
            'size' => '20',
        ),
        'external_account' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'external_account',
            'vname' => 'LBL_EXTERNAL_ACCOUNT',
            'type' => 'relate',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'account_id_c',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'stic_followups_id1_c' => array(
            'required' => false,
            'name' => 'stic_followups_id1_c',
            'vname' => 'LBL_FOLLOWUP_ORIGIN_STIC_FOLLOWUPS_ID',
            'type' => 'id',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 36,
            'size' => '20',
        ),
        'followup_origin' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'followup_origin',
            'vname' => 'LBL_FOLLOWUP_ORIGIN',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'stic_followups_id1_c',
            'ext2' => 'stic_FollowUps',
            'module' => 'stic_FollowUps',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'color' => array(
            'required' => false,
            'name' => 'color',
            'vname' => 'LBL_COLOR',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'options' => 'stic_colors_list',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '2',
            'inline_edit' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '50',
            'size' => '20',
            'popupHelp' => 'LBL_COLOR_INFO',
        ),
        'stic_followups_contacts' => array(
            'name' => 'stic_followups_contacts',
            'type' => 'link',
            'relationship' => 'stic_followups_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_FOLLOWUPS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_followups_contactscontacts_ida',
        ),
        'stic_followups_contacts_name' => array(
            'name' => 'stic_followups_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FOLLOWUPS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => 1,
            'id_name' => 'stic_followups_contactscontacts_ida',
            'link' => 'stic_followups_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
        ),
        'stic_followups_contactscontacts_ida' => array(
            'name' => 'stic_followups_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_followups_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FOLLOWUPS_CONTACTS_FROM_CONTACTS_TITLE',
        ),
        'stic_followups_project' => array(
            'name' => 'stic_followups_project',
            'type' => 'link',
            'relationship' => 'stic_followups_project',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_STIC_FOLLOWUPS_PROJECT_FROM_PROJECT_TITLE',
            'id_name' => 'stic_followups_projectproject_ida',
        ),
        'stic_followups_project_name' => array(
            'name' => 'stic_followups_project_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FOLLOWUPS_PROJECT_FROM_PROJECT_TITLE',
            'save' => 1,
            'id_name' => 'stic_followups_projectproject_ida',
            'link' => 'stic_followups_project',
            'table' => 'project',
            'module' => 'Project',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
        ),
        'stic_followups_projectproject_ida' => array(
            'name' => 'stic_followups_projectproject_ida',
            'type' => 'link',
            'relationship' => 'stic_followups_project',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FOLLOWUPS_PROJECT_FROM_PROJECT_TITLE',
        ),
        'stic_followups_stic_registrations' => array(
            'name' => 'stic_followups_stic_registrations',
            'type' => 'link',
            'relationship' => 'stic_followups_stic_registrations',
            'source' => 'non-db',
            'module' => 'stic_Registrations',
            'bean_name' => 'stic_Registrations',
            'vname' => 'LBL_STIC_FOLLOWUPS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'id_name' => 'stic_followups_stic_registrationsstic_registrations_ida',
        ),
        'stic_followups_stic_registrations_name' => array(
            'name' => 'stic_followups_stic_registrations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FOLLOWUPS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'save' => 1,
            'id_name' => 'stic_followups_stic_registrationsstic_registrations_ida',
            'link' => 'stic_followups_stic_registrations',
            'table' => 'stic_registrations',
            'module' => 'stic_Registrations',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
        ),
        'stic_followups_stic_registrationsstic_registrations_ida' => array(
            'name' => 'stic_followups_stic_registrationsstic_registrations_ida',
            'type' => 'link',
            'relationship' => 'stic_followups_stic_registrations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FOLLOWUPS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
        ),
        'stic_goals_stic_followups' => array(
            'name' => 'stic_goals_stic_followups',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_followups',
            'source' => 'non-db',
            'module' => 'stic_Goals',
            'bean_name' => 'stic_Goals',
            'vname' => 'LBL_STIC_GOALS_STIC_FOLLOWUPS_FROM_STIC_GOALS_TITLE',
            'id_name' => 'stic_goals_stic_followupsstic_goals_ida',
        ),
        'stic_goals_stic_followups_name' => array(
            'name' => 'stic_goals_stic_followups_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GOALS_STIC_FOLLOWUPS_FROM_STIC_GOALS_TITLE',
            'save' => 1,
            'id_name' => 'stic_goals_stic_followupsstic_goals_ida',
            'link' => 'stic_goals_stic_followups',
            'table' => 'stic_goals',
            'module' => 'stic_Goals',
            'rname' => 'name',
            'required' => 0,
        ),
        'stic_goals_stic_followupsstic_goals_ida' => array(
            'name' => 'stic_goals_stic_followupsstic_goals_ida',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_followups',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_STIC_FOLLOWUPS_FROM_STIC_GOALS_TITLE',
        ),

        'stic_families_stic_followups' => array(
            'name' => 'stic_families_stic_followups',
            'type' => 'link',
            'relationship' => 'stic_families_stic_followups',
            'source' => 'non-db',
            'module' => 'stic_Families',
            'bean_name' => false,
            'vname' => 'LBL_STIC_FAMILIES_STIC_FOLLOWUPS_FROM_STIC_FAMILIES_TITLE',
            'id_name' => 'stic_families_stic_followupsstic_families_ida',
        ),
        'stic_families_stic_followups_name' => array(
            'name' => 'stic_families_stic_followups_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FAMILIES_STIC_FOLLOWUPS_FROM_STIC_FAMILIES_TITLE',
            'save' => true,
            'id_name' => 'stic_families_stic_followupsstic_families_ida',
            'link' => 'stic_families_stic_followups',
            'table' => 'stic_families',
            'module' => 'stic_Families',
            'rname' => 'name',
        ),
        'stic_families_stic_followupsstic_families_ida' => array(
            'name' => 'stic_families_stic_followupsstic_families_ida',
            'type' => 'link',
            'relationship' => 'stic_families_stic_followups',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FAMILIES_STIC_FOLLOWUPS_FROM_STIC_FOLLOWUPS_TITLE',
        ),

    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_FollowUps', 'stic_FollowUps', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_FollowUps']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_FollowUps']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_FollowUps']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
