<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Accounts_Relationships'] = array(
    'table' => 'stic_accounts_relationships',
    'audited' => 1,
    'inline_edit' => 1,
    'duplicate_merge' => 1,
    'fields' => array(
        'start_date' => array(
            'required' => 0,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'validation' => array('type' => 'isbefore', 'compareto' => 'end_date', 'blank' => 1),
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => 1,
            'display_default' => 'today',
        ),
        'end_date' => array(
            'required' => 0,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'validation' => array('type' => 'isafter', 'compareto' => 'start_date', 'blank' => 1),
            'importable' => 1,
            'audited' => 0,
            'reportable' => 1,
            'unified_search' => 0,
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => 1,
            'inline_edit' => 1,
            'display_default' => '',
        ),
        'relationship_type' => array(
            'required' => 1,
            'name' => 'relationship_type',
            'vname' => 'LBL_RELATIONSHIP_TYPE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 0,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_accounts_relationships_types_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
            'default' => '',
        ),
        'role' => array(
            'required' => 0,
            'name' => 'role',
            'vname' => 'LBL_ROLE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_accounts_relationships_project_roles_list',
            'studio' => 'visible',
            'dependency' => 0,
        ),
        'end_reason' => array(
            'required' => 0,
            'name' => 'end_reason',
            'vname' => 'LBL_END_REASON',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_accounts_relationships_end_reasons_list',
            'studio' => 'visible',
            'dependency' => 0,
        ),
        'other_end_reasons' => array(
            'required' => 0,
            'name' => 'other_end_reasons',
            'vname' => 'LBL_OTHER_END_REASONS',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
        ),
        'active' => array(
            'required' => false,
            'name' => 'active',
            'vname' => 'LBL_ACTIVE',
            'type' => 'bool',
            'no_default' => false,
            'massupdate' => 0,
            'inline_edit' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'false',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '2',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'popupHelp' => 'LBL_ACTIVE_HELP',
            'studio' => array(
                'quickcreate' => false,
                'editview' => false),
        ),
        'stic_accounts_relationships_accounts' => array(
            'name' => 'stic_accounts_relationships_accounts',
            'type' => 'link',
            'relationship' => 'stic_accounts_relationships_accounts',
            'source' => 'non-db',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'id_name' => 'stic_accounts_relationships_accountsaccounts_ida',
        ),
        'stic_accounts_relationships_accounts_name' => array(
            'name' => 'stic_accounts_relationships_accounts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'save' => 1,
            'id_name' => 'stic_accounts_relationships_accountsaccounts_ida',
            'link' => 'stic_accounts_relationships_accounts',
            'table' => 'accounts',
            'module' => 'Accounts',
            'required' => 1,
            'rname' => 'name',
            'massupdate' => 1,
        ),
        'stic_accounts_relationships_accountsaccounts_ida' => array(
            'name' => 'stic_accounts_relationships_accountsaccounts_ida',
            'type' => 'link',
            'relationship' => 'stic_accounts_relationships_accounts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_ACCOUNTS_FROM_STIC_ACCOUNTS_RELATIONSHIPS_TITLE',
        ),
        'stic_accounts_relationships_project' => array(
            'name' => 'stic_accounts_relationships_project',
            'type' => 'link',
            'relationship' => 'stic_accounts_relationships_project',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_PROJECT_FROM_PROJECT_TITLE',
            'id_name' => 'stic_accounts_relationships_projectproject_ida',
        ),
        'stic_accounts_relationships_project_name' => array(
            'name' => 'stic_accounts_relationships_project_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_PROJECT_FROM_PROJECT_TITLE',
            'save' => 1,
            'id_name' => 'stic_accounts_relationships_projectproject_ida',
            'link' => 'stic_accounts_relationships_project',
            'table' => 'project',
            'module' => 'Project',
            'rname' => 'name',
            'massupdate' => 1,
        ),
        'stic_accounts_relationships_projectproject_ida' => array(
            'name' => 'stic_accounts_relationships_projectproject_ida',
            'type' => 'link',
            'relationship' => 'stic_accounts_relationships_project',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_ACCOUNTS_RELATIONSHIPS_PROJECT_FROM_STIC_ACCOUNTS_RELATIONSHIPS_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => 1,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Accounts_Relationships', 'stic_Accounts_Relationships', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Accounts_Relationships']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_Accounts_Relationships']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_Accounts_Relationships']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
