<?php
/**
 * Products, Quotations & Invoices modules.
 * Extensions to SugarCRM
 * @package Advanced OpenSales for SugarCRM
 * @subpackage Products
 * @copyright SalesAgility Ltd http://www.salesagility.com
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author Salesagility Ltd <support@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Название',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_FORM_TITLE' => 'Список товаров',
  'LBL_MODULE_NAME' => 'Товары',
  'LBL_MODULE_TITLE' => 'Товары',
  'LBL_HOMEPAGE_TITLE' => 'Мои товары',
  'LNK_NEW_RECORD' => 'Добавить товар',
  'LNK_LIST' => 'Товары',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск товара',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'Просмотр истории',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AOS_PRODUCTS_SUBPANEL_TITLE' => 'Товары',
  'LBL_NEW_FORM_TITLE' => 'Новые товары',
  'LBL_MAINCODE' => 'Код товара',
  'VALUE' => 'Название товара',
  'LBL_PART_NUMBER' => 'Артикул',
  'LBL_CATEGORY' => 'Категория',
  'LBL_TYPE' => 'Тип',
  'LBL_COST' => 'Себестоимость',
  'LBL_PRICE' => 'Цена по прайсу',
  'LBL_URL' => 'URL',
  'LBL_CONTACT' => 'Контакт',
  
  'LBL_PRODUCT_IMAGE' => 'Фото товара',
  'LBL_IMAGE_UPLOAD_FAIL' => 'ОШИБКА:  размер загружаемого файла превышает максимально допустимое значение, равное ',
  'LBL_AOS_PRODUCT_CATEGORYS_NAME' => 'Категория товара',
);
?>
