<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_ADD_ANOTHER_FILE'=> 'Добавить другой файл' ,
'LBL_ADD_DOCUMENT'=> 'Добавить документ' ,
'LBL_ADD_FILE'=> 'Добавить файл' ,
'LBL_ATTACHMENTS'=> 'Вложения' ,
'LBL_BODY'=> 'Тело:' ,
'LBL_CLOSE'=> 'Закрыто:' ,
'LBL_COLON'=> ':' ,
'LBL_DESCRIPTION'=> 'Описание:' ,
'LBL_EDIT_ALT_TEXT'=> 'Правка альтернативного текста' ,
'LBL_EMAIL_ATTACHMENT'=> 'Вложение E-mail' ,
'LBL_HIDE_ALT_TEXT'=> 'Скрыть альтернативный текст',
'LBL_HTML_BODY'=> 'Тело HTML' ,
'LBL_INSERT_VARIABLE'=> 'Вставить переменную:' ,
'LBL_INSERT_URL_REF'=> 'Вставить URL-ссылку' ,
'LBL_INSERT_TRACKER_URL'=> 'Вставить URL трекера:' ,
'LBL_INSERT'=> 'Вставить' ,
'LBL_LIST_DATE_MODIFIED'=> 'Последнее изменение' ,
'LBL_LIST_DESCRIPTION'=> 'Описание' ,
'LBL_LIST_FORM_TITLE'=> 'Список шаблонов E-mail' ,
'LBL_LIST_NAME'=> 'Название' ,
'LBL_MODULE_NAME'=> 'Шаблоны E-mail' ,
'LBL_MODULE_TITLE'=> 'Шаблоны E-mail: ГЛАВНАЯ' ,
'LBL_NAME'=> 'Название:' ,
'LBL_NEW_FORM_TITLE'=> 'Создать шаблон E-mail' ,
'LBL_PUBLISH'=> 'Публикация:' ,
'LBL_RELATED_TO'=> 'Относится к' ,
'LBL_SEARCH_FORM_TITLE'=> 'Поиск шаблонов E-mail' ,
'LBL_SHOW_ALT_TEXT'=> 'Показ альтернативного текста' ,
'LBL_SUBJECT'=> 'Тема:' ,
'LBL_SUGAR_DOCUMENT'        => 'Документ',
'LBL_TEAMS'=> 'Teams:', ///
'LBL_TEAMS_LINK'=> 'Teams', ///
'LBL_TEXT_BODY'=> 'Текст' ,
'LBL_USERS'=> 'Пользователи',

'LNK_ALL_EMAIL_LIST'=> 'Все E-mail' ,
'LNK_ARCHIVED_EMAIL_LIST'=> 'Архивированные E-mail' ,
'LNK_CHECK_EMAIL'=> 'Проверить почту' ,
'LNK_DRAFTS_EMAIL_LIST'=> 'Черновик' ,
'LNK_EMAIL_TEMPLATE_LIST'=> 'Шаблоны E-mail' ,
'LNK_IMPORT_NOTES'=> 'Импорт заметок' ,
'LNK_NEW_ARCHIVE_EMAIL'=> 'Создать архивный E-mail' ,
'LNK_NEW_EMAIL_TEMPLATE'=> 'Создать шаблон E-mail' ,
'LNK_NEW_EMAIL'=> 'Отправить E-mail в архив' ,
'LNK_NEW_SEND_EMAIL'=> 'Создать E-mail' ,
'LNK_SENT_EMAIL_LIST'=> 'Отправленные E-mail' ,
'LNK_VIEW_CALENDAR'=> 'Сегодня' ,
// for Inbox
'LBL_NEW'=> 'Новый' ,
'LNK_CHECK_MY_INBOX'=> 'Проверить почту' ,
'LNK_GROUP_INBOX'=> 'Групповые входящие' ,
'LNK_MY_ARCHIVED_LIST'=> 'Мои архивы' ,
'LNK_MY_DRAFTS'=> 'Мои черновики' ,
'LNK_MY_INBOX'=> 'Моя почта' ,
'LBL_LIST_BASE_MODULE'=> 'Base Module:', ///
'LBL_TEXT_ONLY'             => 'Только текст',
'LBL_SEND_AS_TEXT'          => 'Отправить только текст',
'LBL_ACCOUNT'               => 'Контрагент',
'LBL_BASE_MODULE'=> 'Главный модуль',
'LBL_FROM_NAME'=> 'От (имя)',
'LBL_PLAIN_TEXT'=> 'Обычный текст',
'LBL_CREATED_BY'=> 'Создано',
'LBL_FROM_ADDRESS'=> 'От (адрес)',
'LBL_PUBLISHED'=> 'Опубликовано',
'LBL_ACTIVITIES_REPORTS' => 'Отчёты по мероприятиям',
'LNK_VIEW_MY_INBOX' => 'Просмотр моих E-mail',
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
'LBL_EDIT_LAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
'LBL_SELECT' => 'Обзор' /*for 508 compliance fix*/,
'LBL_ID_FF_CLEAR' => 'Очистить' /*for 508 compliance fix*/,
'LBL_TYPE' => 'Тип',
);
?>
