DELETE FROM email_templates
	WHERE id='14f18ded-378d-ab84-3237-5e830d4e874d';
DELETE FROM email_templates
	WHERE id='267275d8-959c-6aed-8754-5e830d07fedf';
DELETE FROM email_templates
	WHERE id='483e1c3b-51dc-b5ab-e220-5e830d52596a';
DELETE FROM email_templates
	WHERE id='b4477938-f3c4-bef6-292c-5e830dee6ceb';
DELETE FROM email_templates
	WHERE id='bc4c87c3-febd-73d5-cf73-5e830dd3bac0';
DELETE FROM email_templates
	WHERE id='c4440a38-10b9-ef63-0e40-5e830d1c293d';
DELETE FROM email_templates
	WHERE id='c6c4093f-0a1a-30d8-5e33-5e830d6ddd51';
DELETE FROM email_templates
	WHERE id='e61c85c2-e6cb-6dda-3760-5e830d31fbdc';
DELETE FROM email_templates
	WHERE id='e9e00ea2-ac1b-a635-9671-5e830d66a582';
DELETE FROM email_templates
	WHERE id='ed9867a2-1f56-b684-4bc6-5e830d215b5d';

INSERT INTO `email_templates` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `published`, `name`, `description`, `subject`, `body`, `body_html`, `deleted`, `assigned_user_id`, `text_only`, `type`) VALUES
('14f18ded-378d-ab84-3237-5e830d4e874d', NOW(), NOW(), '1', '1', 'off', 'Caso actualizado (Usuarios)', 'Plantilla para informar a un usuario del CRM cuando se actualiza un caso que tiene asignado.', 'Actualización de: $acase_name (# $acase_case_number)', 'Hola, $user_first_name $user_last_name:\n\nSe ha actualizado el caso $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.\n\n$contact_first_name $contact_last_name dice:\n\n	$aop_case_updates_description\n\nPuedes revisar el caso en: $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id', '<p>Hola, $user_first_name $user_last_name:</p>\n<p> </p>\n<p>Se ha actualizado el caso $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.</p>\n <p><strong>$contact_first_name $contact_last_name dice:</strong></p>\n<p style="padding-left:30px;">$aop_case_updates_description</p>\n <p>Puedes revisar el caso en: $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id</p>', 0, 1, NULL, 'system'),
('267275d8-959c-6aed-8754-5e830d07fedf', NOW(), NOW(), '1', '1', 'off', 'Invitación a un evento', 'Plantilla de invitación a un evento.', 'Invitación a $fp_events_name', 'Apreciado/a $contact_name:\nHas sido invitado/a a $fp_events_name del $fp_events_date_start al $fp_events_date_end.\n$fp_events_description\nCordialmente,\n', '\n<p>Apreciado/a $contact_name:</p>\n<p>Has sido invitado/a a $fp_events_name del $fp_events_date_start al $fp_events_date_end.</p>\n<p>$fp_events_description</p>\n<p>Para aceptar esta invitación haz clic en Acepto.</p>\n<p> $fp_events_link o $fp_events_link_declined</p>\n<p>Cordialmente,</p>\n', 0, 1, NULL, 'system'),
('483e1c3b-51dc-b5ab-e220-5e830d52596a', NOW(), NOW(), '1', '1', 'off', 'Confirmación de alta voluntaria', 'Plantilla para confirmar el alta voluntaria de una persona.', 'Confirmación de alta voluntaria', 'Hola, $contact_first_name $contact_last_name:\nPor favor, confirma tu alta voluntaria haciendo clic en el enlace siguiente: $sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_email_address', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p>Por favor, confirma tu alta voluntaria haciendo clic en el enlace siguiente:\n <a href="$sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_confirm_opt_in_token">Alta voluntaria</a></p>\n', 0, 1, NULL, 'system'),
('b4477938-f3c4-bef6-292c-5e830dee6ceb', NOW(), NOW(), '1', '1', 'off', 'Contraseña generada por el sistema', 'Plantilla para notificar una contraseña a un usuario.', 'Información de la nueva cuenta', 'Aquí tienes tu nombre de usuario y una contraseña provisional:\nNombre de usuario: $contact_user_user_name\nContraseña: $contact_user_user_hash\n\n$config_site_url\n\nCuando accedas al sistema con esta contraseña, deberás cambiarla por otra de tu elección.', '<div><table width="550"><tbody><tr><td><p>Aquí tienes tu nombre de usuario y una contraseña provisional:</p>\n <p>Nombre de usuario: $contact_user_user_name</p>\n <p>Contraseña: $contact_user_user_hash</p>\n <p>$config_site_url</p>\n <p>Cuando accedas al sistema con esta contraseña, deberás cambiarla por otra de tu elección.</p></td></tr></tbody></table></div>', 0, 1, NULL, 'system'),
('bc4c87c3-febd-73d5-cf73-5e830dd3bac0', NOW(), NOW(), '1', '1', 'off', 'Contraseña olvidada', 'Plantilla para regenerar la contraseña de acceso al CRM.', 'Resetea tu contraseña', 'El $contact_user_pwd_last_changed has solicitado poder resetear tu contraseña.\n\nHaz clic en el enlace siguiente para resetearla: $contact_user_link_guid', '<div><table width="550"><tbody><tr><td><p>El $contact_user_pwd_last_changed has solicitado poder resetear tu contraseña.</p>\n <p>Haz clic en el enlace siguiente para resetearla: $contact_user_link_guid</p></td></tr></tbody></table></div>', 0, 1, NULL, 'system'),
('c4440a38-10b9-ef63-0e40-5e830d1c293d', NOW(), NOW(), '1', '1', 'off', 'Doble factor de autenticación', 'Plantilla para enviar un código de doble factor de autenticación.', 'Código de doble factor de autenticación', 'El código de doble factor de autenticación es $code.', '<div><table width="550"><tbody><tr><td><p>El código de doble factor de autenticación es <b>$code</b>.</p></td></tr></tbody></table></div>', 0, 1, NULL, 'system'),
('c6c4093f-0a1a-30d8-5e33-5e830d6ddd51', NOW(), NOW(), '1', '1', 'off', 'Caso actualizado (Personas)', 'Plantilla para enviar a una persona cuando se actualiza un caso con el que está relacionada', 'Actualización del caso: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nSe ha actualizado el caso $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.\n\n$contact_first_name $contact_last_name dice:\n\n	$aop_case_updates_description', '<p>Hola, $contact_first_name $contact_last_name:</p>\n	<p> </p>\n <p>Se ha actualizado el caso $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.</p>\n	<p><strong>$user_first_name $user_last_name dice:</strong></p>\n <p style="padding-left:30px;">$aop_case_updates_description</p>', 0, 1, NULL, 'system'),
('e61c85c2-e6cb-6dda-3760-5e830d31fbdc', NOW(), NOW(), '1', '1', 'off', 'Caso cerrado', 'Plantilla para informar a una persona que se ha cerrado un caso con el cual estaba relacionada.', 'Caso cerrado: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nEl caso $acase_name (# $acase_case_number) se ha cerrado el $acase_date_entered.\n\n	Estado:	$acase_status\n	Código:	$acase_case_number\n	Resolución:	$acase_resolution', '<p>Hola, $contact_first_name $contact_last_name:</p>\n	<p>El caso $acase_name (# $acase_case_number) se ha cerrado el $acase_date_entered</p>\n <table border="0"><tbody><tr><td>Estado</td><td>$acase_status</td></tr><tr><td>Código</td><td>$acase_case_number</td></tr><tr><td>Resolución</td><td>$acase_resolution</td></tr></tbody></table>', 0, 1, NULL, 'system'),
('e9e00ea2-ac1b-a635-9671-5e830d66a582', NOW(), NOW(), '1', '1', 'off', 'Caso creado', 'Plantilla para enviar a una persona cuando esta abre un caso.', 'Nuevo caso: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nHemos recibido tu caso $acase_name (# $acase_case_number) el $acase_date_entered.\n\n	Estado:	$acase_status\n	Código:	$acase_case_number\n	Descripción:	$acase_description', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p>Hemos recibido tu caso $acase_name (# $acase_case_number) el $acase_date_entered</p>\n <table border="0"><tbody><tr><td>Estado</td><td>$acase_status</td></tr><tr><td>Código</td><td>$acase_case_number</td></tr><tr><td>Descripción</td><td>$acase_description</td></tr></tbody></table>', 0, 1, NULL, 'system'),
('ed9867a2-1f56-b684-4bc6-5e830d215b5d', NOW(), NOW(), '1', '1', 'off', 'Cuenta creada', 'Plantilla para informar a una persona que se ha creado su cuenta del portal de casos.', 'Cuenta creada en el portal de soporte', 'Hola, $contact_name:\n\nYa dispones de una cuenta para acceder a $portal_address.\n\nPuedes acceder a él usando tu dirección de correo electrónico y la contraseña $joomla_pass.', '<p>Hola, $contact_name:</p>\n <p>Ya dispones de una cuenta para acceder a <a href="$portal_address">$portal_address</a>.</p>\n <p>Puedes acceder a él usando tu dirección de correo electrónico y la contraseña $joomla_pass.</p>', 0, 1, NULL, 'system');
