<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Events'] = array(
    'table' => 'stic_events',
    'audited' => 1,
    'inline_edit' => 1,
    'duplicate_merge' => 1,
    'fields' => array(
        'type' => array(
            'required' => 0,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_events_types_list',
            'studio' => 'visible',
            'dependency' => 0,
            'no_default' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
        ),
        'status' => array(
            'required' => 0,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_events_status_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
            'no_default' => 0,
            'reportable' => 1,
        ),
        'start_date' => array(
            'required' => 0,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'size' => '20',
            'enable_range_search' => 1,
            'options' => 'date_range_search_dom',
            'validation' => array('type' => 'isbefore', 'compareto' => 'end_date', 'blank' => 1),
            'inline_edit' => 1,
        ),
        'end_date' => array(
            'required' => 0,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'size' => '20',
            'enable_range_search' => 1,
            'options' => 'date_range_search_dom',
            'validation' => array('type' => 'isafter', 'compareto' => 'start_date', 'blank' => 1),
            'inline_edit' => 1,
        ),
        'timetable' => array(
            'required' => 0,
            'name' => 'timetable',
            'vname' => 'LBL_TIMETABLE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'inline_edit' => 1,
        ),
        'discard_reason' => array(
            'required' => 0,
            'name' => 'discard_reason',
            'vname' => 'LBL_DISCARD_REASON',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_events_discard_reasons_list',
            'studio' => 'visible',
            'dependency' => 0,
            'no_default' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
        ),
        'max_attendees' => array(
            'required' => 0,
            'name' => 'max_attendees',
            'vname' => 'LBL_MAX_ATTENDEES',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'inline_edit' => 1,
            'default' => 0,
        ),
        'status_not_invited' => array(
            'required' => 0,
            'name' => 'status_not_invited',
            'vname' => 'LBL_STATUS_NOT_INVITED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
        ),
        'status_invited' => array(
            'required' => 0,
            'name' => 'status_invited',
            'vname' => 'LBL_STATUS_INVITED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'inline_edit' => 0,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_confirmed' => array(
            'required' => 0,
            'name' => 'status_confirmed',
            'vname' => 'LBL_STATUS_CONFIRMED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'reportable' => 1,
            'inline_edit' => 0,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_rejected' => array(
            'required' => 0,
            'name' => 'status_rejected',
            'vname' => 'LBL_STATUS_REJECTED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_maybe' => array(
            'required' => 0,
            'name' => 'status_maybe',
            'vname' => 'LBL_STATUS_MAYBE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_didnt_take_part' => array(
            'required' => 0,
            'name' => 'status_didnt_take_part',
            'vname' => 'LBL_STATUS_DIDNT_TAKE_PART',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_took_part' => array(
            'required' => 0,
            'name' => 'status_took_part',
            'vname' => 'LBL_STATUS_TOOK_PART',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'status_drop_out' => array(
            'required' => 0,
            'name' => 'status_drop_out',
            'vname' => 'LBL_STATUS_DROP_OUT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'no_default' => 0,
            'inline_edit' => 0,
            'reportable' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'default' => 0,
        ),
        'budget' => array(
            'required' => 0,
            'name' => 'budget',
            'vname' => 'LBL_BUDGET',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'expected_cost' => array(
            'required' => 0,
            'name' => 'expected_cost',
            'vname' => 'LBL_EXPECTED_COST',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'actual_cost' => array(
            'required' => 0,
            'name' => 'actual_cost',
            'vname' => 'LBL_ACTUAL_COST',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'expected_income' => array(
            'required' => 0,
            'name' => 'expected_income',
            'vname' => 'LBL_EXPECTED_INCOME',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'actual_income' => array(
            'required' => 0,
            'name' => 'actual_income',
            'vname' => 'LBL_ACTUAL_INCOME',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'precision' => 2,
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '26',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'price' => array(
            'required' => 0,
            'name' => 'price',
            'vname' => 'LBL_PRICE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 1,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'default' => 0,
        ),
        'attendees' => array(
            'required' => 0,
            'name' => 'attendees',
            'vname' => 'LBL_ATTENDEES',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'int',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'disable_num_format' => '',
            'inline_edit' => 1,
            'default' => 0,
        ),
        'total_hours' => array(
            'name' => 'total_hours',
            'vname' => 'LBL_TOTAL_HOURS',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'module' => 'stic_Events',
            'len' => '10',
            'precision' => 2,
            'massupdate' => 0,
            'required' => 0,
            'audited' => 0,
            'importable' => 1,
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'inline_edit' => 1,
            'popupHelp' => 'LBL_TOTAL_HOURS_TITLE',
            'default' => 0,
        ),
        'session_amount' => array(
            'required' => 0,
            'name' => 'session_amount',
            'vname' => 'LBL_SESSION_AMOUNT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => '1',
            'audited' => 0,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline_edit' => 1,
            'popupHelp' => 'LBL_SESSION_AMOUNT_INFO',
        ),
        'session_color' => array(
            'required' => false,
            'name' => 'session_color',
            'vname' => 'LBL_SESSION_COLOR',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'options' => 'stic_colors_list',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '2',
            'inline_edit' => 0,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '50',
            'size' => '20',
            'popupHelp' => 'LBL_SESSION_COLOR_INFO',
        ),
        'stic_events_project' => array(
            'name' => 'stic_events_project',
            'type' => 'link',
            'relationship' => 'stic_events_project',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_STIC_EVENTS_PROJECT_FROM_PROJECT_TITLE',
            'id_name' => 'stic_events_projectproject_ida',
        ),
        'stic_events_project_name' => array(
            'name' => 'stic_events_project_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_EVENTS_PROJECT_FROM_PROJECT_TITLE',
            'save' => true,
            'id_name' => 'stic_events_projectproject_ida',
            'link' => 'stic_events_project',
            'table' => 'project',
            'module' => 'Project',
            'rname' => 'name',
            'massupdate' => 1,
            'inline_edit' => 1,
        ),
        'stic_events_projectproject_ida' => array(
            'name' => 'stic_events_projectproject_ida',
            'type' => 'link',
            'relationship' => 'stic_events_project',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_EVENTS_PROJECT_FROM_STIC_EVENTS_TITLE',
        ),
        'stic_events_fp_event_locations' => array(
            'name' => 'stic_events_fp_event_locations',
            'type' => 'link',
            'relationship' => 'stic_events_fp_event_locations',
            'source' => 'non-db',
            'module' => 'FP_Event_Locations',
            'bean_name' => 'FP_Event_Locations',
            'vname' => 'LBL_STIC_EVENTS_FP_EVENT_LOCATIONS_FROM_FP_EVENT_LOCATIONS_TITLE',
            'id_name' => 'stic_events_fp_event_locationsfp_event_locations_ida',
        ),
        'stic_events_fp_event_locations_name' => array(
            'name' => 'stic_events_fp_event_locations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_EVENTS_FP_EVENT_LOCATIONS_FROM_FP_EVENT_LOCATIONS_TITLE',
            'save' => true,
            'id_name' => 'stic_events_fp_event_locationsfp_event_locations_ida',
            'link' => 'stic_events_fp_event_locations',
            'table' => 'fp_event_locations',
            'module' => 'FP_Event_Locations',
            'massupdate' => 1,
            'inline_edit' => 1,
            'rname' => 'name',
        ),
        'stic_events_fp_event_locationsfp_event_locations_ida' => array(
            'name' => 'stic_events_fp_event_locationsfp_event_locations_ida',
            'type' => 'link',
            'relationship' => 'stic_events_fp_event_locations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_EVENTS_FP_EVENT_LOCATIONS_FROM_STIC_EVENTS_TITLE',
        ),

        'stic_registrations_stic_events' => array(
            'name' => 'stic_registrations_stic_events',
            'type' => 'link',
            'relationship' => 'stic_registrations_stic_events',
            'source' => 'non-db',
            'module' => 'stic_Registrations',
            'bean_name' => 'stic_Registrations',
            'side' => 'right',
            'vname' => 'LBL_STIC_REGISTRATIONS_STIC_EVENTS_FROM_STIC_REGISTRATIONS_TITLE',
        ),
        'stic_sessions_stic_events' => array(
            'name' => 'stic_sessions_stic_events',
            'type' => 'link',
            'relationship' => 'stic_sessions_stic_events',
            'source' => 'non-db',
            'module' => 'stic_Sessions',
            'bean_name' => 'stic_Sessions',
            'side' => 'right',
            'vname' => 'LBL_STIC_SESSIONS_STIC_EVENTS_FROM_STIC_SESSIONS_TITLE',
        ),
        // Centers relationship Vardef
        'stic_centers_stic_events' => array (
            'name' => 'stic_centers_stic_events',
            'type' => 'link',
            'relationship' => 'stic_centers_stic_events',
            'source' => 'non-db',
            'module' => 'stic_Centers',
            'bean_name' => 'stic_Centers',
            'vname' => 'LBL_STIC_CENTERS_STIC_EVENTS_FROM_STIC_CENTERS_TITLE',
            'id_name' => 'stic_centers_stic_eventsstic_centers_ida',
        ),
          'stic_centers_stic_events_name' => array (
            'name' => 'stic_centers_stic_events_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_CENTERS_STIC_EVENTS_FROM_STIC_CENTERS_TITLE',
            'save' => true,
            'id_name' => 'stic_centers_stic_eventsstic_centers_ida',
            'link' => 'stic_centers_stic_events',
            'table' => 'stic_centers',
            'module' => 'stic_Centers',
            'rname' => 'name',
          ),
          'stic_centers_stic_eventsstic_centers_ida' => array (
            'name' => 'stic_centers_stic_eventsstic_centers_ida',
            'type' => 'link',
            'relationship' => 'stic_centers_stic_events',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_CENTERS_STIC_EVENTS_FROM_STIC_EVENTS_TITLE',
          ),

    ),
    'relationships' => array(
    ),
    'optimistic_locking' => 1,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Events', 'stic_Events', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Events']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
