<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_MODULE_NAME' => 'Проект' ,
'LBL_MODULE_TITLE' => 'Проекты - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск проекта' ,
'LBL_LIST_FORM_TITLE' => 'Список проектов' ,
'LBL_HISTORY_TITLE' => 'История' ,

'LBL_ID' => 'ID:' ,
'LBL_DATE_ENTERED' => 'Дата создания:' ,
'LBL_DATE_MODIFIED' => 'Дата изменения:' ,
'LBL_ASSIGNED_USER_ID' => 'Ответственный(ая): ' ,
'LBL_ASSIGNED_USER_NAME' => 'Ответственный(ая):',
'LBL_MODIFIED_USER_ID' => 'Изменено(ID):' ,
'LBL_CREATED_BY' => 'Кем создано:' ,
'LBL_TEAM_ID' => 'Team:',
'LBL_NAME' => 'Название:' ,
'LBL_PDF_PROJECT_NAME' => 'Название проекта:',
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_DELETED' => 'Удалено:' ,
'LBL_DATE' => 'Дата:',
'LBL_DATE_START' => 'Дата начала:',
'LBL_DATE_END' => 'Дата окончания:',
'LBL_PRIORITY' => 'Приоритет:',
'LBL_STATUS' => 'Статус:',
'LBL_MY_PROJECTS' => 'Мои проекты',
'LBL_MY_PROJECT_TASKS' => 'Мои проектные задачи',

'LBL_TOTAL_ESTIMATED_EFFORT' => 'Предварительная оценка общих усилий (час.):' ,
'LBL_TOTAL_ACTUAL_EFFORT' => 'Реальные общие усилия (час.):' ,

'LBL_LIST_NAME' => 'Название' ,
'LBL_LIST_DAYS' => 'дней',
'LBL_LIST_ASSIGNED_USER_ID' => 'Ответственный(ая)' ,
'LBL_LIST_TOTAL_ESTIMATED_EFFORT' => 'Предварительная оценка общих усилий (час.)' ,
'LBL_LIST_TOTAL_ACTUAL_EFFORT' => 'Реальные общие усилия (час.)' ,
'LBL_LIST_UPCOMING_TASKS' => 'Ближайшие задачи (1 неделя)',
'LBL_LIST_OVERDUE_TASKS' => 'Просроченные задачи',
'LBL_LIST_OPEN_CASES' => 'Открытые обращения',
'LBL_LIST_END_DATE' => 'Дата окончания',
'LBL_LIST_TEAM_ID' => 'Team',


'LBL_PROJECT_SUBPANEL_TITLE' => 'Проекты' ,
'LBL_PROJECT_TASK_SUBPANEL_TITLE' => 'Проектные задачи' ,
'LBL_CONTACT_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_ACCOUNT_SUBPANEL_TITLE' => 'Контрагенты' ,
'LBL_OPPORTUNITY_SUBPANEL_TITLE' => 'Сделки' ,
'LBL_QUOTE_SUBPANEL_TITLE' => 'Сметы' ,

// quick create label
'LBL_NEW_FORM_TITLE' => 'Новый проект',

'CONTACT_REMOVE_PROJECT_CONFIRM' => 'Вы уверены, что хотите удалить этот контакт из проекта?' ,

'LNK_NEW_PROJECT'=> 'Создать проект' ,
'LNK_PROJECT_LIST'=> 'Проекты' ,
'LNK_NEW_PROJECT_TASK'=> 'Создать задачу проекта' ,
'LNK_PROJECT_TASK_LIST'=> 'Проектные задачи' ,

'LBL_DEFAULT_SUBPANEL_TITLE' => 'Проекты' ,
'LBL_ACTIVITIES_TITLE'=> 'Мероприятия' ,
'LBL_ACTIVITIES_SUBPANEL_TITLE'=> 'Мероприятия' ,
'LBL_HISTORY_SUBPANEL_TITLE'=> 'История' ,
'LBL_QUICK_NEW_PROJECT'=> 'Создать проект' ,

'LBL_PROJECT_TASKS_SUBPANEL_TITLE' => 'Проектные задачи' ,
'LBL_CONTACTS_SUBPANEL_TITLE' => 'Контакты' ,
'LBL_ACCOUNTS_SUBPANEL_TITLE' => 'Контрагенты' ,
'LBL_OPPORTUNITIES_SUBPANEL_TITLE' => 'Сделки',
'LBL_CASES_SUBPANEL_TITLE' => 'Обращения',
'LBL_BUGS_SUBPANEL_TITLE' => 'Ошибки',
'LBL_PRODUCTS_SUBPANEL_TITLE' => 'Products',


'LBL_TASK_ID' => 'ID',
'LBL_TASK_NAME' => 'Название задачи',
'LBL_DURATION' => 'Продолжительность',
'LBL_ACTUAL_DURATION' => 'Фактическая продолжительность',
'LBL_START' => 'Начало',
'LBL_FINISH' => 'Окончание',
'LBL_PREDECESSORS' => 'Предшественники',
'LBL_PERCENT_COMPLETE' => '% выполнения',
'LBL_MORE'  => 'Больше...',

'LBL_PERCENT_BUSY' => '% занято',
'LBL_TASK_ID_WIDGET' => 'id',
'LBL_TASK_NAME_WIDGET' => 'описание',
'LBL_DURATION_WIDGET' => 'продолжительность',
'LBL_START_WIDGET' => 'дата начала',
'LBL_FINISH_WIDGET' => 'дата окончания',
'LBL_PREDECESSORS_WIDGET' => 'предшественники_',
'LBL_PERCENT_COMPLETE_WIDGET' => 'Процент выполнения',
'LBL_EDIT_PROJECT_TASKS_TITLE'=> 'Редактировать проектные задачи',

'LBL_OPPORTUNITIES' => 'Сделки',
'LBL_LAST_WEEK' => 'Предыдущая',
'LBL_NEXT_WEEK' => 'Следующая',
'LBL_PROJECTRESOURCES_SUBPANEL_TITLE' => 'Project Resources', ///
'LBL_PROJECTTASK_SUBPANEL_TITLE' => 'Проектные задачи',
'LBL_HOLIDAYS_SUBPANEL_TITLE' => 'Holidays', ///
'LBL_PROJECT_INFORMATION' => 'Основная информация',
'LBL_EDITLAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
'LBL_INSERTROWS' => 'Добавить строки' /*for 508 compliance fix*/,
'LBL_PROJECT_INFORMATION' => 'Основная информация',
);
?>
