<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Assessments'] = array(
    'table' => 'stic_assessments',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'areas' => array(
            'required' => false,
            'name' => 'areas',
            'vname' => 'LBL_AREAS',
            'type' => 'multienum',
            'massupdate' => '1',
            'default' => '^^',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'options' => 'stic_assessments_areas_list',
            'studio' => 'visible',
            'isMultiSelect' => true,
        ),
        'assessment_date' => array(
            'required' => true,
            'name' => 'assessment_date',
            'vname' => 'LBL_ASSESSMENT_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'enable_range_search' => true,
            'options' => 'date_range_search_dom',
        ),
        'moment' => array(
            'required' => true,
            'name' => 'moment',
            'vname' => 'LBL_MOMENT',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_assessments_moments_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'scope' => array(
            'required' => true,
            'name' => 'scope',
            'vname' => 'LBL_SCOPE',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_assessments_scope_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'conclusions' => array(
            'required' => false,
            'name' => 'conclusions',
            'vname' => 'LBL_CONCLUSIONS',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '2',
            'cols' => '40',
        ),
        'recommendations' => array(
            'required' => false,
            'name' => 'recommendations',
            'vname' => 'LBL_RECOMMENDATIONS',
            'type' => 'multienum',
            'massupdate' => '1',
            'default' => '^^',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'options' => 'stic_assessments_recommendations_list',
            'studio' => 'visible',
            'isMultiSelect' => true,
        ),
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_assessments_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'account_id_c' => array(
            'required' => false,
            'name' => 'account_id_c',
            'vname' => 'LBL_ACCOUNT_ID',
            'type' => 'id',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 36,
            'size' => '20',
        ),
        'working_with' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'working_with',
            'vname' => 'LBL_WORKING_WITH',
            'type' => 'relate',
            'massupdate' => 1,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'account_id_c',
            'ext2' => 'Accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'derivation' => array(
            'required' => false,
            'name' => 'derivation',
            'vname' => 'LBL_DERIVATION',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_contacts_referral_agents_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'next_date' => array(
            'required' => false,
            'name' => 'next_date',
            'vname' => 'LBL_NEXT_DATE',
            'type' => 'date',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'enabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
        ),
        'stic_assessments_contacts' => array(
            'name' => 'stic_assessments_contacts',
            'type' => 'link',
            'relationship' => 'stic_assessments_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_ASSESSMENTS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_assessments_contactscontacts_ida',
        ),
        'stic_assessments_contacts_name' => array(
            'name' => 'stic_assessments_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_ASSESSMENTS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => 1,
            'id_name' => 'stic_assessments_contactscontacts_ida',
            'link' => 'stic_assessments_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'massupdate' => 1,
            'rname' => 'name',
            'required' => 0,
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
        ),
        'stic_assessments_contactscontacts_ida' => array(
            'name' => 'stic_assessments_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_assessments_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_ASSESSMENTS_CONTACTS_FROM_STIC_ASSESSMENTS_TITLE',
        ),

        'stic_goals_stic_assessments' => array(
            'name' => 'stic_goals_stic_assessments',
            'type' => 'link',
            'relationship' => 'stic_goals_stic_assessments',
            'source' => 'non-db',
            'module' => 'stic_Goals',
            'bean_name' => 'stic_Goals',
            'side' => 'right',
            'vname' => 'LBL_STIC_GOALS_STIC_ASSESSMENTS_FROM_STIC_GOALS_TITLE',
        ),
        'stic_families_stic_assessments' => array(
            'name' => 'stic_families_stic_assessments',
            'type' => 'link',
            'relationship' => 'stic_families_stic_assessments',
            'source' => 'non-db',
            'module' => 'stic_Families',
            'bean_name' => false,
            'vname' => 'LBL_STIC_FAMILIES_STIC_ASSESSMENTS_FROM_STIC_FAMILIES_TITLE',
            'id_name' => 'stic_families_stic_assessmentsstic_families_ida',
        ),
        'stic_families_stic_assessments_name' => array(
            'name' => 'stic_families_stic_assessments_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_FAMILIES_STIC_ASSESSMENTS_FROM_STIC_FAMILIES_TITLE',
            'save' => true,
            'id_name' => 'stic_families_stic_assessmentsstic_families_ida',
            'link' => 'stic_families_stic_assessments',
            'table' => 'stic_families',
            'module' => 'stic_Families',
            'rname' => 'name',
        ),
        'stic_families_stic_assessmentsstic_families_ida' => array(
            'name' => 'stic_families_stic_assessmentsstic_families_ida',
            'type' => 'link',
            'relationship' => 'stic_families_stic_assessments',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_FAMILIES_STIC_ASSESSMENTS_FROM_STIC_ASSESSMENTS_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Assessments', 'stic_Assessments', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Assessments']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_Assessments']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_Assessments']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
