<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Grants'] = array(
    'table' => 'stic_grants',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'start_date' => array(
            'required' => true,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'expected_end_date' => array(
            'required' => false,
            'name' => 'expected_end_date',
            'vname' => 'LBL_EXPECTED_END_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'renovation_date' => array(
            'required' => false,
            'name' => 'renovation_date',
            'vname' => 'LBL_RENOVATION_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'end_date' => array(
            'required' => false,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'amount' => array(
            'required' => false,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'decimal',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '18',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => true,
            'precision' => '2',
        ),
        'percentage' => array(
            'required' => false,
            'name' => 'percentage',
            'vname' => 'LBL_PERCENTAGE',
            'type' => 'decimal',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '18',
            'size' => '5',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => true,
            'precision' => '2',
        ),
        'returned_amount' => array(
            'required' => false,
            'name' => 'returned_amount',
            'vname' => 'LBL_RETURNED_AMOUNT',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '18',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => true,
            'precision' => '2',
        ),
        'active' => array(
            'required' => false,
            'name' => 'active',
            'vname' => 'LBL_ACTIVE',
            'type' => 'bool',
            'massupdate' => 0,
            'default' => '0',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => 0,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'popupHelp' => 'LBL_ACTIVE_HELP',
            'studio' => array(
                'quickcreate' => false,
                'editview' => false),
        ),
        'periodicity' => array(
            'required' => false,
            'name' => 'periodicity',
            'vname' => 'LBL_PERIODICITY',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_grants_periodicities_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'type' => array(
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_grants_types_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'subtype' => array(
            'required' => false,
            'name' => 'subtype',
            'vname' => 'LBL_SUBTYPE',
            'type' => 'dynamicenum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_grants_subtypes_list',
            'studio' => 'visible',
            'dbType' => 'enum',
            'parentenum' => 'type',
        ),
        'stic_grants_accounts' => array(
            'name' => 'stic_grants_accounts',
            'type' => 'link',
            'relationship' => 'stic_grants_accounts',
            'source' => 'non-db',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'vname' => 'LBL_STIC_GRANTS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'id_name' => 'stic_grants_accountsaccounts_ida',
        ),
        'stic_grants_accounts_name' => array(
            'name' => 'stic_grants_accounts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GRANTS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'save' => true,
            'id_name' => 'stic_grants_accountsaccounts_ida',
            'link' => 'stic_grants_accounts',
            'table' => 'accounts',
            'module' => 'Accounts',
            'rname' => 'name',
        ),
        'stic_grants_accountsaccounts_ida' => array(
            'name' => 'stic_grants_accountsaccounts_ida',
            'type' => 'link',
            'relationship' => 'stic_grants_accounts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GRANTS_ACCOUNTS_FROM_STIC_GRANTS_TITLE',
        ),
        'stic_grants_contacts' => array(
            'name' => 'stic_grants_contacts',
            'type' => 'link',
            'relationship' => 'stic_grants_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_GRANTS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_grants_contactscontacts_ida',
        ),
        'stic_grants_contacts_name' => array(
            'name' => 'stic_grants_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GRANTS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => true,
            'id_name' => 'stic_grants_contactscontacts_ida',
            'link' => 'stic_grants_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
        ),
        'stic_grants_contactscontacts_ida' => array(
            'name' => 'stic_grants_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_grants_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GRANTS_CONTACTS_FROM_STIC_GRANTS_TITLE',
        ),
        'stic_grants_opportunities' => array(
            'name' => 'stic_grants_opportunities',
            'type' => 'link',
            'relationship' => 'stic_grants_opportunities',
            'source' => 'non-db',
            'module' => 'Opportunities',
            'bean_name' => 'Opportunity',
            'vname' => 'LBL_STIC_GRANTS_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
            'id_name' => 'stic_grants_opportunitiesopportunities_ida',
        ),
        'stic_grants_opportunities_name' => array(
            'name' => 'stic_grants_opportunities_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GRANTS_OPPORTUNITIES_FROM_OPPORTUNITIES_TITLE',
            'save' => true,
            'id_name' => 'stic_grants_opportunitiesopportunities_ida',
            'link' => 'stic_grants_opportunities',
            'table' => 'opportunities',
            'module' => 'Opportunities',
            'rname' => 'name',
        ),
        'stic_grants_opportunitiesopportunities_ida' => array(
            'name' => 'stic_grants_opportunitiesopportunities_ida',
            'type' => 'link',
            'relationship' => 'stic_grants_opportunities',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GRANTS_OPPORTUNITIES_FROM_STIC_GRANTS_TITLE',
        ),
        'stic_grants_project' => array(
            'name' => 'stic_grants_project',
            'type' => 'link',
            'relationship' => 'stic_grants_project',
            'source' => 'non-db',
            'module' => 'Project',
            'bean_name' => 'Project',
            'vname' => 'LBL_STIC_GRANTS_PROJECT_FROM_PROJECT_TITLE',
            'id_name' => 'stic_grants_projectproject_ida',
        ),
        'stic_grants_project_name' => array(
            'name' => 'stic_grants_project_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GRANTS_PROJECT_FROM_PROJECT_TITLE',
            'save' => true,
            'id_name' => 'stic_grants_projectproject_ida',
            'link' => 'stic_grants_project',
            'table' => 'project',
            'module' => 'Project',
            'rname' => 'name',
        ),
        'stic_grants_projectproject_ida' => array(
            'name' => 'stic_grants_projectproject_ida',
            'type' => 'link',
            'relationship' => 'stic_grants_project',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GRANTS_PROJECT_FROM_STIC_GRANTS_TITLE',
        ),
        'stic_grants_stic_families' => array(
            'name' => 'stic_grants_stic_families',
            'type' => 'link',
            'relationship' => 'stic_grants_stic_families',
            'source' => 'non-db',
            'module' => 'stic_Families',
            'bean_name' => 'stic_Families',
            'vname' => 'LBL_STIC_GRANTS_STIC_FAMILIES_FROM_STIC_FAMILIES_TITLE',
            'id_name' => 'stic_grants_stic_familiesstic_families_ida',
        ),
        'stic_grants_stic_families_name' => array(
            'name' => 'stic_grants_stic_families_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_GRANTS_STIC_FAMILIES_FROM_STIC_FAMILIES_TITLE',
            'save' => true,
            'id_name' => 'stic_grants_stic_familiesstic_families_ida',
            'link' => 'stic_grants_stic_families',
            'table' => 'stic_families',
            'module' => 'stic_Families',
            'rname' => 'name',
        ),
        'stic_grants_stic_familiesstic_families_ida' => array(
            'name' => 'stic_grants_stic_familiesstic_families_ida',
            'type' => 'link',
            'relationship' => 'stic_grants_stic_families',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_GRANTS_STIC_FAMILIES_FROM_STIC_FAMILIES_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Grants', 'stic_Grants', array('basic', 'assignable', 'security_groups'));
// Set special values for SuiteCRM base fields
$dictionary['stic_Grants']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
