<?php
/**
 * Advanced OpenWorkflow, Automating SugarCRM.
 * @package Advanced OpenWorkflow for SugarCRM
 * @copyright SalesAgility Ltd http://www.salesagility.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author SalesAgility <info@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Процесс',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Название',
  'LBL_LIST_FORM_TITLE' => 'Процессы',
  'LBL_MODULE_NAME' => 'Процесс',
  'LBL_MODULE_TITLE' => 'Процесс',
  'LBL_HOMEPAGE_TITLE' => 'Мои процессы',
  'LNK_NEW_RECORD' => 'Создать процесс',
  'LNK_LIST' => 'Процессы',
  'LNK_PROCESSED_LIST' => 'Контроль процессов',
  'LNK_IMPORT_AOW_WORKFLOW' => 'Импорт процесса',
  'LBL_SEARCH_FORM_TITLE' => 'Поиск процесса',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_AOW_WORKFLOW_SUBPANEL_TITLE' => 'Процесс',
  'LBL_NEW_FORM_TITLE' => 'Новый процесс',
  'LBL_FLOW_MODULE' => 'Контролируемый модуль',
  'LBL_STATUS' => 'Статус',
  'LBL_FLOW_RUN_ON' => 'Запускать для',
  'LNK_IMPORT_AOW_WORKFLOW' => 'Импорт процесса',
  'LBL_AOW_WORKFLOW_SUBPANEL_TITLE' => 'Процессы',
  'LBL_CONDITION_LINES' => 'Условия выполнения процесса',
  'LBL_ADD_CONDITION' => 'Добавить условие',
  'LBL_ACTION_LINES' => 'Выполняемые действия',
  'LBL_ADD_ACTION' => 'Добавить действие',
  'LBL_MULTIPLE_RUNS' => 'Множественный запуск',
);
