<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_MODULE_NAME' => 'Версии' ,
'LBL_MODULE_TITLE' => 'Версии - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск версий' ,
'LBL_LIST_FORM_TITLE' => 'Список версий' ,
'LBL_NEW_FORM_TITLE' => 'Новая версия' ,
'LBL_RELEASE' => 'Версия:' ,
'LBL_LIST_NAME' => 'Версия' ,
'LBL_NAME' => 'Версия:' ,
'LBL_LIST_LIST_ORDER' => 'Порядок' ,
'LBL_LIST_ORDER' => 'Порядок:' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_STATUS' => 'Статус:' ,
'LNK_NEW_RELEASE' => 'Список версий' ,
'NTC_DELETE_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись?' ,
'ERR_DELETE_RECORD' => 'Вы должны указать запись для удаления версии.' ,
'NTC_STATUS' => 'Установите статус на "Не активна" для удаления этой версии из списка' ,
'NTC_LIST_ORDER' => 'Установить порядок следования версий' ,
'release_status_dom' =>
array (
'Active' => 'Активна' ,
'Inactive' => 'Не активна'   ,
),
'LBL_EDITLAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
);


?>
