<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Journal'] = array(
    'table' => 'stic_journal',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'journal_date' => array(
            'required' => true,
            'name' => 'journal_date',
            'vname' => 'LBL_JOURNAL_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
            'display_default' => 'now',
        ),
        'type' => array(
            'required' => true,
            'name' => 'type',
            'vname' => 'LBL_TYPE',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_journal_types_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'turn' => array(
            'required' => false,
            'name' => 'turn',
            'vname' => 'LBL_TURN',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_journal_turns_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'task' => array(
            'required' => false,
            'name' => 'task',
            'vname' => 'LBL_TASK',
            'type' => 'multienum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'stic_journal_tasks_list',
            'studio' => 'visible',
            'isMultiSelect' => true,
        ),
        'task_scope' => array(
            'required' => false,
            'name' => 'task_scope',
            'vname' => 'LBL_TASK_SCOPE',
            'type' => 'multienum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'stic_journal_task_scopes_list',
            'studio' => 'visible',
            'isMultiSelect' => true,
        ),
        'task_start_date' => array(
            'required' => false,
            'name' => 'task_start_date',
            'vname' => 'LBL_TASK_START_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'task_end_date' => array(
            'required' => false,
            'name' => 'task_end_date',
            'vname' => 'LBL_TASK_END_DATE',
            'type' => 'datetimecombo',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'task_fulfillment' => array(
            'required' => false,
            'name' => 'task_fulfillment',
            'vname' => 'LBL_TASK_FULFILLMENT',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_journal_task_fulfillments_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'task_description' => array(
            'required' => false,
            'name' => 'task_description',
            'vname' => 'LBL_TASK_DESCRIPTION',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '4',
            'cols' => '20',
        ),
        'infringement_seriousness' => array(
            'required' => false,
            'name' => 'infringement_seriousness',
            'vname' => 'LBL_INFRINGEMENT_SERIOUSNESS',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_journal_seriousness_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'infringement_description' => array(
            'required' => false,
            'name' => 'infringement_description',
            'vname' => 'LBL_INFRINGEMENT_DESCRIPTION',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'studio' => 'visible',
            'rows' => '4',
            'cols' => '20',
        ),

        // Contacts relationship Vardef
        'stic_journal_contacts' => array(
            'name' => 'stic_journal_contacts',
            'type' => 'link',
            'relationship' => 'stic_journal_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_JOURNAL_CONTACTS_FROM_CONTACTS_TITLE',
        ),

        // Centers relationship Vardef
        'stic_journal_stic_centers' => array(
            'name' => 'stic_journal_stic_centers',
            'type' => 'link',
            'relationship' => 'stic_journal_stic_centers',
            'source' => 'non-db',
            'module' => 'stic_Centers',
            'bean_name' => 'stic_Centers',
            'vname' => 'LBL_STIC_JOURNAL_STIC_CENTERS_FROM_STIC_CENTERS_TITLE',
            'id_name' => 'stic_journal_stic_centersstic_centers_ida',
        ),
        'stic_journal_stic_centers_name' => array(
            'name' => 'stic_journal_stic_centers_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_JOURNAL_STIC_CENTERS_FROM_STIC_CENTERS_TITLE',
            'save' => true,
            'id_name' => 'stic_journal_stic_centersstic_centers_ida',
            'link' => 'stic_journal_stic_centers',
            'table' => 'stic_centers',
            'module' => 'stic_Centers',
            'rname' => 'name',
            'inline_edit' => 'false',
        ),
        'stic_journal_stic_centersstic_centers_ida' => array(
            'name' => 'stic_journal_stic_centersstic_centers_ida',
            'type' => 'link',
            'relationship' => 'stic_journal_stic_centers',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_JOURNAL_STIC_CENTERS_FROM_STIC_JOURNAL_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Journal', 'stic_Journal', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Journal']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_Journal']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_Journal']['fields']['name']['inline_edit'] = false; // Name can not edit inline in this module stic_journal_stic_centers_name
$dictionary['stic_Journal']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
