DELETE FROM email_templates
	WHERE id='14f18ded-378d-ab84-3237-5e830d4e874d';
DELETE FROM email_templates
	WHERE id='267275d8-959c-6aed-8754-5e830d07fedf';
DELETE FROM email_templates
	WHERE id='483e1c3b-51dc-b5ab-e220-5e830d52596a';
DELETE FROM email_templates
	WHERE id='b4477938-f3c4-bef6-292c-5e830dee6ceb';
DELETE FROM email_templates
	WHERE id='bc4c87c3-febd-73d5-cf73-5e830dd3bac0';
DELETE FROM email_templates
	WHERE id='c4440a38-10b9-ef63-0e40-5e830d1c293d';
DELETE FROM email_templates
	WHERE id='c6c4093f-0a1a-30d8-5e33-5e830d6ddd51';
DELETE FROM email_templates
	WHERE id='e61c85c2-e6cb-6dda-3760-5e830d31fbdc';
DELETE FROM email_templates
	WHERE id='e9e00ea2-ac1b-a635-9671-5e830d66a582';
DELETE FROM email_templates
	WHERE id='ed9867a2-1f56-b684-4bc6-5e830d215b5d';

INSERT INTO `email_templates` (`id`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `published`, `name`, `description`, `subject`, `body`, `body_html`, `deleted`, `assigned_user_id`, `text_only`, `type`) VALUES
('14f18ded-378d-ab84-3237-5e830d4e874d', NOW(), NOW(), '1', '1', 'off', 'Cas actualitzat (Usuaris)', 'Plantilla per informar un usuari del CRM quan s''actualitza un cas que té assignat.', 'Actualització de: $acase_name (# $acase_case_number)', 'Hola, $user_first_name $user_last_name:\n\nHi ha hagut una actualització del cas $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.\n\n$contact_first_name $contact_last_name diu:\n\n	$aop_case_updates_description\n\nPots revisar el cas a: $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id', '<p>Hola, $user_first_name $user_last_name:</p>\n	<p> </p>\n <p>Hi ha hagut una actualizació del cas $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.</p>\n <p><strong>$contact_first_name $contact_last_name diu:</strong></p>\n <p style="padding-left:30px;">$aop_case_updates_description</p>\n <p>Pots revisar el cas a: $sugarurl/index.php?module=Cases&action=DetailView&record=$acase_id</p>', 0, NULL, NULL, 'system'),
('267275d8-959c-6aed-8754-5e830d07fedf', NOW(), NOW(), '1', '1', 'off', 'Invitació a esdeveniment', 'Plantilla d''invitació a un esdeveniment.', 'Invitació a $fp_events_name', 'Benvolgut/da $contact_name:\nHas estat convidat/da a $fp_events_name del $fp_events_date_start al $fp_events_date_end.\n$fp_events_description\nCordialment,\n', '\n<p>Benvolgut/da $contact_name:</p>\n<p>Has estat convidat/da a $fp_events_name del $fp_events_date_start al $fp_events_date_end.</p>\n<p>$fp_events_description</p>\n<p>Si vols acceptar aquesta invitació fes clic a Accepto.</p>\n<p> $fp_events_link o $fp_events_link_declined</p>\n<p>Cordialment,</p>\n', 0, NULL, NULL, 'system'),
('483e1c3b-51dc-b5ab-e220-5e830d52596a', NOW(), NOW(), '1', '1', 'off', 'Confirmació d''alta voluntària', 'Plantilla per confirmar l''alta voluntària d''una persona.', 'Confirmació d''alta voluntària', 'Hola, $contact_first_name $contact_last_name:\nSi us plau, confirma la teva alta voluntària fent clic a l''enllaç següent: $sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_email_address', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p>Si us plau, confirma la teva alta voluntària fent clic a l''enllaç següent:\n <a href="$sugarurl/index.php?entryPoint=ConfirmOptIn&from=$emailaddress_confirm_opt_in_token">Alta voluntària</a></p>\n', 0, NULL, NULL, 'system'),
('b4477938-f3c4-bef6-292c-5e830dee6ceb', NOW(), NOW(), '1', '1', 'off', 'Contrasenya generada pel sistema', 'Plantilla per notificar una contrasenya a un usuari.', 'Informació del nou compte', 'Aquí tens el teu nom d''usuari i una contrasenya provisional:\nNom d''usuari: $contact_user_user_name\nContrasenya: $contact_user_user_hash\n\n$config_site_url\n\nUn cop accedeixis al sistema amb aquesta contrasenya, se''t demanarà que la canviïs per una de nova.', '<div><table width="550"><tbody><tr><td><p>Aquí tens el teu nom d''usuari i una contrasenya provisional:</p>\n <p>Nom d''usuari: $contact_user_user_name </p>\n <p>Contrasenya: $contact_user_user_hash </p>\n <p>$config_site_url</p>\n <p>Un cop accedeixis al sistema amb aquesta contrasenya, se''t demanarà que la canviïs per una de nova.</p></td></tr></tbody></table></div>', 0, NULL, 0, 'system'),
('bc4c87c3-febd-73d5-cf73-5e830dd3bac0', NOW(), NOW(), '1', '1', 'off', 'Contrasenya oblidada', 'Plantilla per regenerar la contrasenya d''accés al CRM.', 'Restableix la teva contrasenya', 'El $contact_user_pwd_last_changed has demanat poder restablir la teva contrasenya.\n\nFes clic al següent enllaç per restablir-la:\n\n$contact_user_link_guid', '<div><table width="550"><tbody><tr><td><p>El $contact_user_pwd_last_changed has demanat poder restablir la teva contrasenya. </p><p>Fes clic al següent enllaç per restablir-la:</p><p> $contact_user_link_guid </p>  </td>         </tr><tr><td></td>         </tr></tbody></table></div>', 0, NULL, 0, 'system'),
('c4440a38-10b9-ef63-0e40-5e830d1c293d', NOW(), NOW(), '1', '1', 'off', 'Doble factor d''autenticació', 'Plantilla per enviar un codi de doble factor d''autenticació.', 'Codi de doble factor d''autenticació', 'El codi de doble factor d''autenticació és $code.', '<div><table width="550"><tbody><tr><td><p>El codi de doble factor d''autenticació és <b>$code</b>.</p></td></tr></tbody></table></div>', 0, NULL, 0, 'system'),
('c6c4093f-0a1a-30d8-5e33-5e830d6ddd51', NOW(), NOW(), '1', '1', 'off', 'Cas actualitzat (Persones)', 'Plantilla per enviar a una persona quan s''actualitza un cas amb el qual està relacionada', 'Actualització del cas: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nHi ha hagut una actualització del cas $acase_name (# $acase_case_number) el $aop_case_updates_date_entered.\n\n$contact_first_name $contact_last_name diu:\n\n	aop_case_updates_description', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p> </p>\n <p>Hi ha hagut una actualització del cas $acase_name (# $acase_case_number) el $aop_case_updates_date_entered:</p>\n <p><strong>$user_first_name $user_last_name diu:</strong></p>\n <p style="padding-left:30px;">$aop_case_updates_description</p>', 0, NULL, NULL, 'system'),
('e61c85c2-e6cb-6dda-3760-5e830d31fbdc', NOW(), NOW(), '1', '1', 'off', 'Cas tancat', 'Plantilla per informar una persona que s''ha tancat un cas amb el qual estava relacionada.', 'Cas tancat: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nEl cas $acase_name (# $acase_case_number) s''ha tancat el $acase_date_entered.\n\n	Estat:	$acase_status\n	Codi:	$acase_case_number\n	Resolució:	$acase_resolution', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p>El cas $acase_name (# $acase_case_number) s''ha tancat el $acase_date_entered</p>\n <table border="0"><tbody><tr><td>Estat</td><td>$acase_status</td></tr><tr><td>Codi</td><td>$acase_case_number</td></tr><tr><td>Resolució</td><td>$acase_resolution</td></tr></tbody></table>', 0, NULL, NULL, 'system'),
('e9e00ea2-ac1b-a635-9671-5e830d66a582', NOW(), NOW(), '1', '1', 'off', 'Cas creat', 'Plantilla per enviar a una persona quan aquesta obre un cas.', 'Nou cas: $acase_name [$acase_case_number]', 'Hola, $contact_first_name $contact_last_name:\n\nHem rebut el teu cas $acase_name (# $acase_case_number) el $acase_date_entered.\n\n	Estat:	$acase_status\n	Codi:	$acase_case_number\n	Descripció:	$acase_description', '<p>Hola, $contact_first_name $contact_last_name:</p>\n <p>Hem rebut el teu cas $acase_name (# $acase_case_number) el $acase_date_entered</p>\n <table border="0"><tbody><tr><td>Estat</td><td>$acase_status</td></tr><tr><td>Codi</td><td>$acase_case_number</td></tr><tr><td>Descripció</td><td>$acase_description</td></tr></tbody></table>', 0, NULL, NULL, 'system'),
('ed9867a2-1f56-b684-4bc6-5e830d215b5d', NOW(), NOW(), '1', '1', 'off', 'Compte creat', 'Plantilla per informar una persona que se li ha creat un compte al portal de casos.', 'Compte creat al portal de suport', 'Hola, $contact_name:\n\n Ja disposes d''un compte per accedir a $portal_address.\n\n Pots connectar-t''hi fent servir la teva adreça electrònica i la contrasenya $joomla_pass.', '<p>Hola, $contact_name:</p>\n <p>Ja disposes d''un compte per accedir a <a href="$portal_address">$portal_address</a>.</p>\n	<p>Pots connectar-t''hi fent servir la teva adreça electrònica i la contrasenya $joomla_pass.</p>', 0, NULL, NULL, 'system');
