<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_MODULE_NAME' => 'Сотрудники' ,
'LBL_MODULE_TITLE' => 'Сотрудники - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск сотрудника' ,
'LBL_LIST_FORM_TITLE' => 'Сотрудники' ,
'LBL_NEW_FORM_TITLE' => 'Новый сотрудник' ,
'LBL_EMPLOYEE' => 'Сотрудники:' ,
'LBL_LOGIN' => 'Вход' ,
'LBL_RESET_PREFERENCES' => 'Установить стандартные значения' ,
'LBL_TIME_FORMAT' => 'Формат времени:' ,
'LBL_DATE_FORMAT' => 'Формат даты:' ,
'LBL_TIMEZONE' => 'Текущее время:' ,
'LBL_CURRENCY' => 'Валюта:' ,
'LBL_LIST_NAME' => 'ФИО' ,
'LBL_LIST_LAST_NAME' => 'Фамилия' ,
'LBL_LIST_EMPLOYEE_NAME' => 'ФИО сотрудника' ,
'LBL_LIST_DEPARTMENT' => 'Отдел' ,
'LBL_LIST_REPORTS_TO_NAME' => 'Руководитель' ,
'LBL_LIST_EMAIL' => 'E-mail' ,
'LBL_LIST_PRIMARY_PHONE' => 'Основной тел.' ,
'LBL_LIST_USER_NAME' => 'Логин' ,
'LBL_LIST_ADMIN' => 'Администрирование' ,
'LBL_NEW_EMPLOYEE_BUTTON_TITLE' => 'Новый сотрудник' ,
'LBL_NEW_EMPLOYEE_BUTTON_LABEL' => 'Новый сотрудник' ,
'LBL_NEW_EMPLOYEE_BUTTON_KEY' => 'N' ,
'LBL_ERROR' => 'Ошибка:' ,
'LBL_PASSWORD' => 'Пароль:' ,
'LBL_EMPLOYEE_NAME' => 'ФИО сотрудника:' ,
'LBL_USER_NAME' => 'Логин:' ,
'LBL_USER_TYPE'       => 'Тип пользователя',
'LBL_FIRST_NAME' => 'Имя:' ,
'LBL_LAST_NAME' => 'Фамилия:' ,
'LBL_EMPLOYEE_SETTINGS' => 'Настройки сотрудника' ,
'LBL_THEME' => 'Тема:' ,
'LBL_LANGUAGE' => 'Язык:' ,
'LBL_ADMIN' => 'Администратор:' ,
'LBL_EMPLOYEE_INFORMATION' => 'Информация о сотруднике' ,
'LBL_OFFICE_PHONE' => 'Тел. (раб.):' ,
'LBL_REPORTS_TO' => 'Руководитель (ID):',
'LBL_REPORTS_TO_NAME' => 'Руководитель:',
'LBL_OTHER_PHONE' => 'Другое:' ,
'LBL_OTHER_EMAIL' => 'Другой E-mail:' ,
'LBL_NOTES' => 'Заметки:' ,
'LBL_DEPARTMENT' => 'Отдел:' ,
'LBL_TITLE' => 'Должность:' ,
'LBL_ANY_ADDRESS' => 'Любой адрес:',
'LBL_ANY_PHONE' => 'Любой тел.:' ,
'LBL_ANY_EMAIL' => 'Любой E-mail:' ,
'LBL_ADDRESS' => 'Адрес:' ,
'LBL_CITY' => 'Город:' ,
'LBL_STATE' => 'Область:' ,
'LBL_POSTAL_CODE' => 'Индекс:' ,
'LBL_COUNTRY' => 'Страна:' ,
'LBL_NAME' => 'ФИО:' ,
'LBL_MOBILE_PHONE' => 'Тел. (моб.):' ,
'LBL_OTHER' => 'Другое:' ,
'LBL_FAX' => 'Факс:' ,
'LBL_EMAIL' => 'E-mail:' ,
'LBL_EMAIL_LINK_TYPE'=> 'Почтовый клиент',
'LBL_EMAIL_LINK_TYPE_HELP'=> '<b>Почтовый клиент Suite</b> - отправка электронных писем при помощи встроенного в Suite почтового клиента.<br><b>Внешний почтовый клиент</b> - любой другой почтовый клиент, например Microsoft Outlook.',
'LBL_HOME_PHONE' => 'Тел. (дом.):' ,
'LBL_WORK_PHONE' => 'Тел. (раб.):',
'LBL_ADDRESS_INFORMATION' => 'Адресная информация' ,
'LBL_EMPLOYEE_STATUS' => 'Статус сотрудника:' ,
'LBL_PRIMARY_ADDRESS' => 'Основной адрес:' ,
'LBL_SAVED_SEARCH' => 'Параметры макета',
'LBL_CREATE_USER_BUTTON_TITLE' => 'Создать пользователя' ,
'LBL_CREATE_USER_BUTTON_LABEL' => 'Создать пользователя' ,
'LBL_CREATE_USER_BUTTON_KEY' => 'N' ,
'LBL_FAVORITE_COLOR' => 'Любимый цвет:' ,
'LBL_MESSENGER_ID' => 'IM - имя / E-mail:' ,
'LBL_MESSENGER_TYPE' => 'IM-тип:' ,
'ERR_EMPLOYEE_NAME_EXISTS_1' => 'Имя сотрудника ' ,
'ERR_EMPLOYEE_NAME_EXISTS_2' => ' уже существует. Дублирование имён сотрудников не допускается.  Измените имя сотрудника, чтобы оно стало уникальным.' ,
'ERR_LAST_ADMIN_1' => 'Имя сотрудника \"' ,
'ERR_LAST_ADMIN_2' => '\" последний сотрудник с правами администратора. По крайней мере один сотрудник должен быть администратором.' ,
'LNK_NEW_EMPLOYEE' => 'Создать сотрудника' ,
'LNK_EMPLOYEE_LIST' => 'Сотрудники' ,
'ERR_DELETE_RECORD' => 'Перед удалением вы должны указать запись.',
'LBL_LIST_EMPLOYEE_STATUS' => 'Статус сотрудника',

'LBL_SUGAR_LOGIN' => 'Пользователь системы',
'LBL_RECEIVE_NOTIFICATIONS' => 'Уведомлять при назначении',
'LBL_IS_ADMIN' => 'Администратор',
'LBL_GROUP' => 'Групповой пользователь',
'LBL_PORTAL_ONLY'=> 'Пользователь портала',
'LBL_PHOTO'=> 'Фото',
'LBL_DELETE_USER_CONFIRM'           => 'Этот сотрудник также является пользователем системы. Удаление данного сотрудника приведёт к удалению соответствующей записи о пользователе системы; удалённый пользователь не будет иметь доступ к системе. Хотите продолжить удаление?',
'LBL_DELETE_EMPLOYEE_CONFIRM'       => 'Вы действительно хотите удалить данного сотрудника?',
  'LBL_ONLY_ACTIVE' => 'Активные сотрудники',
'LBL_SELECT' => 'Обзор' /*for 508 compliance fix*/,
'LBL_FF_CLEAR' => 'Очистить' /*for 508 compliance fix*/,
  'LBL_AUTHENTICATE_ID' => 'ID аутентификации',
  'LBL_EXT_AUTHENTICATE' => 'Внешняя аутентификация',
  'LBL_GROUP_USER' => 'Групповой пользователь',
  'LBL_LIST_ACCEPT_STATUS' => 'Статус',
  'LBL_MODIFIED_BY' =>'Изменено',
    'LBL_MODIFIED_BY_ID' =>'Изменено(ID)',
  'LBL_CREATED_BY_NAME' => 'Создано', //bug48978
  'LBL_PORTAL_ONLY_USER' => 'Portal API User', ///
  'LBL_PSW_MODIFIED' => 'Последнее изменение пароля',
  'LBL_SHOW_ON_EMPLOYEES' => 'Display Employee Record', ///
  'LBL_USER_HASH' => 'Пароль',
  'LBL_SYSTEM_GENERATED_PASSWORD' =>'Автоматически сгенерированный пароль',
  'LBL_DESCRIPTION'=> 'Описание',
  'LBL_FAX_PHONE'=> 'Факс',
  'LBL_FAX'=> 'Факс',
  'LBL_STATUS'=> 'Статус',
  'LBL_ADDRESS_CITY'=> 'Адрес - город',
  'LBL_ADDRESS_COUNTRY'=> 'Адрес - страна',
  'LBL_ADDRESS_INFORMATION'=> 'Адресные данные',
  'LBL_ADDRESS_POSTALCODE'=> 'Индекс',
  'LBL_ADDRESS_STATE'=> 'Адрес - область',
  'LBL_ADDRESS_STREET'=> 'Адрес - улица',
  'LBL_ADDRESS'=> 'Адрес',
  
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DELETED' => 'Удалено',

);


?>
