<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_MODULE_NAME' => 'Задачи' ,
'LBL_TASK' => 'Задачи: ' ,
'LBL_MODULE_TITLE' => 'Задачи - ГЛАВНАЯ' ,
'LBL_SEARCH_FORM_TITLE' => 'Поиск задачи' ,
'LBL_LIST_FORM_TITLE' => 'Список задач' ,
'LBL_NEW_FORM_TITLE' => 'Создать задачу' ,
'LBL_NEW_FORM_SUBJECT' => 'Тема:' ,
'LBL_NEW_FORM_DUE_DATE' => 'Дата выполнения:' ,
'LBL_NEW_FORM_DUE_TIME' => 'Время выполнения:' ,
'LBL_NEW_TIME_FORMAT' => '(24:00)' ,
'LBL_LIST_CLOSE' => 'Закрыть' ,
'LBL_LIST_SUBJECT' => 'Тема' ,
'LBL_LIST_CONTACT' => 'Контакт' ,
'LBL_LIST_PRIORITY' => 'Приоритет' ,
'LBL_LIST_RELATED_TO' => 'Относится к' ,
'LBL_LIST_DUE_DATE' => 'Дата выполнения' ,
'LBL_LIST_DUE_TIME' => 'Время выполнения' ,
'LBL_SUBJECT' => 'Тема:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_DUE_DATE' => 'Дата выполнения:' ,
'LBL_DUE_TIME' => 'Время выполнения:' ,
'LBL_PRIORITY' => 'Приоритет:' ,
'LBL_COLON' => ':' ,
'LBL_DUE_DATE_AND_TIME' => 'Дата и время выполнения:' ,
'LBL_START_DATE_AND_TIME' => 'Дата и время начала:' ,
'LBL_START_DATE' => 'Дата начала:' ,
'LBL_LIST_START_DATE' => 'Дата начала',
'LBL_START_TIME' => 'Время начала:' ,
'LBL_LIST_START_TIME' => 'Время начала',
'DATE_FORMAT' => '(гггг-мм-дд)' ,
'LBL_NONE' => 'Нет' ,
'LBL_CONTACT' => 'Контакт:' ,
'LBL_EMAIL_ADDRESS' => 'Адреса E-mail:',
'LBL_PHONE' => 'Тел.:' ,
'LBL_EMAIL' => 'E-mail:' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_NAME' => 'Название:' ,
'LBL_CONTACT_NAME' => 'Контактное лицо' ,
'LBL_LIST_COMPLETE' => 'Завершено:' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_DATE_DUE_FLAG' => 'Нет даты выполнения' ,
'LBL_DATE_START_FLAG' => 'Нет даты начала' ,
'ERR_DELETE_RECORD' => ' Необходимо указать запись для удаления контакта' ,
'ERR_INVALID_HOUR' => 'Пожалуйста, введите значение часа между 0 и 24' ,
'LBL_DEFAULT_PRIORITY' => 'Средний' ,
'LBL_LIST_MY_TASKS' => 'Мои открытые задачи' ,
'LNK_NEW_TASK' => 'Создать задачу' ,
'LNK_TASK_LIST' => 'Задачи' ,
'LNK_IMPORT_TASKS' => 'Импорт задач',
'LBL_CONTACT_FIRST_NAME'=> 'Имя контакта' ,
'LBL_CONTACT_LAST_NAME'=> 'Фамилия контакта',
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_ASSIGNED_TO_NAME'=> 'Ответственный(ая):',
'LBL_LIST_DATE_MODIFIED' => 'Дата изменения',
'LBL_CONTACT_ID' => 'ID контакта:',
'LBL_PARENT_ID' => 'ID родителя:',
'LBL_CONTACT_PHONE' => 'Телефон контакта:',
'LBL_PARENT_NAME' => 'Тип родителя:',
'LBL_ACTIVITIES_REPORTS' => 'Отчёт о мероприятиях',
'LBL_TASK_INFORMATION' => 'Основная информация',
'LBL_HISTORY_SUBPANEL_TITLE' => 'Заметки',
'LBL_EDITLAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
'LBL_TASK_INFORMATION' => 'Основная информация',
//For export labels
'LBL_DATE_DUE' => 'Дата выполнения',
'LBL_EXPORT_ASSIGNED_USER_NAME' => 'Ответственный(ая)',
'LBL_EXPORT_ASSIGNED_USER_ID' => 'Ответственный(ая)-ID',
'LBL_EXPORT_MODIFIED_USER_ID' => 'Изменено(ID)',
'LBL_EXPORT_CREATED_BY' => 'Создано (ID)',
'LBL_EXPORT_PARENT_TYPE' => 'Относится к модулю',
'LBL_EXPORT_PARENT_ID' => 'Относится к (ID)',
'LBL_RELATED_TO' => 'Относится к:',
);


?>
