<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_REPLY_ADDR' => 'Ответить (адрес): ',
'LBL_REPLY_NAME' => 'Ответить (имя): ',

'LBL_MODULE_NAME' => 'Рассылки E-mail' ,
'LBL_MODULE_TITLE' => 'Рассылки E-mail: ГЛАВНАЯ' ,
'LBL_LIST_FORM_TITLE' => 'Рассылки E-mail' ,
'LBL_NAME' => 'Название: ' ,
'LBL_LIST_NAME' => 'Название' ,
'LBL_LIST_FROM_ADDR' => 'От' ,
'LBL_LIST_DATE_START' => 'Дата начала' ,
'LBL_LIST_TEMPLATE_NAME' => 'Шаблон E-mail' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_STATUS'=> 'Статус' ,
'LBL_STATUS_TEXT'=> 'Статус:' ,
'LBL_TEMPLATE_NAME'=> 'Название шаблона',
'LBL_DATE_ENTERED' => 'Дата ввода' ,
'LBL_DATE_MODIFIED' => 'Дата изменения' ,
'LBL_MODIFIED' => 'Исправлено: ' ,
'LBL_CREATED' => 'Создано: ' ,
'LBL_MESSAGE_FOR'=> 'Отправить это сообщение:' ,
'LBL_MESSAGE_FOR_ID'=> 'Сообщение для' ,

'LBL_FROM_NAME' => 'От - имя: ' ,
'LBL_FROM_ADDR' => 'От - адрес E-mail: ' ,
'LBL_DATE_START' => 'Дата начала' ,
'LBL_TIME_START' => 'Время начала' ,
'LBL_START_DATE_TIME' => 'Дата и время начала: ' ,
'LBL_TEMPLATE' => 'Шаблон E-mail: ' ,

'LBL_MODIFIED_BY' => 'Кем исправлено: ' ,
'LBL_CREATED_BY' => 'Кем создано: ' ,
'LBL_DATE_CREATED' => 'Дата создания: ' ,
'LBL_DATE_LAST_MODIFIED' => 'Дата изменения: ' ,

'LNK_NEW_CAMPAIGN' => 'Создать маркет. кампанию' ,
'LNK_CAMPAIGN_LIST' => 'Маркетинговые кампании' ,
'LNK_NEW_PROSPECT_LIST' => 'Создать список адресатов' ,
'LNK_PROSPECT_LIST_LIST' => 'Списки адресатов' ,
'LNK_NEW_PROSPECT' => 'Создать адресата' ,
'LNK_PROSPECT_LIST' => 'Адресаты' ,
'LBL_DEFAULT_SUBPANEL_TITLE'=> 'Рассылки E-mail' ,
'LBL_CREATE_EMAIL_TEMPLATE'=> 'Создать' ,
'LBL_EDIT_EMAIL_TEMPLATE'=> 'Править' ,
'LBL_FROM_MAILBOX'=> 'Почтовый ящик для возвращаемых писем' ,
'LBL_FROM_MAILBOX_NAME'=> 'Почтовый ящик для возвращаемых писем:' ,
'LBL_PROSPECT_LIST_SUBPANEL_TITLE'=> 'Адресаты' ,
'LBL_ALL_PROSPECT_LISTS'=> 'ВСЕМ спискам адресатов маркетинговой кампании' ,
'LBL_RELATED_PROSPECT_LISTS'=> 'ВЫБРАННЫМ спискам адресатов маркетинговой кампании.' ,
'LBL_PROSPECT_LIST_NAME'=> 'Имя:' ,
'LBL_LIST_PROSPECT_LIST_NAME'=> 'Список адресатов' ,
'LBL_MODULE_SEND_TEST'=> 'Рассылка: проверка отправки' ,
'LBL_MODULE_SEND_EMAILS'=> 'Рассылка: отправить E-mail' ,
'LBL_SCHEDULE_MESSAGE_TEST'=> 'Пожалуйста, выберите рассылки, которые вы хотите протестировать' ,
'LBL_SCHEDULE_MESSAGE_EMAILS'=> 'Пожалуйста, выберите рассылки, которые вы хотите запланировать к отправке в определённое время:' ,
'LBL_SCHEDULE_BUTTON_TITLE'=> 'Отправить' ,
'LBL_SCHEDULE_BUTTON_LABEL'=> 'Отправить' ,
'LBL_SCHEDULE_BUTTON_KEY'=> 'T'  ,



);
?>
