<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$mod_strings = array(
    'LBL_ASSIGNED_TO_ID' => 'Assigned to (ID)',
    'LBL_ASSIGNED_TO_NAME' => 'Assigned to',
    'LBL_ASSIGNED_TO' => 'Assigned to',
    'LBL_LIST_ASSIGNED_TO_NAME' => 'Assigned to',
    'LBL_LIST_ASSIGNED_USER' => 'Assigned to',
    'LBL_CREATED' => 'Created By',
    'LBL_CREATED_USER' => 'Created By',
    'LBL_CREATED_ID' => 'Created By (ID)',
    'LBL_MODIFIED' => 'Modified By',
    'LBL_MODIFIED_NAME' => 'Modified By',
    'LBL_MODIFIED_USER' => 'Modified By',
    'LBL_MODIFIED_ID' => 'Modified By (ID)',
    'LBL_SECURITYGROUPS' => 'Security Groups',
    'LBL_SECURITYGROUPS_SUBPANEL_TITLE' => 'Security Groups',
    'LBL_ID' => 'ID',
    'LBL_DATE_ENTERED' => 'Date Created',
    'LBL_DATE_MODIFIED' => 'Date Modified',
    'LBL_DESCRIPTION' => 'Description',
    'LBL_DELETED' => 'Deleted',
    'LBL_NAME' => 'Name',
    'LBL_LIST_NAME' => 'Name',
    'LBL_EDIT_BUTTON' => 'Edit',
    'LBL_REMOVE' => 'Remove',
    'LBL_LIST_FORM_TITLE' => 'SEPE XML Files List',
    'LBL_MODULE_NAME' => 'SEPE XML Generator',
    'LBL_MODULE_TITLE' => 'SEPE XML Generator',
    'LBL_HOMEPAGE_TITLE' => 'My SEPE XML Files',
    'LNK_NEW_RECORD' => 'Create a SEPE XML File',
    'LNK_LIST' => 'View SEPE XML Files',
    'LNK_IMPORT_STIC_SEPE_FILES' => 'Import SEPE XML Files',
    'LBL_SEARCH_FORM_TITLE' => 'Search SEPE XML Files',
    'LBL_HISTORY_SUBPANEL_TITLE' => 'View History',
    'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Activities',
    'LBL_STIC_SEPE_FILES_SUBPANEL_TITLE' => 'SEPE XML Generator',
    'LBL_NEW_FORM_TITLE' => 'New SEPE XML File',
    'LBL_STATUS' => 'Status',
    'LBL_TYPE' => 'File type',
    'LBL_REPORTED_MONTH' => 'Month/year reported',
    'LBL_LOG' => 'Error log',
    'LBL_AGREEMENT' => 'Agreement code',
    'LBL_GENERATE_XML_FILE' => 'Generate XML file',
    'LBL_SEPE_LOG_TITLE' => 'This file was last generated by: ',
    'LBL_SEPE_GENERATED_WITHOUT_ERRORS' => 'XML file successfully generated',
    'LBL_SEPE_XML_HAS_ERRORS' => 'The XML file has not been generated because there are errors that should be corrected.',
    'LBL_ERROR_DATE_FUTURE' => "The field 'Reported month' must be equal or prior than today's date.",
    'LBL_ERROR_SEPE_CODIGO_AGENCIA' => 'The value of SEPE_CODIGO_AGENCIA setting is incorrect. It must be a 10 digits integer.',
    'LBL_ERROR_SEPE_AGREEMENT' => 'For ACCD or ACCI files an Agreement code is required.',
    'LBL_ERROR_PATTERN_SEPE_AGREEMENT' => 'The Agreement code is wrong. It should be a 10 characters string containing numbers and letters.',
    'LBL_SEPE_ERRORS_TITLE' => 'File has not been generated due to the errrors below:',
    'LBL_ERROR_SEPE_REQUIRED' => 'The following field (from module) is required: ',
    'LBL_ERROR_SEPE_PATTERN' => 'The following field (from module) does not meet the pattern: ',
    'LBL_ERROR_SEPE_NOT_IN_LIST' => 'The value of the following field (from module) is not in the SEPE lists: ',
    'LBL_ERROR_SEPE_LENGTH_EXCEEDED' => 'The value of the following field (from module) exceeds the allowed length: ',
    'LBL_ERRORS_SEPE_CHECK' => 'Check',
    'LBL_SEPE_WARNINGS_TITLE' => 'Warnings (records that may be included in the file after some changes)',
    'LBL_WARNING_JOB_OFFER_NOT_SEPE_ACTIVATED' => "A contact enroled to SEPE has a related offer that it is not SEPE activated (or activation date is later than contact's enrolment date): ",
    'LBL_WARNING_JOB_OFFER_COVERED_NOT_ACTIVATED' => 'An offer with Covered Date (SEPE) has no Activation Date (SEPE) or Activation Date is later: ',
    'LBL_WARNING_CONTACT_NOT_SEPE_ACTIVATED' => "A contact related to a SEPE job offer is not enroled to SEPE (or SEPE contact's enrolment date is later than some job application dates): ",
    'LBL_WARNING_CONTACT_AND_JOB_OFFER_NOT_SEPE_ACTIVATED' => "A job application has at least one date that is prior to the SEPE contact's enrolment date or to the offer's activation date: ",
    'LBL_WARNING_ACCD_ACTION_SEPE_NOT_ACTIVATED' => "A contact not enroled to SEPE is related to SEPE Actions (or contact's enrolment date is later than some action dates): ",
    'LBL_WARNING_ACCI_ACTION_SEPE_NOT_ACTIVATED' => "A contact not enroled to SEPE is related to SEPE Incidents (or contact's enrolment date is later than some incident dates): ",
    'LBL_DEFAULT_PANEL' => 'Overview',
    'LBL_PANEL_RECORD_DETAILS' => 'Record details',
    'LBL_REPORTED_MONTH_HELP' => "Select any day in the month or in the year for which you need to generate the XML file. For example, if you want to generate September's file, you should select any date from September 1st to 30th. If you want to generate 2019's file, you should select any date from January 1st to December 31st 2019.",
    'LBL_AGREEMENT_HELP' => "The Agreement code field will be enabled and required when generating ACCD or ACCI files. Agreement codes can be managed by editing the 'stic_sepe_agreement_list' in the Dropdown list editor.",
    'LBL_AGREEMENT_EMPTY_ERROR' => 'When the Type field is set to any ACCD or ACCI file, the Agreement code field is required.',
    'LBL_AGREEMENT_ERROR' => 'When the Type field is not set to any ACCD or ACCI file, the Agreement code field should be empty.',
);
