<?php 

// ADDITIONAL LANGUAGES
$config['languages'] = array(
  'af_ZA' => 'Afrikaans (South Africa)',
  'ar_EG' => 'Arabic (Egypt)',
  'bg_BG' => 'Bulgarian (Bulgaria)',
  'ca_ES' => 'Catalan (Spain)',
  'cs_CZ' => 'Czech (Czech Republic',
  'da_DK' => 'Danish (Denmark)',
  'de_CH' => 'German (Germany)',
  'de_DE' => 'German (Switzerland)',
  'el_GR' => 'Greek (Greece)',
  'es_ES' => 'Spanish (Spain)',
  'es_MX' => 'Spanish (Mexico)',
  'et_EE' => 'Estonian (Estonia)',
  'eu_ES' => 'Basque (Spain)',
  'fa_IR' => 'Persian (Iran)',
  'fi_FI' => 'Finnish (Finland)',
  'fr_CA' => 'French (Canada)',
  'fr_FR' => 'French (France)',
  'he_IL' => 'Hebrew (Israel)',
  'hi_IN' => 'Hindi (India)',
  'hr_HR' => 'Croatian (Croatia)',
  'hu_HU' => 'Hungarian (Hungary)',
  'hy_AM' => 'Armenian (Armenia)',
  'id_ID' => 'Indonesian (Indonesia)',
  'it_IT' => 'Italian (Italy)',
  'ja_JP' => 'Japanese (Japan)',
  'ko_KR' => 'Korean (Korea)',
  'lt_LT' => 'Lithuanian (Lithuania)',
  'lv_LV' => 'Latvian (Latvia)',
  'mk_MK' => 'Macedonian (Macedonia)',
  'nb_NO' => 'Norwegian Bokmål (Norway)',
  'nl_NL' => 'Dutch (Netherlands)',
  'pl_PL' => 'Polish (Poland)',
  'pt_BR' => 'Portuguese (Brazil)',
  'pt_PT' => 'Portuguese (Portugal)',
  'ro_RO' => 'Romanian (Romania)',
  'ru_RU' => 'Russian (Russia)',
  'si_LK' => 'Sinhala (Sri Lanka)',
  'sk_SK' => 'Slovak (Slovakia)',
  'sl_SI' => 'Slovenian (Slovenia)',
  'sr_SP' => 'Serbian (Cyrillic)',
  'sv_SE' => 'Swedish (Sweden)',
  'th_TH' => 'Thai (Thailand)',
  'tr_TR' => 'Turkish (Turkey)',
  'uk_UA' => 'Ukrainian (Ukraine)',
  'ur_PK' => 'Urdu (Pakistan)',
  'vi_VN' => 'Vietnamese (Viet Nam)',
  'zh_CN' => 'Chinese (China)',
  'zh_TW' => 'Chinese (Taiwan)',
);

?>
