<?php
/**
 * Advanced OpenWorkflow, Automating SugarCRM.
 * @package Advanced OpenWorkflow for SugarCRM
 * @copyright SalesAgility Ltd http://www.salesagility.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author SalesAgility <info@salesagility.com>
 */
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------------
  * Description : Defines the Russian language pack for the base application.
  *
  ***********************************************************************likhobory*/

$mod_strings = array (
  'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая)-ID',
  'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
  'LBL_ID' => 'ID',
  'LBL_DATE_ENTERED' => 'Дата создания',
  'LBL_DATE_MODIFIED' => 'Дата изменения',
  'LBL_MODIFIED' => 'Изменено',
  'LBL_MODIFIED_ID' => 'Изменено(ID)',
  'LBL_MODIFIED_NAME' => 'Изменено (Имя)',
  'LBL_CREATED' => 'Создано',
  'LBL_CREATED_ID' => 'Создано(ID)',
  'LBL_DESCRIPTION' => 'Описание',
  'LBL_DELETED' => 'Удалён',
  'LBL_NAME' => 'Название',
  'LBL_CREATED_USER' => 'Создано',
  'LBL_MODIFIED_USER' => 'Изменено',
  'LBL_LIST_NAME' => 'Название',
  'LBL_LIST_FORM_TITLE' => 'Контроль процессов',
  'LBL_MODULE_NAME' => 'Контроль процессов',
  'LBL_MODULE_TITLE' => 'Контроль процессов',
  'LBL_HOMEPAGE_TITLE' => 'Контроль моих процессов',
  'LNK_NEW_RECORD' => 'Создать Контроль процессов',
  'LNK_LIST' => 'Контроль процессов',
  'LNK_IMPORT_FF_AOW_PROCESSED' => 'Import Process Audit',
  'LBL_SEARCH_FORM_TITLE' => 'Search Process Audit',
  'LBL_HISTORY_SUBPANEL_TITLE' => 'История',
  'LBL_ACTIVITIES_SUBPANEL_TITLE' => 'Мероприятия',
  'LBL_FF_AOW_PROCESSED_SUBPANEL_TITLE' => 'Контроль процессов',
  'LBL_NEW_FORM_TITLE' => 'Новый Контроль процессов',
  'LBL_AOW__WORKFLOW_ID' => 'WorkFlow Id',
  'LBL_AOW__WORKFLOW' => 'Процессы',
  'LBL_AOW_ACTION_ID' => 'Action Id',
  'LBL_AOW_ACTION' => 'Действие',
  'LBL_MODULE' => 'Модуль',
  'LBL_BEAN' => 'Запись',
  'LBL_STATUS' => 'Статус',
  'LNK_IMPORT_AOW_AOW_PROCESSED' => 'Import Process Audit',
  'LBL_AOW_AOW_PROCESSED_SUBPANEL_TITLE' => 'Контроль процессов',
  'LNK_IMPORT_AOW_PROCESSED' => 'Import Process Audit',
  'LBL_AOW_PROCESSED_SUBPANEL_TITLE' => 'Контроль процессов',
  'LBL_AOW_WORKFLOW' => 'Процессы',
  'LNK_NEW_WORKFLOW' => 'Создать процесс',
  'LNK_WORKFLOW_LIST' => 'Процессы',
);