<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_CAPTCHA_HELP_TEXT'=> 'CAPTCHA (от англ. "Completely Automated Public Turing test to tell Computers and Humans Apart" - полностью автоматизированный публичный тест Тьюринга для различения компьютеров и людей.) Это тест с запросом к отправителю, с целью убедиться, что ответ не был сгенерирован компьютером автоматически. Для работы этой опции необходимо получить открытый и закрытый ключи с сайта reCAPTCHA: http://recaptcha.net/.',
'CAPTCHA'=> 'CAPTCHA',
'CAPTCHA_PRIVATE_KEY'=> 'Закрытый ключ',
'CAPTCHA_PUBLIC_KEY'=> 'Открытый ключ',
'ENABLE_CAPTCHA'=> 'Включить reCAPTCHA',
'ERR_PUBLIC_CAPTCHA_KEY'=> 'Неверный ключ',
'BTN_REBUILD_CONFIG' => 'Перестроить' ,
'EXPORT_DELIMITER' => 'Символ разделителя',
'ADMIN_EXPORT_ONLY'=> 'Разрешить экспорт только администратору',
'EXPORT'=> 'Параметры экспорта',
'EXPORT_CHARSET' => 'Стандартная кодировка при импорте и экспорте данных',
'DISABLE_EXPORT'=> 'Отключить экспорт',
'DESC_DROPDOWN_EDITOR' => 'Создание, удаление или изменение комбобоксов' ,
'DESC_EDIT_CUSTOM_FIELDS' => 'Правка пользовательских полей, созданных для размещения полей' ,
'DESC_FILES_INSTALLED' => 'Следующие обновления установлены:' ,
'DESC_FILES_QUEUED' => 'Следующие Обновления локально поставлены в очередь для установки:' ,
'DESC_IFRAME' => 'Добавление закладок, которые могут показывать любой сайт' ,
'DESC_MODULES_INSTALLED' => 'Следующие модули установлены:' ,

'DOWNLOAD_QUESTION'      => 'Вы уверены, что хотите загрузить выбранные модули?',
'ENABLED_OFFLINE_CLIENTS' => 'Offline Clients are enabled.',

'SEARCHING_UPDATES' => 'Поиск обновлений...',
'DOWNLOADING' => 'Загрузка...',
'DL_PACKAGES_DOWNLOADING' => 'Загрузка',
'DL_PACKAGES_OF' => '',
'DL_PACKAGES_PACKAGES' => 'пакета(ов)',
'LOADING_CATEGORIES' => 'Загрузка категорий...',
'SEARCHING_PACKAGES' => 'Поиск пакетов...',
'AUTHENTICATING' => 'Авторизация...',

'LBL_MINUTES'=> 'Минут',
'LBL_HOURS'=> 'Часов',
'LBL_DAYS'=> 'Дней',
'LBL_WEEKS'=> 'Недель',
'LBL_MONTHS'=> 'Месяцев',

'LBL_PUBLIC_KEY'=> 'Открытый ключ',
'LBL_PRIVATE_KEY'=> 'Закрытый ключ',

'ERR_INVALID_LOCALE_NAME_FORMAT_UPGRADE' => 'Указанный до обновления формат имени более не поддерживается и устанавливается в стандартное значение. При необходимости укажите новый формат и нажмите на кнопку <b>Сохранить</b>.',

'ERR_CANNOT_CREATE_RESTORE_FILE' => 'Ошибка: Невозможно создать файл восстановления',
'ERR_CREDENTIALS_MISSING'   => 'Указанная учётная запись отсутствует на сервере',
'ERR_DELETE_RECORD' => 'Перед удалением должен быть указан номер записи.' ,
'ERR_ENABLE_CURL'   => 'Пожалуйста, убедитесь, что у вас включён curl',
'ERR_EXPAND_DATABASE_COMPLETED' => 'Ошибка: Наличие файла restoreExpand.sql свидетельствует о том, что вы уже изменили размеры полей базы данных.',
'ERR_INCORRECT_REGEX' => 'Регулярное выражение в Regex-поле имеет неверный синтаксис. Пожалуйста, проверьте выражение и исправьте синтаксис',
'ERR_EMPTY_REGEX_DESCRIPTION' => 'Описание необходимого регулярного выражения. Это описание будет отображаться для пользователей, устанавливающих новые пароли.',
'ERR_NO_COLUMNS_TO_EXPAND' => 'Ошибка: База данных не содержит varchar, char или текстовых полей.',
'ERR_NOT_FOR_MSSQL'=> 'Эта функция не работает в данной конфигурации.',
'ERR_NOT_FOR_MYSQL'=> 'Эта функция не работает в данной конфигурации.',
'ERR_NOT_FOR_ORACLE'=> 'Эта функция не работает в данной конфигурации.' ,
'ERR_NOT_IMPLEMENTED'=>'Эта функция не работает в данной конфигурации.',
'ERR_NUM_OFFLINE_CLIENTS_MET' => 'You have already met the number of Offline Clients for your license key.  You must either disable an existing Offline Client or update your license.',
'ERR_OC_USER_ALREADY_EXISTS' => 'Выбранный вами пользователь уже существует в системе.',
'ERR_SUGAR_DEPOT_DOWN'    => 'Невозможно установить соединение с Suite Exchange для выбора и загрузки модулей.',
'ERR_SMTP_SERVER_NOT_SET'=> 'Внимание: SMTP-сервер для исходящей почты не настроен. Настройте его в параметрах почты для того, чтобы иметь возможность отослать пароли пользователям.',
'ERR_UW_ACCEPT_LICENSE'                  => 'Вы должны принять лицензионное соглашение перед тем как продолжить',
'ERR_UW_CONFIG_FAILED'                      => "Ошибка записи в файл config.php",
'ERR_UW_COPY_FAILED'                        => 'Невозможно скопировать файл ',
'ERR_UW_INVALID_VIEW'                       => 'Указан неверный объект.',
'ERR_UW_MUST_SELECT_OVERWRITE_OPTION' => 'Please select an overwrite option',
'ERR_UW_NO_DEPENDENCY'      => "Следующие зависимости не были найдены в системе:",
'ERR_UW_NO_FILES'                           => "Не указаны файлы для копирования.",
'ERR_UW_NO_INSTALL_FILE'                    => "Не указан инсталляционный файл.",
'ERR_UW_NO_LANG_DESC'                       => "Описание языкового файла отсутствует.",
'ERR_UW_NO_LANG'                            => "Не указан языковой файл.",
'ERR_UW_NO_MANIFEST'                        => "В архиве отсутствует файл manifest.php. Продолжение установки невозможно.",
'ERR_UW_NO_MODE'                            => "Не указан режим операции.",
'ERR_UW_NO_TEMP_DIR'                        => "Не указана временная директория для копирования файлов.",
'ERR_UW_NO_UPDATE_RECORD'                   => 'Невозможно определить инсталляционную запись для',
'ERR_UW_NO_UPLOAD_FILE'                     => "Пожалуйста, нажмите на кнопку <b>Обзор</b> для выбора загружаемого файла.<br>\n",
'ERR_UW_NO_VIEW'                            => "Страница не определена. Пожалуйста, перейдите в панель администратора для перехода на эту страницу.",
'ERR_UW_NOT_ACCEPTIBLE_TYPE'                => " На этой странице вы можете загружать только модули, темы и языковые файлы.",
'ERR_UW_NOT_RECOGNIZED'                     => 'не распознан',
'ERR_UW_NOT_VALID_UPLOAD'                   => 'Загружен неверный файл.',
'ERR_UW_ONLY_PATCHES'                       => " На этой странице вы можете загружать только обновления.",
'ERR_UW_REMOVE_FAILED'                      => 'Невозможно удалить файл',
'ERR_UW_REMOVE_PACKAGE'                     => "Невозможно удалить пакет ",
'ERR_UW_RUN_SQL'                            => "Ошибка запуска sql-скрипта: ",
'ERR_UW_UPDATE_CONFIG'                      => "Ошибка при добавлении в файл config.php информации о новой версии.",
'ERR_UW_UPLOAD_ERROR'                       => "Ошибка загрузки файла, пожалуйста, попробуйте  ещё раз!<br>\n",
'ERROR_FLAVOR_INCOMPATIBLE' => 'Загруженный файл не совместим с установленной версией Suite: ' ,
'ERROR_LICENSE_EXPIRED'=> 'Ошибка: ваша лицензия закончилась' ,
'ERROR_LICENSE_EXPIRED2' => " дней назад. Пожалуйста, перейдите <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a>  в панель администратора для ввода нового лицензионного ключа.  Если вы не введёте новый ключ в течение 7 дней с момента истечения лицензии, то вы не сможете войти в систему.",
'ERROR_MANIFEST_TYPE' => 'В Manifest-файле должен быть указан тип пакета.' ,
'ERROR_PACKAGE_TYPE' => 'В Manifest-файле указан неизвестный тип пакета' ,
'ERROR_VALIDATION_EXPIRED'=> 'Ошибка: Срок действия лицензионного ключа истёк' ,
'ERROR_VALIDATION_EXPIRED2' => " дней назад. Пожалуйста, перейдите <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a> в панель администратора для ввода нового лицензионного ключа.  Если вы не введёте новый ключ в течение 7 дней с момента истечения лицензии, то вы не сможете войти в систему.",
'ERROR_VERSION_INCOMPATIBLE' => 'Загружаемый файл не совместим с установленной версией Suite: ' ,

'FATAL_LICENSE_ALTERED' => 'Your license has been altered since the last time you were able to validate it. ',
'FATAL_LICENSE_EXPIRED'=> 'Ошибка: ваша лицензия истекла более 7 дней назад' ,
'FATAL_LICENSE_EXPIRED2'=> 'Пожалуйста, обновите вашу лицензионную информацию в панели администратора для восстановления полной работоспособности системы.' ,
'FATAL_LICENSE_REQUIRED' => 'Ошибка: Необходима информация о лицензионном ключе .',
'FATAL_VALIDATION_EXPIRED'=> 'Ошибка: срок действия вашего лицензионного ключа истёк более 7 дней назад' ,
'FATAL_VALIDATION_EXPIRED2'=> 'Пожалуйста, обновите вашу лицензионную информацию в панели администратора для восстановления полной работоспособности системы.' ,
'FATAL_VALIDATION_REQUIRED' => 'Ошибка: Необходима информация о лицензионном ключе.  ',
'HDR_LOGIN_PANEL'          => 'Пожалуйста, введите ваши учётные данные для suitecrm.com.',
'HEARTBEAT_MESSAGE'=> '<BR>',

'LBL_ACCEPT_TERMS' => 'Принимаю',
'LBL_ACCEPT'                                => 'Принимаю',
'LBL_ADMIN_SUGAR_SERVER'                => 'Имя администратора:',
'LBL_ADMIN_WIZARD_TITLE' => 'Мастер настройки системы',
'LBL_ADMIN_WIZARD' => 'Быстрая настройка параметров SuiteCRM',
'LBL_ADMINISTRATION_HOME_TITLE' => 'Система' ,
'LBL_ADMINISTRATION_HOME_DESC' => 'Конфигурирование системных настроек. Часть выполненных здесь стандартных настроек может перезаписана пользователями на странице настройки личных параметров пользователя.',
'LBL_ALLOW_USER_TABS' => 'Разрешить пользователям скрывать закладки модулей' ,
'LBL_ALREADY_RUNNING'                  => 'This server is running as an Offline Client.',
'LBL_APPLY_DST_FIX_DESC' => 'Этот обязательный шаг обновит временн<b>у</b>ю функциональность.' ,
'LBL_APPLY_DST_FIX' => 'Исправление дневного времени' ,
'LBL_AVAILABLE_MODULES'  => 'Модули, доступные для загрузки',
'LBL_AVAILABLE_UPDATES'=> 'Доступные обновления' ,
'LBL_BACKUP_BACK_HOME' => 'Возврат в панель администратора' ,
'LBL_BACKUP_CONFIRM' => 'Подтвердить настройки' ,
'LBL_BACKUP_CONFIRMED' => 'Настройки подтверждены.<br> Нажмите на кнопку "Создать резервную копию" для выполнения резервного копирования.<br>' ,
'LBL_BACKUP_DIRECTORY_ERROR' => 'Вы должны указать директорию для сохранения результатов резервного копирования.' ,
'LBL_BACKUP_DIRECTORY_EXISTS' => 'Директория для создания резервных копий не существует и не может быть создана.' ,
'LBL_BACKUP_DIRECTORY_NOT_WRITABLE' => 'Директория для создания резервных копий существует, но не доступна для записи.' ,
'LBL_BACKUP_DIRECTORY_WRITABLE' => '(должна быть доступна для записи)' ,
'LBL_BACKUP_DIRECTORY' => 'Директория:' ,
'LBL_BACKUP_FILE_AS_SUB' => 'Целевой файл уже существует в виде поддиректории в указанной директории' ,
'LBL_BACKUP_FILE_EXISTS' => 'Целевой файл уже существует в директории.' ,
'LBL_BACKUP_FILE_STORED' => 'Резервная копия успешно сохранена под именем' ,
'LBL_BACKUP_FILENAME_ERROR' => 'Должно быть указано имя файла резервной копии.' ,
'LBL_BACKUP_FILENAME' => 'Имя файла:' ,
'LBL_BACKUP_INSTRUCTIONS_1' => 'Назначение данной утилиты состоит в том, чтобы помочь вам создать резервную копию файлов CRM-системы.<br><br>Так же необходимо регулярно выполнять резервное копирование базы данных.<br>За более подробной информацией обратитесь к документации по вашей БД.<br>' ,
'LBL_BACKUP_INSTRUCTIONS_2' => 'Для создания резервной копии CRM-файлов в виде zip-архива введите следующую информацию:' ,
'LBL_BACKUP_RUN_BACKUP' => 'Создать резервную копию' ,
'LBL_BACKUP_TITLE' => 'Online-резервные копии ' ,
'LBL_BACKUP' => 'Восстановление системы из резервной копии' ,
'LBL_BACKUPS_TITLE' => 'Резервные копии' ,
'LBL_BACKUPS' => 'Выполнение резервного копирования файлов системы' ,
'LBL_BROWSE'                => 'Обзор',
'LBL_BUG_TITLE' => 'Отслеживание ошибок' ,
'LBL_BUG_DESC' => 'Перечень версий вашей продукции.',
'LBL_CANCEL_BUTTON_TITLE' => 'Отказаться',
'LBL_CAT_VIEW'            => 'Категории',
'LBL_CHANGE_NAME_MODULES'=> 'Редактирование меток закладок' ,
'LBL_CHECK_FOR_UPDATES'  => 'Проверить обновления',
'LBL_CHECK_NOW_LABEL' => 'Проверить сейчас' ,
'LBL_CHECK_NOW_TITLE' => 'Проверить сейчас' ,
'LBL_CHECK_DB_VARDEFS' => 'Проверка структуры БД на основе vardefs...',
'LBL_CONFIGURE_TABS_AND_SUBPANELS_DESC'=> 'Выбор закладок модулей и субпанелей, которые будут отображаться в системе',
'LBL_CLEAR_CHART_DATA_CACHE_DESC'=> 'Удаление кэшированных данных диаграмм' ,
'LBL_CLEAR_CHART_DATA_CACHE_TITLE'=> 'Очистка кэша диаграмм' ,
'LBL_CLEAR_CHART_DATA_CACHE_FINDING'=> 'Поиск файлов...',
'LBL_CLEAR_CHART_DATA_CACHE_DELETING1'=> 'Удаление данных диаграммы из кэша...',
'LBL_CLEAR_CHART_DATA_CACHE_DELETING2'=> 'удаление:',
'LBL_CLEAR_THEME_CACHE_DESC'=> 'Удаление файлов тем из кэша',
'LBL_CLEAR_THEME_CACHE_TITLE'=> 'Очистка кэша тем',
'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DELETING1'=> 'Удаление файлов поиска из кэша...',
'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DELETING2'=> 'Удаление файла',
'LBL_CLEAR_PDFFONTS_DESC'=> 'Removing PDF Font Cache File, will rebuild when needed.', ///
'LBL_CLEAR_PDFFONTS_DESC_SUCCESS'=> 'Success : PDF Font Cache File deleted', ///
'LBL_CLEAR_PDFFONTS_DESC_FAILURE'=> 'Error : Clearing PDF Font Cache File failed', ///
'LBL_CLEAR_PDF_FONT_CACHE_TITLE'=> 'Clear PDF Font File Cache', ///
'LBL_CLEAR_PDF_FONT_CACHE_DESC'=> 'Removes cached file used to store PDF fonts data', ///
'LBL_CONFIG_CHECK' => 'Проверка конфигурации' ,
'LBL_CONFIG_AJAX' => 'Настройка AJAX',
'LBL_CONFIG_FTS' => 'Configure Full Text Search Engine', ///
'LBL_CONFIG_AJAX_DESC' => 'При включённой AJAX-технологии скорость обновления страниц существенно повышается, поскольку не требуется обновление всей страницы. Если в каких-либо модулях возникли проблемы с отображением данных, вы можете отключить использование AJAX-технологии в проблемных модулях системы.',
'LBL_CONFIG_AJAX_HELP' => 'В левой колонке перечислены модули, отображаемые с использованием AJAX-технологии, в правой колонке перечислены модули, в которых использование данной технологии отключено. Воспользуйтесь мышью для перемещения названий модулей между колонками.',
'LBL_CONFIG_TABS'=> 'Отображение закладок модулей и субпанелей',
'LBL_CONFIG_TABS_DESC'=> 'Вы можете перемещать закладки или субпанели для настройки их видимости.',
'LBL_CONFIG_LANGS_DESC'=> 'Вы можете перемещать названия языковых пакетов в необходимую колонку для настройки их доступности.',
'LBL_CONFIG_TABS_ALLOW_USERS_HIDE_TABS_HELP'=> 'Установите данный параметр, если вы хотите, чтобы пользователи могли самостоятельно настраивать видимость модулей системы в настройках параметров пользователя.',
'LBL_CONFIGURATOR_DESC'=> 'Установка Config.php' ,
'LBL_CONFIGURATOR_TITLE'=> 'Конфигуратор' ,
'LBL_CONFIGURE_GROUP_TABS_DESC' => 'Создание и редактирование сгруппированных модулей',
'LBL_CONFIGURE_GROUP_TABS' => 'Настройка сгруппированных модулей',
'LBL_CONFIGURE_SETTINGS_TITLE' => 'Настройка конфигурации' ,
'LBL_CONFIGURE_SETTINGS' => 'Системные установки' ,
'LBL_CONFIGURE_TABS_AND_SUBPANELS' => 'Настройка отображения закладок и субпанелей',
'LBL_CONFIGURE_UPDATER'=> 'Настройка обновлений Suite' ,
'LBL_CONTRACT_TITLE'=> 'Договоры',
'LBL_CONTRACT_DESC'=> 'Define contract types for the Contracts module. When users create a contract, the Types drop-down menu displays the contract types for selection.', ///
'LBL_CONTRACT_TYPES'=> 'Manage Contract Types', ///
'LBL_COULD_NOT_CONNECT'=>'Error: Could not connect to the Suite Server.
Please check your Proxy Settings value in the <a href="index.php?module=Configurator&action=EditView">System Settings</a> admin panel.
Last attempted connection @ ',
'LBL_CREATE_RESOTRE_FILE' => 'Файл restoreExpand.sql был успешно создан. Вы можете использовать этот файл для восстановления прежних размеров полей.',
'LBL_CURRENCY' => 'Настройки валют, установка курса валют' ,
'LBL_CONNECTOR_SETTINGS' => 'Подключения',
'LBL_CONNECTOR_SETTINGS_DESC' => 'Управление параметрами подключения',
'LBL_SUGARPDF_SETTINGS' => 'PDF', ///
'LBL_SUGARPDF_SETTINGS_DESC' => 'Manage settings for generated PDF files', ///
'LBL_DENY' => 'Не принимаю',
'LBL_DIAG_CANCEL_BUTTON' => 'Отказаться' ,
'LBL_DIAG_EXECUTE_BUTTON' => 'Запустить диагностику' ,
'LBL_DIAGNOSTIC_ACCESS' => 'Вы должны иметь права администратора для запуска утилиты диагностики.' ,
'LBL_DIAGNOSTIC_BEANLIST_DESC' => 'This information tells us whether or not the beanFiles specified in the beanList actually exists. This can be an issue with an improperly defined module loaded extension.' ,
'LBL_DIAGNOSTIC_BEANLIST_GREEN' => 'Зелёный цвет означает, что файл существует.' ,
'LBL_DIAGNOSTIC_BEANLIST_ORANGE' => 'Оранжевый цвет означает, что индексированные файлы отсутствуют и поиск не может быть осуществлён.' ,
'LBL_DIAGNOSTIC_BEANLIST_RED' => 'Красный цвет означает, что файл не существует.' ,
'LBL_DIAGNOSTIC_BLBF'=> 'Наличие файлов BeanList/BeanFiles',
'LBL_DIAGNOSTIC_CALCMD5'=> '&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;Подсчёт контрольных сумм (MD5)',
'LBL_DIAGNOSTIC_CONFIGPHP'=> 'Содержимое файла config.php' ,
'LBL_DIAGNOSTIC_CUSTOMDIR'=> 'Содержимое папки Custom' ,
'LBL_DIAGNOSTIC_DELETED' => 'Файл был удалён',
'LBL_DIAGNOSTIC_DELETELINK' => 'Удаление результатов диагностики' ,
'LBL_DIAGNOSTIC_FILE' => 'Файл',
'LBL_DIAGNOSTIC_ZIP' => '.zip не существует.<BR><BR>',
'LBL_DIAGNOSTIC_DELETE_ERROR' => 'Невозможно получить имя файла или GUID для удаления файла.<BR><BR>',
'LBL_DIAGNOSTIC_DELETE_DIE' => 'Удаляемый вами файл не является файлом диагностики.',
'LBL_DIAGNOSTIC_DELETE_RETURN' => 'Возврат на страницу администрирования',
'LBL_DIAGNOSTIC_DESC'=> 'Диагностика системной конфигурации' ,
'LBL_DIAGNOSTIC_DONE' => 'Готово' ,
'LBL_DIAGNOSTIC_DOWNLOADLINK' => 'Сохранение результатов диагностики' ,
'LBL_DIAGNOSTIC_EXECUTING' => 'Выполнение диагностических операций...' ,
'LBL_DIAGNOSTIC_FILESMD5'=> '&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;Содержимое файла files.md5',
'LBL_DIAGNOSTIC_GETBEANFILES' => 'Проверка наличия bean-файлов...',
'LBL_DIAGNOSTIC_GETCONFPHP' => 'Получение содержимого файла config.php...',
'LBL_DIAGNOSTIC_GETCUSTDIR' => 'Получение содержимого папки custom...',
'LBL_DIAGNOSTIC_GETMD5INFO' => 'Подсчёт контрольных сумм (MD5)...',
'LBL_DIAGNOSTIC_GETMYSQLINFO' => 'основной информации о БД',
'LBL_DIAGNOSTIC_GETMYSQLTD' => 'дампа БД',
'LBL_DIAGNOSTIC_GETMYSQLTS' => 'схемы БД',
'LBL_DIAGNOSTIC_GETPHPINFO' => 'Получение данных phpinfo()',
'LBL_DIAGNOSTIC_GETSUGARLOG' => 'Получение содержимого файла журнала',
'LBL_DIAGNOSTIC_GETTING' => 'Получение...',
'LBL_DIAGNOSTIC_MD5'=> 'Анализ контрольных сумм:',
'LBL_DIAGNOSTIC_MYSQLDUMPS'=> 'Дамп таблиц с данными о конфигурации системы',
'LBL_DIAGNOSTIC_MYSQLINFO'=> 'Основная информация',
'LBL_DIAGNOSTIC_MYSQLSCHEMA'=> 'Структура таблиц',
'LBL_DIAGNOSTIC_NO_MYSQL' => 'БД MySQL не установлена. Функции MySQL недоступны.' ,
'LBL_DIAGNOSTIC_PHPINFO'=> 'phpinfo()',
'LBL_DIAGNOSTIC_SUGARLOG'=> 'Получение содержимого файла журнала',
'LBL_DIAGNOSTIC_TITLE'=> 'Диагностика' ,
'LBL_DIAGNOSTIC_VARDEFS'=> 'Структура таблиц на основе VARDEFS',
'LBL_DISABLED' => 'Скрыты',
'LBL_DISPLAY_TABS'=> 'Показывать закладки' ,
'LBL_DO_OVERWRITE_FILES'    => 'Не перезаписывать файлы',
'LBL_DOCUMENTATION_TITLE' => 'Online-документация' ,
'LBL_DOCUMENTATION' => 'Просмотр руководства пользователя и администратора' ,
'LBL_DONE'  => 'Готово',
'LBL_DROP_HERE' => '[Переместить сюда]',
'LBL_DROPDOWN_EDITOR' => 'Редактор комбобоксов' ,
'LBL_DST_APPLY_FIX' => 'Применение исправления дневного времени к существующим данным. Пожалуйста, создайте резервную копию всех Ваших данных.' ,
'LBL_DST_BEFORE_DESC' => 'Это исправление может изменить Ваши данные. Пожалуйста, создайте резервную копию всех Ваших данных перед запуском данного исправления.' ,
'LBL_DST_BEFORE' => 'Перед началом:' ,
'LBL_DST_CURRENT_SERVER_TIME_ZONE_LOCALE' => 'Часовой пояс сервера:' ,
'LBL_DST_CURRENT_SERVER_TIME_ZONE' => 'Определён часовой пояс сервера:' ,
'LBL_DST_CURRENT_SERVER_TIME' => 'Определено местное серверное время:' ,
'LBL_DST_END_DATE_TIME' => 'Дата/Время окончания' ,
'LBL_DST_FIX_CONFIRM_DESC' => 'Пожалуйста, просмотрите следующие данные  и подтвердите, что Ваша система сконфигурирована правильно.' ,
'LBL_DST_FIX_CONFIRM' => 'Подтверждение: ' ,
'LBL_DST_FIX_DONE_DESC' => 'Исправление дневного времени успешно применено.' ,
'LBL_DST_FIX_TARGET' => 'Цель:' ,
'LBL_DST_FIX_USER_TZ' => 'Этот шаг устанавливает часовой пояс для всех пользователей в наиболее предпочтительное значение.' ,
'LBL_DST_FIX_USER' => 'Пользовательская часовые пояса:<br>(ВЫБОРОЧНО)' ,
'LBL_DST_SET_USER_TZ' => 'Установка часового пояса пользователя' ,
'LBL_DST_START_DATE_TIME' => 'Дата/Время начала' ,
'LBL_DST_UPGRADE' => 'Обновление:' ,
'LBL_EDIT_CUSTOM_FIELDS' => 'Изменение пользовательских полей' ,
'LBL_EDIT_TABS'=> 'Править закладки' ,
'LBL_EMAIL_TITLE' => 'E-mail' ,
'LBL_EMAIL_DESC' => 'Управление входящими и исходящими письмами. Настройки должны быть сконфигурированы для того, чтобы обеспечить пользователям возможность рассылки писем и новостей компании.',
'LBL_EMAIL_ADDRESS_REQUIRED_FOR_FEATURE' => 'Для использования данной возможности каждому создаваемому пользователю необходимо в обязательном порядке указывать основной адрес E-mail.',
'LBL_ENABLE_MAILMERGE' => 'Включить слияние?' ,
'LBL_ENABLED' => 'Доступны',
'LBL_ERROR_VERSION_INFO'=> 'Ошибка при выборке информации о версии, пожалуйста, попробуйте  ещё раз позже.' ,
'LBL_EXCEEDING_OC_LICENSES' => "Error: The number of enabled Offline Clients currently exceeds the number specified in your license.  Please go to <a href='index.php?module=Administration&action=ListViewOfflineClient'>'\"Manage Offline Clients\"</a> in the Admin screen to disable Offline Clients or update your License.", ///
'LBL_EXECUTE'               => 'Выполнить',
'LBL_EXPAND_DATABASE_COLUMNS_DESC' => 'Увеличение размера char/varchar/text-полей в базе данных (только для MSSQL)',
'LBL_EXPAND_DATABASE_COLUMNS' => 'Увеличение размера поля',
'LBL_EXPAND_DATABASE_TEXT'=> 'Данная утилита позволяет увеличить размер выбранных полей базы данных и используется как временная мера для устранения ограничений, связанных с многобайтовыми символами в SQL Server. <br>Выберите один из вариантов: <br> Отобразить sql-скрипт на экране<br> Экспортировать sql-скрипт в файл<br> Выполнить sql-скрипт',
'LBL_EXPORT_CUSTOM_FIELDS_TITLE' => 'Экспорт структуры пользовательских полей' ,
'LBL_EXPORT_CUSTOM_FIELDS'=> 'Экспорт определений пользовательских полей в файл .sugar' ,
'LBL_EXPORT_DOWNLOAD_KEY' => 'Export Download Key' ,
'LBL_EXTERNAL_DEV_DESC'=> 'Перемещение структуры пользовательских полей из одной системы в другую' ,
'LBL_EXTERNAL_DEV_TITLE'=> 'Перемещение пользовательских полей' ,
'LBL_FORECAST_TITLE'=> 'Прогноз' ,
'LBL_FORECAST_DESC'=> 'Define time periods for the Forecasts module. These time periods display in the Time Periods drop-down menus in the Forecasts Module.', ///
'LBL_GLOBAL_SEARCH_SETTINGS' => 'Глобальный поиск',
'LBL_GLOBAL_SEARCH_SETTINGS_DESC' => 'Настройка глобального поиска',
'LBL_FTS_SETTINGS' => 'Full-Text Search', ///
'LBL_FTS_SETTINGS_DESC' => 'Configure the full-text search system.', ///
'LBL_GLOBAL_TEAM_DESC' => 'Глобальная видимость' ,
'LBL_GLOBAL_TEAM_SELECT' => 'A default global team was not found. Please select a team from this list.', ///
'LBL_GLOBAL_TEAM' => 'Rebuild access to global team.', ///
'LBL_GO' => 'Go' ,
'LBL_HELP_BOOKMARK' => 'Добавить страницу в закладки',
'LBL_HELP_EMAIL' => 'E-mail',
'LBL_HELP_LINK' => 'Ссылка на эту страницу',
'LBL_HELP_PRINT' => 'Печать',
'LBL_HIDE_TABS'=> 'Скрывать закладки' ,
'LBL_HIDDEN_PANELS'=> 'Скрытые субпанели',
'LBL_HIDDEN_TABS'=> 'Скрытые закладки модулей',
'LBL_HIDE_ADVANCED_OPTIONS'=> 'Дополнительные настройки видимости',
'LBL_HT_DONE' => '--- ГОТОВО ---' ,
'LBL_HT_NO_WRITE_2' => 'Если вы хотите защитить файлы от просмотра их в браузере, то создайте в корневой директории файл .htaccess со следующим содержимым:' ,
'LBL_HT_NO_WRITE' => 'Не доступен для записи файл: ' ,
'LBL_ICF_ADDING' => 'Добавление метаданных пользовательского поля - ' ,
'LBL_ICF_DROPPING' => 'удаление метаданных пользовательского поля ' ,
'LBL_ICF_IMPORT_S' => 'Импорт структуры' ,
'LBL_IFRAME'=> 'Мои сайты' ,
'LBL_IMPORT_CUSTOM_FIELDS_DESC'=> ' <br>Импорт файла .sugar, который был экспортирован на другом компьютере. В результате структура пользовательских полей на этом компьютере станет такой же, как и на другом компьютере. Рекомендуется экспортировать Вашу структуру пользовательских полей перед импортированием новой структуры. После импортирования структуры система автоматически запустит обновление пользовательских полей, сообщающее Вам об изменениях, сделанных в базе данных. Если Вы согласны с этими изменениями, то нажмите на ссылку в нижней части экрана. Если Вы хотите обратить процесс импортирования, то просто импортируйте структуру, которую Вы экспортировали перед импортированием. <br> Предупреждение: Этот процесс удалит как предыдущую структуру пользовательских полей, которая не определена в файле .sug, так и все данные, помещённые в эти пользовательские поля.' ,
'LBL_IMPORT_CUSTOM_FIELDS_STRUCT'=> ' Структура пользовательских полей (CustomFieldStruct.sugar)' ,
'LBL_IMPORT_CUSTOM_FIELDS_TITLE' => 'Импорт структуры пользовательских полей' ,
'LBL_IMPORT_CUSTOM_FIELDS'=> 'Импорт определений пользовательских полей из файла .sugar' ,
'LBL_IMPORT_VALIDATION_KEY' => 'Импортирование лицензионного ключа' ,
'LBL_IMPORT_WIZARD' => 'Мастер импорта',
'LBL_IMPORT_WIZARD_DESC' => 'Используйте мастер импорта для быстрого импортирования записей в систему',
'LBL_INBOUND_EMAIL_TITLE' => 'Входящие E-mail' ,
'LBL_LANGUAGES' => 'Управление доступом к языковым пакетам',
'LBL_LAYOUT' => 'Добавление, удаление, изменение полей, макетов полей и панелей в приложении' ,
'LBL_LICENSE_EXPIRE_DATE'   => 'Expiration Date', ///
'LBL_LICENSE_KEY'          => 'Download Key', ///
'LBL_LICENSE_NUM_LIC_OC'           => 'Number of Offline Client Licenses', ///
'LBL_LICENSE_NUM_PORTAL_USERS'         => 'Number of Concurrent Self-Service Portal Users',///
'LBL_LICENSE_USERS'      => 'Number of Users', ///
'LBL_LICENSE_VALIDATION_END'           => 'Validation Key Expiration', ///
'LBL_LICENSE_VALIDATION_KEY'           => 'Validation Key', ///
'LBL_LICENSE_VALIDATION'           => 'License Validation', ///
'LBL_LICENSE'               => 'Лицензия',
'LBL_LICENSE_UNAUTHORIZED_ACCESS' => 'Unauthorized access to license settings.', ///
'LBL_LIST_FIRST_CONNECT_DATE' => 'First Connect Date', ///
'LBL_LIST_LAST_CONNECT_DATE' => 'Last Connect Date', ///
'LBL_LIST_NUM_SYNCS' => 'Num. of Syncs', ///
'LBL_LIST_SET_STATUS' => 'Set Status', ///
'LBL_LIST_SYSTEM_KEY' => 'System Key', ///
'LBL_LIST_SYSTEM_NAME' => 'System Name', ///
'LBL_LIST_VIEW'          => 'Список',

'LBL_LDAP_TITLE'=> 'LDAP-аутентификация',
'LBL_LDAP_ENABLE'=> 'Включить LDAP-аутентификацию',
'LBL_LDAP_HELP_TXT'=> 'При включении LDAP-аутентификации управление паролями осуществляется только через LDAP. Настройки системы управления паролями Sugar не будут учитываться.',
'LBL_LDAP_SERVER_HOSTNAME'=> 'Сервер:',
'LBL_LDAP_SERVER_PORT'=> 'Порт:',
'LBL_LDAP_ADMIN_USER'=> 'Имя пользователя:',
'LBL_LDAP_ADMIN_USER_DESC'=> 'Поиск пользователя Sugar. В случае отсутствия параметра будет выполнен анонимный вход.',
'LBL_LDAP_ADMIN_PASSWORD'=> 'Пароль:',
'LBL_LDAP_AUTHENTICATION'=> 'Аутентификация:',
'LBL_LDAP_AUTHENTICATION_DESC'=> 'Аутентификация на сервере LDAP, используя данные пользователя',
'LBL_LDAP_AUTO_CREATE_USERS'=> 'Автоматическое создание пользователей:',
'LBL_LDAP_USER_DN'=> 'DN пользователя:',
'LBL_LDAP_GROUP_DN'=> 'DN группы:',
'LBL_LDAP_GROUP_DN_DESC'=> 'Пример: <em>ou=groups,dc=example,dc=com</em>',
'LBL_LDAP_USER_FILTER'=> 'Параметры:',
'LBL_LDAP_GROUP_MEMBERSHIP'=> 'Членство в группе:',
'LBL_LDAP_GROUP_MEMBERSHIP_DESC'=> 'Пользователь должен быть членом определённой группы',
'LBL_LDAP_GROUP_USER_ATTR'=> 'Атрибут пользователя:',
'LBL_LDAP_GROUP_USER_ATTR_DESC'=> 'Уникальный идентификатор пользователя, используемый для проверки принадлежности пользователя к определённой группе, например: <em>uid</em>',
'LBL_LDAP_GROUP_ATTR_DESC'=> 'Уникальный Атрибут группы, например: <em>memberUid</em>',
'LBL_LDAP_GROUP_ATTR'=> 'Атрибут группы:',
	'LBL_LDAP_GROUP_ATTR_REQ_DN' => 'Добавить DN пользователя:',
	'LBL_LDAP_GROUP_ATTR_REQ_DN_DESC' => 'Проверять DN пользователя вместе с атрибутом пользователя при проверке членства в группе',

'LBL_LDAP_USER_FILTER_DESC'=> 'Любые дополнительные параметры, применяемые в процессе аутентификации пользователей, например: <em>is_sugar_user=1 или (is_sugar_user=1)(is_sales=1)</em>',
'LBL_LDAP_LOGIN_ATTRIBUTE'=> 'Login-атрибут:',
'LBL_LDAP_BIND_ATTRIBUTE'=> 'Bind-атрибут:',
'LBL_LDAP_BIND_ATTRIBUTE_DESC'=> 'Аутентификация пользователя LDAP, например:[<b>AD:</b>&nbsp;userPrincipalName] [<b>openLDAP:</b>&nbsp;userPrincipalName] [<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;uid] ',
'LBL_LDAP_LOGIN_ATTRIBUTE_DESC'=> 'Поиск пользователя LDAP, например:[<b>AD:</b>&nbsp;userPrincipalName] [<b>openLDAP:</b>&nbsp;dn] [<b>Mac&nbsp;OS&nbsp;X:</b>&nbsp;dn] ',
'LBL_LDAP_SERVER_HOSTNAME_DESC'=> 'Пример: ldap.example.com или ldaps://ldap.example.com при включении SSL',
'LBL_LDAP_SERVER_PORT_DESC'=> 'Пример: 389 или 636 при включении SSL',
'LBL_LDAP_GROUP_NAME'=> 'Название группы:',
'LBL_LDAP_GROUP_NAME_DESC'=> 'Пример: <em>cn=sugarcrm</em>',
'LBL_LDAP_USER_DN_DESC'=> 'Пример: <em>ou=people,dc=example,dc=com</eM>',
'LBL_LDAP_AUTO_CREATE_USERS_DESC'=> 'Если аутентифицированный пользователь не существует в базе Suite, то он будет создан.',
'LBL_LDAP_ENC_KEY'=> 'Ключ шифрования:',

'LBL_LOADING'              => 'Идёт загрузка модулей...',
'LBL_LOCALE_DB_COLLATION_TITLE'             => 'Сравнение',
'LBL_LOCALE_DB_COLLATION'                   => 'Сравнение:',
'LBL_LOCALE_DEFAULT_CURRENCY_ISO4217'       => 'Код валюты (ISO 4217)',
'LBL_LOCALE_DEFAULT_CURRENCY_NAME'          => 'Валюта',
'LBL_LOCALE_DEFAULT_CURRENCY_SYMBOL'        => 'Символ валюты',
'LBL_LOCALE_DEFAULT_CURRENCY'               => 'Системная валюта',
'LBL_LOCALE_DEFAULT_DATE_FORMAT'            => 'Формат даты',
'LBL_LOCALE_DEFAULT_DECIMAL_SEP'            => 'Символ десятичного разделителя',
'LBL_LOCALE_DEFAULT_LANGUAGE'               => 'Языковой пакет',
'LBL_LOCALE_DEFAULT_NAME_FORMAT'            => 'Формат имени',
'LBL_LOCALE_DEFAULT_NUMBER_GROUPING_SEP'    => 'Символ разделителя разрядов',
'LBL_LOCALE_DEFAULT_SYSTEM_SETTINGS'        => 'Интерфейс пользователя',
'LBL_LOCALE_DEFAULT_TIME_FORMAT'            => 'Формат времени',
'LBL_LOCALE_EXAMPLE_NAME_FORMAT'            => 'Пример',
'LBL_LOCALE_NAME_FORMAT_DESC'               => '"s" Приветствие<br>"f" Имя<br>"l" Фамилия',
'LBL_LOCALE_TITLE'                          => 'Управление региональными настройками',
'LBL_LOCALE' => 'Установка региональных настроек',
'LBL_LOGIN_SUGAR_SERVER_DESC'          => '- The User Name of the person who will operate this offline client',
'LBL_LOGIN_SUGAR_SERVER'                => 'End User Name:',
'LBL_MAILBOX_DESC' => 'Настройка групповых учётных записей для входящей почты, а также управление персональными учётными записями пользователей' ,
'LBL_MANAGE_CONTRACTEMPLATES_TITLE'=> 'Contract Types',
'LBL_MANAGE_CURRENCIES' => 'Валюта' ,
'LBL_MANAGE_GROUPS_TITLE'   => 'Управление группами' ,
'LBL_MANAGE_GROUPS'         => 'Управление групповыми счетами' ,
'LBL_MANAGE_LANGUAGES' => 'Языковые пакеты',
'LBL_MANAGE_LAYOUT' => 'Размещение поля' ,
'LBL_MANAGE_LICENSE_TITLE'  => 'License Management', ///
'LBL_MANAGE_LICENSE'        => 'Manage license properties', ///
'LBL_MANAGE_LOCALE' => 'Региональные настройки',
'LBL_MANAGE_MAILBOX' => 'Входящие E-mail' ,
'LBL_MANAGE_OFFLINE_CLIENT'   => 'View Offline Clients', ///
'LBL_MANAGE_OPPORTUNITIES' => 'Сделки' ,
'LBL_MANAGE_PASSWORD_TITLE' => 'Управление паролями',
'LBL_MANAGE_PASSWORD'=> 'Настройка параметров пароля',
'LBL_MANAGE_RELEASES' => 'Версии' ,
'LBL_MANAGE_ROLES_TITLE' => 'Управление ролями' ,
'LBL_MANAGE_ROLES' => 'Управление ролевым членством и свойствами' ,
'LBL_MANAGE_TEAMS_TITLE' => 'Team Management', ///
'LBL_MANAGE_TEAMS' => 'Manage team membership and properties', ///
'LBL_MANAGE_TIMEPERIODS_TITLE' => 'Периоды времени',
'LBL_MANAGE_TIMEPERIODS' => 'Управление периодами времени',
'LBL_MANAGE_USERS_TITLE' => 'Управление пользователями' ,
'LBL_MANAGE_USERS' => 'Управление пользователями (настройки и пароли)' ,
'LBL_MANAGE_WORKFLOW'                   => 'Workflow Management', ///
'LBL_MANUAL_VALIDATION_TXT' => 'Подтверждение вручную' ,
'LBL_MANUAL_VALIDATION'=>'
If you experience persistent problems with automatic validation, please check your Proxy configuration in the <a href="index.php?module=Configurator&action=EditView">System Settings</a> admin panel.
If your system environment prohibits your system from communicating to the license validation server through the internet, you should proceed with the <a href="javascript:void(0)" onclick="toggleDisplay(\'mainbody\');toggleDisplay(\'manualbody\');">Manual Validation</a> steps. ',
'LBL_MANUAL_VALIDATION1'=> 'Step 1: Generate a license key information file by clicking the following button. ', ///
'LBL_MANUAL_VALIDATION2'=> 'Then save the file (sugarkey.lic) on your local file system.', ///
'LBL_MANUAL_VALIDATION3'=> 'Step 2: Transfer the sugarkey.lic file to a system where you can access the internet with a web browser.   <br<br>Go to <a href="http://updates.sugarcrm.com/license">http://updates.sugarcrm.com/license</a>  and submit the sugarkey.lic file.  <br><br>The license validation web site will perform the validation immediately and return you the validation key file (sugarvalidationkey.lic) if the validation is successful.  You browser should prompt you to save the file.  ', ///
'LBL_MANUAL_VALIDATION4'=> 'Step 3:  Transfer the validation key file (sugarvalidationkey.lic) back to the SugarCRM system.  Import the validation key using this form below: ', ///
'LBL_MANUAL_VALIDATION5'=> 'After you import the validation key, you have completed the manual validation process.  Your system will update the validation key expiration date, which is the date when you need re-validate.', ///
'LBL_MANUFACTURERS_TITLE' => 'Manufacturers', ///
'LBL_MANUFACTURERS' => 'Set up the list of manufacturers', ///
'LBL_MASS_EMAIL_CONFIG_DESC'=> 'Настройка параметров электронной почты' ,
'LBL_MASS_EMAIL_CONFIG_TITLE'=> 'Настройка E-mail' ,
'LBL_MASS_EMAIL_MANAGER_DESC'=> 'Управление очерёдностью рассылки исходящей почты' ,
'LBL_MASS_EMAIL_MANAGER_HEADER'=> 'Управление рассылкой' ,
'LBL_MASS_EMAIL_MANAGER_TITLE'=> 'Управление очередью E-mail' ,
'LBL_MASSAGE_MASS_EMAIL_DESC'=> 'SugarCRM 3.5.1+ предполагает обновление для массовой рассылки E-mail.  Нажмите на кнопку "Начать обновление" для продолжения.' ,
'LBL_MASSAGE_MASS_EMAIL'=> 'GMT-исправление даты и времени при рассылке E-mail' ,
'LBL_MISSING_GLOBAL'=> 'We have noticed that there are users missing global team membership. If you would like to have a global team, please check the option below.', ///
'LBL_MISSING_PRIVATE'=> 'We have noticed that some users do not have private teams. If you would like to ensure that all users have private teams, we recommend that you repair the option below.', ///
'LBL_MISSING_TEAMS'=> 'We have noticed discrepancies between your reports to structure and your team strcuture. If you would like to repair this, please check the option below.', ///
//ModuleInstaller
'LBL_MI_REBUILDING' => 'Восстановление ',
'LBL_MI_SECTION' => 'раздел...',
'LBL_MI_IN_EXT' => 'Установка расширения %s',
'LBL_MI_UN_EXT' => 'Удаление расширения %s',
'LBL_MI_UN_CUSTOMFIELD' => 'Удаление пользовательских полей...',
'LBL_MI_IN_CUSTOMFIELD' => 'Установка пользовательских полей....',
'LBL_MI_COMPLETE' => 'Готово',
'LBL_MI_UN_BEAN' => 'Удаление Bean :',
'LBL_MI_IN_BEAN' => 'Установка Bean :',
'LBL_MI_IN_DASHLETS' => 'Установка Suite Dashlet ',
'LBL_MI_UN_DASHLETS' => 'Удаление Suite Dashlet ',
'LBL_MI_IN_IMAGES' => 'Установка иконок',
'LBL_MI_IN_MENUS' => 'Установка меню',
'LBL_MI_UN_MENUS' => 'Удаление меню',
'LBL_MI_IN_ADMIN' => 'Установка администраторского раздела ',
'LBL_MI_UN_ADMIN' => 'Удаление администраторского раздела ',
'LBL_MI_IN_USER' => 'Установка пользовательских страниц ',
'LBL_MI_UN_USER' => 'Удаление пользовательских страниц ',
'LBL_MI_IN_VAR' => 'Установка Variable Definitions',
'LBL_MI_UN_VAR' => 'Удаление Variable Definitions',
'LBL_MI_IN_SUBPANEL' => 'Установка макетов субпанелей',
'LBL_MI_UN_SUBPANEL' => 'Удаление макетов субпанелей',
'LBL_MI_IN_LANG' => 'Установка языковых пакетов',
'LBL_MI_UN_LANG' => 'Удаление языковых пакетов',
'LBL_MI_IN_RELATIONSHIPS' => 'Установка связей',
'LBL_MI_UN_RELATIONSHIPS' => 'Удаление связей',
'LBL_MI_UN_RELATIONSHIPS_DROP' => 'удаление таблиц ',
'LBL_MI_REPAIR_INDICES' => 'Восстановление индексов',
'LBL_MI_IN_CONNECTORS' => 'Установка подключений',
'LBL_MI_UN_CONNECTORS' => 'Удаление подключений',
'LBL_MI_IN_HOOKS' => 'Установка хуков',
'LBL_MI_UN_HOOKS' => 'Удаление хуков',
'LBL_MI_IN_SCHEDULEDTASKS' => 'Установка запланированных заданий',
'LBL_MI_UN_SCHEDULEDTASKS' => 'Удаление запланированных заданий',
'LBL_ML_ACTION' => 'Действие' ,
'LBL_ML_CANCEL'             => 'Отказаться',
'LBL_ML_COMMIT'=> 'Вперёд',
'LBL_ML_DESCRIPTION' => 'Описание' ,
'LBL_ML_INSTALLED' => 'Дата установки',
'LBL_ML_NAME' => 'Имя' ,
'LBL_ML_PUBLISHED' => 'Дата публикации' ,
'LBL_ML_TYPE' => 'Тип' ,
'LBL_ML_UNINSTALLABLE' => 'Возможность удаления' ,
'LBL_ML_VERSION' => 'Версия' ,
'LBL_ML_INSTALL'=> 'Установить',
'LBL_ML_ENABLE_OR_DISABLE'=> 'Вкл./Выкл.',
'LBL_ML_DELETE'=> 'Удалить',
'LBL_MODIFY_CREDENTIALS'     => 'Изменение учётных данных',
'LBL_MODULE_LICENSE'                        => 'Пожалуйста, прочитайте лицензионное соглашение:',
'LBL_MODULE_LOADER_TITLE' => 'Загрузчик модулей' ,
'LBL_MODULE_LOADER' => 'Добавление / удаление модулей, тем, языковых пакетов и других расширений' ,
'LBL_MODULE_NAME' => 'Администрирование' ,
'LBL_MODULE_TITLE' => 'Администрирование - ГЛАВНАЯ' ,
'LBL_MODULES_TO_DOWNLOAD'    => 'Загружаемые модули (переместите их сюда)',
'LBL_NEVER'=> 'Никогда' ,
'LBL_NEW_FORM_TITLE' => 'Создать контрагента' ,
'LBL_NOTIFY_SUBJECT' => 'Тема E-mail:' ,
'LBL_OC_SEARCH_FORM_TITLE' => 'Offline Client Search', ///
'LBL_OFFLINE_CLIENT'   => 'View Offline Clients that are connected to this Sugar system', ///
'LBL_OOTB_BOUNCE'       => 'Запускать ночью проверку почтовых ящиков для возвращаемых писем' ,
'LBL_OOTB_CAMPAIGN'     => 'Запускать ночью массовую рассылку писем' ,
'LBL_OOTB_IE'           => 'Проверять входящие письма' ,
'LBL_OOTB_PRUNE'        => 'Сжимать базу данных первого числа каждого месяца',
'LBL_OOTB_REPORTS'      => 'Выполнять запланированные задачи создания отчётов' ,
'LBL_OOTB_WORKFLOW'     => 'Обрабатывать задачи документооборота' ,
'LBL_OOTB_TRACKER'=> 'Очищать историю последних просмотров первого числа каждого месяца',
'LBL_UPDATE_TRACKER_SESSIONS' => 'Обновить таблицу tracker_sessions',
'LBL_OOTB_SUGARFEEDS'   => 'Очищать ленту событий',
'LBL_OOTB_DCE_CLNUP'    => 'Close loop on completed DCE actions', ///
'LBL_OOTB_DCE_REPORT'         => 'Create Action to gather daily reports', ///
'LBL_OOTB_DCE_SALES_REPORT'   => 'Create weekly Sales Report Email',    ///
'LBL_OVERWRITE_FILES'   => 'Перезаписать файлы',
'LBL_PASSWORD_SUGAR_SERVER_DESC'        => '- логин и пароль администратора на сервере',
'LBL_PASSWORD_SUGAR_SERVER'          => 'Пароль администратора:',
'LBL_PASSWORD'             => 'Пароль',
'LBL_PASSWORD_RESET_MANAGEMENT'=> 'Параметр сброса пароля',
'LBL_PASSWORD_RULES_MANAGEMENT'=> 'Требования к паролю',
'LBL_PASSWORD_TEMPLATE' => 'Шаблоны E-mail',
'LBL_PASSWORD_CREATE_TEMPLATE' => 'Создать',
'LBL_PASSWORD_EDIT_TEMPLATE' => 'Изменить',
'LBL_PASSWORD_GENERATE_TEMPLATE_MSG' => 'Шаблон письма, содержащий автоматически сгенерированный пароль',
'LBL_PASSWORD_LOST_TEMPLATE_MSG' => 'Шаблон письма, содержащий автоматически сгенерированную ссылку сброса пароля',
'LBL_PASSWORD_INVALID_LENGTH' => 'Минимальная длина должна быть меньше максимальной длины',
'LBL_PASSWORD_INVALID_MINLENGTH' => 'Минимальная длина должна быть больше 0',
'LBL_PASSWORD_SYST_GENERATED_PWD_ON' => 'Включить автоматическое создание паролей',
'LBL_PASSWORD_SYST_GENERATED_PWD_HELP' => 'Когда данная опция включена, пользователям будет высылаться письмо, содержащее  автоматически сгенерированную ссылку. Открыв данную ссылку пользователь попадёт на страницу, где сможет ввести новое значение пароля. Для работы этой опции необходимо следующее: 1) В настройках E-mail должен быть корректно настроен сервер исходящей почты.<br>2) Учётные записи пользователей должны содержать корректную информацию об их электронных адресах.',
'LBL_PASSWORD_EXP_AFTER'=> 'Пароль недействителен после',
'LBL_PASSWORD_FORGOT_FEATURE'=> 'Включить возможность сброса пароля',
'LBL_PASSWORD_FORGOT_FEATURE_HELP'=> 'Когда данная опция включена, пользователи будут иметь возможность сбросить пароль на странице ввода логина/пароля. Для работы этой опции необходимо следующее: 1) В настройках E-mail должен быть корректно настроен сервер исходящей почты и 2) Учётные записи пользователей должны содержать корректную информацию об их электронных адресах',
'LBL_PASSWORD_ONE_UPPER_CASE' => 'Должен содержать буквы в верхнем регистре (A-Z)',
'LBL_PASSWORD_ONE_LOWER_CASE' => 'Должен содержать буквы в нижнем регистре (a-z)',
'LBL_PASSWORD_ONE_NUMBER' => 'Должен содержать цифры (0-9)',
'LBL_PASSWORD_ONE_SPECIAL_CHAR' => 'Должен содержать как минимум один из следующих специальных символов: (~,!,@,#,$,%,^,&,*,(,),_,+,-,=,{,},|)',
'LBL_PASSWORD_ONLY_LOWCASE' => 'Только символы в нижнем регистре',
'LBL_PASSWORD_LOCKOUT' => 'Блокировка логина',
'LBL_PASSWORD_LOCKOUT_ATTEMPT1' => 'Блокировать логин после ',
'LBL_PASSWORD_LOCKOUT_ATTEMPT2' => ' безуспешных попыток входа в систему',
'LBL_PASSWORD_LOGIN' => 'Логин',
'LBL_PASSWORD_LOGINS' => 'входов в систему',
'LBL_PASSWORD_LOGIN_DELAY' => 'Активировать логин вновь через',
'LBL_PASSWORD_NEEDED_CARACTERS' => 'Обязательные символы',
'LBL_PASSWORD_PROHIBITED_CARACTERS' => 'Запрещённые символы',
'LBL_PASSWORD_MINIMUM_LENGTH'=> 'Минимальная длина',
'LBL_PASSWORD_MAXIMUM_LENGTH'=> 'Максимальная длина',
'LBL_PASSWORD_AND_MAXIMUM_LENGTH'=> 'и максимальная длина',
'LBL_PASSWORD_FIRSTNAME_PROHIBITED'=> 'Нельзя использовать имя',
'LBL_PASSWORD_LASTNAME_PROHIBITED'=> 'Нельзя использовать фамилию',
'LBL_PASSWORD_SYST_EXPIRATION'=> 'Истечение срока действия пароля, сгенерированного системой',
'LBL_PASSWORD_SYST_GENERATED_TITLE'=> 'Автоматическое создание паролей',
'LBL_PASSWORD_USER_EXPIRATION'=> 'Истечение срока действия пароля, созданного пользователем',
'ERR_PASSWORD_LINK_EXPIRE_TIME'   => 'Укажите время, после которого сгенерированная ссылка будет недействительна.',
'ERR_PASSWORD_EXPIRE_TIME'   => 'Укажите время, после которого пароль будет недействителен.',
'ERR_PASSWORD_EXPIRE_LOGIN'   => 'Укажите количество входов в систему, после которого пароль будет недействителен.',
'ERR_PASSWORD_LOCKOUT_TIME'   => 'Укажите время, после которого пользователи могут опять попытаться войти в систему.',
'ERR_PASSWORD_LOCKOUT_LOGIN'   => 'Укажите количество неудавшихся попыток входа в систему, после которых пользователи будут заблокированы.',
'LBL_PASSWORD_LINK_EXPIRATION'=> 'Истечение срока действия генерируемой ссылки сброса пароля',
'LBL_PASSWORD_LINK_EXPIRATION_HELP'=> 'Автоматически генерируемая системой ссылка высылается на основной E-mail пользователя, позволяя ему получить доступ к странице сброса пароля.',
'LBL_PASSWORD_REGEX'=> 'Запрещённые символы (регулярное выражение)',
'LBL_PASSWORD_REGEX_COMMENT'=> 'Описание регулярного выражения',
'LBL_PASSWORD_RULES' => 'Правила создания паролей',
'LBL_PASSWORD_LINK_EXP_IN'=> 'Ссылка будет недействительна через',
'LBL_PASSWORD_EXP_IN'=> 'Пароль будет недействителен через',
'LBL_PASSWORD_USER_RESET' => 'Сброс пароля пользователем',
'LBL_PERFORM_UPDATE'=> 'Выполнение обновления' ,
'LBL_PLUGINS_TITLE' => 'Sugar Forge' , ///
'LBL_PLUGINS' => 'Получить плагины и другие расширения.' ,
'LBL_PRICE_LIST_TITLE' => 'Product and Quotes', ///
'LBL_PRICE_LIST_DESC' => 'Manage the product catalog, along with the related information on manufacturers and shipping providers.',
'LBL_PRIVATE_TEAM' => 'Rebuild access to private team. Every user of the application must have one, and all managers in the upline must have access to it.', ///
'LBL_PRODUCT_CATEGORIES_TITLE' => 'Product Categories', ///
'LBL_PRODUCT_CATEGORIES' => 'Update the list of product categories', ///
'LBL_PRODUCT_TYPES_TITLE' => 'Product Types', ///
'LBL_PRODUCT_TYPES' => 'Configure the list of product types', ///
'LBL_PRODUCTS_TITLE' => 'Product Catalog', ///
'LBL_PRODUCTS' => 'Enter items in the product catalog', ///
'LBL_PROXY_AUTH'=> 'Аутентификация?' ,
'LBL_PROXY_HOST'=> 'Прокси-сервер' ,
'LBL_PROXY_ON_DESC'=> 'Используйте прокси-сервер для доступа к внешней информации , например для получения обновлений.' ,
'LBL_PROXY_ON'=> 'Использовать прокси-сервер?' ,
'LBL_PROXY_PASSWORD'=> 'Пароль' ,
'LBL_PROXY_PORT'=> 'Порт' ,
'LBL_PROXY_TITLE'=> 'Настройки прокси-сервера' ,
'LBL_PROXY_USERNAME'=> 'Логин' ,
'LBL_QUOTES_ORDERS_TITLE' => 'Quotes and Orders', ///
'LBL_README'                => 'Readme',
'LBL_REBUILD_AUDIT_DESC' => 'Перестройка таблицы аудита' ,
'LBL_REBUILD_AUDIT_TITLE' => 'Перестройка аудита' ,
'LBL_REBUILD_AUDIT_SEARCH' => 'Поиск новых модулей с включённым аудитом',
'LBL_REBUILD_AUDIT_CREATING' => 'creating table %1$s for %2$s .<BR>',   ///
'LBL_REBUILD_AUDIT_SKIP' => 'Таблица аудита для %1$s уже существует, пропускаем...<BR>',
'LBL_REBUILD_CONFIG_DESC' => 'Перестройка файла config.php: обновление версии системы и добавление значений по умолчанию при отсутствии их явных объявлений' ,
'LBL_REBUILD_CONFIG' => 'Перестройка файла конфигурации' ,
'LBL_REBUILD_DASHLETS_DESC_SHORT' => 'Перестройка кэш-файла дашлетов',
'LBL_REBUILD_DASHLETS_DESC_SUCCESS' => 'Кеш-файл дашлетов восстановлен.',
'LBL_REBUILD_DASHLETS_DESC' => 'Удаление кэш-файла дашлетов и просмотр директорий в поисках подходящих файлов дашлетов...',
'LBL_REBUILD_DASHLETS_TITLE' => 'Перестройка дашлетов',
'LBL_REBUILD_EXTENSIONS_DESC' => 'Перестройка расширений, включая определения переменных, языковые файлы, меню и панель администрирования' ,
'LBL_REBUILD_EXTENSIONS_TITLE' => 'Перестройка расширений',
//BEGIN SUGARCRM flav=een
'LBL_REBUILD_EXPRESSIONS_DESC' => 'Восстановление кэша хуков', ///
'LBL_REBUILD_EXPRESSIONS_TITLE' => 'Восстановление хуков', ///
//END SUGARCRM flav=een
'LBL_REBUILD_HTACCESS_DESC'=> 'Изменение .htaccess для ограничения прямого доступа к файлам' ,
'LBL_REBUILD_HTACCESS'=> 'Перестройка .htaccess-файла' ,
'LBL_REBUILD_WEBCONFIG_DESC'=> 'Восстановление файла web.config для ограничения прямого доступа к некоторым файлам',
'LBL_REBUILD_WEBCONFIG'=> 'Восстановление файла web.config на IIS7',
'LBL_REBUILD_JAVASCRIPT_LANG_DESC_SHORT' => 'Перестройка javascript-версий языковых файлов',
'LBL_REBUILD_JAVASCRIPT_LANG_DESC' => 'Удаление javascript-версий языковых файлов; файлы будут восстановлены при первой необходимости.',
'LBL_REBUILD_JAVASCRIPT_LANG_TITLE' => 'Перестройка Javascript Languages',

'LBL_REBUILD_JS_FILES_TITLE' => 'Перестройка сжатых файлов Javascript',
'LBL_REBUILD_JS_FILES_DESC_SHORT' => 'Копирование оригинальных файлов Javascript и замена ими существующих сжатых файлов',
'LBL_REBUILD_CONCAT_JS_FILES_TITLE' => 'Перестройка JS Grouping Files',
'LBL_REBUILD_CONCAT_JS_FILES_DESC_SHORT' => 'Перезапись JS Grouping Files их более свежими версиями',
'LBL_REBUILD_JS_MINI_FILES_TITLE' => 'Минимизация файлов Javascript',
'LBL_REBUILD_JS_MINI_FILES_DESC_SHORT' => 'Минимизация оригинальных файлов Javascript и замена ими существующих сжатых файлов',
'LBL_REPAIR_JS_FILES_TITLE' => 'Восстановление файлов Javascript',
'LBL_REPAIR_JS_FILES_DESC_SHORT' => 'Сжатие файлов Javascript, включая все внесённые изменения, но без перезаписи сжатыми файлами оригинальных файлов Javascript',
'LBL_REPAIR_JS_FILES_PROCESSING' => 'Восстановление файлов может занять несколько минут. Переход на другую страницу не остановит процесс восстановления, поэтому вы можете либо покинуть данную страницу, либо дождаться сообщения об окончании процесса восстановления...<br>',
'LBL_REPAIR_JS_FILES_DONE_PROCESSING' => 'Восстановление закончено.',
'LBL_REPAIR_FIELD_CASING_TITLE' => 'Восстановление нестрочных полей',
'LBL_REPAIR_FIELD_CASING_DESC_SHORT' => 'Приведение названий полей пользовательских таблиц и файлов метаданных к нижнему регистру',
'LBL_REPAIR_FIELD_CASING_PROCESSING' => 'Сканирование пользовательских полей и файлов...',
'LBL_REPAIR_FIELD_CASING_SQL_FIELD_META_DATA' => 'Обновление записи {0} в таблице fields_meta_data',
'LBL_REPAIR_FIELD_CASING_SQL_CUSTOM_TABLE' => 'Обновление поля {0} в таблице {1}',
'LBL_REBUILD_REL_DESC'=> 'Перестройка связей метаданных и удаление связей из кэша' ,
'LBL_REBUILD_REL_TITLE'=> 'Перестройка связей' ,
'LBL_REBUILD_REL_PROC_META'=> 'Обработка связей для ',
'LBL_REBUILD_REL_PROC_C_META'=> 'Обработка пользовательских связей для ',
'LBL_REBUILD_REL_DEL_CACHE'=> 'Удаление связей из кэша...<BR>',
'LBL_REBUILD_REL_UPD_WARNING'=> 'Обновление предупреждающих сообщений...<BR>',
'LBL_REBUILD_SCHEDULERS_DESC_SHORT' => 'Перестройка запланированных заданий' ,
'LBL_REBUILD_SCHEDULERS_DESC_SUCCESS' => 'Восстановление запланированных заданий завершено.' ,
'LBL_REBUILD_SCHEDULERS_DESC' => 'При восстановлении запланированных заданий будут удалены все основные существующие задания, а так же все соответствующие лог-файлы. Все остальные задания будут восстановлены с настройками по умолчанию, включая флаг активности.' ,
'LBL_REBUILD_SCHEDULERS_TITLE' => 'Перестройка заданий планировщика' ,
'LBL_REBUILD_SPRITES_TITLE' => 'Перестройка CSS-спрайтов',
'LBL_REBUILD_SPRITES_DESC_SHORT' => 'Перестройка изображений и конфигурационных файлов спрайтов',
'LBL_REBUILD_WORKFLOW_CACHE' => 'Rebuilding Workflow Cache...<BR>', ///
'LBL_REBUILD_WORKFLOW_COMPILING' => 'Compiling Plugins... <BR>', ///
'LBL_REBUILD' => 'Восстановление' ,
'LBL_REBUILD'=> 'Восстановление' ,
'LBL_REGEX_HELP_TITLE'=> 'Описание регулярного выражения',
'LBL_REGEX_HELP_TEXT'=> 'Здесь вы можете создавать собственные правила ввода пароля путём указания  соответствующего регулярного выражения. <b>Обратите внимание:</b> пароль должен НЕ СООТВЕТСТВОВАТЬ указанным в регулярном выражении условиям; условия, указанные в этом поле, не должны конфликтовать с остальными условиями.',
'LBL_REGEX_DESC_HELP_TEXT'=> 'Здесь вы можете указать краткое описание регулярного выражения. Данное описание будет отображаться при редактировании настроек пользователя в разделе <b>Изменение пароля</b>.',
'LBL_RELEASE' => 'Управление версиями' ,
'LBL_RENAME_TABS'=> 'Переименование закладок модулей' ,
'LBL_REPAIR_ACTION' => 'Что вы хотите сделать?' ,
'LBL_REPAIR_DATABASE_DESC' => 'Восстановление БД, основанное на значениях, определённых в vardefs (только MySQL)' ,
'LBL_REPAIR_DATABASE_PROCESSING' => 'Сравнение базы данных и vardef...',
'LBL_REPAIR_DATABASE_DIFFERENCES' => "Найдены различия между базой данных и vardefs",
'LBL_REPAIR_DATABASE_TEXT' =>   "The following script will sync the database structure with the structure defined " .
"in the vardefs. You have the option of exporting this script and then running it " .
"against your database using external database management tools, or to allow the " .
"administration module to run the script." .
"<br><br><strong>NOTE: any changes you make to the script in the textbox will be reflected " .
"in the exported or executed code.<br><br>",
'LBL_REPAIR_DATABASE_SYNCED' => 'Таблицы базы данных синхронизированы с Vardefs' ,
'LBL_REPAIR_DATABASE_EXECUTE' => "Выполнить",
'LBL_REPAIR_DATABASE_EXPORT' => "Экспортировать",
'LBL_REPAIR_DATABASE' => 'Восстановление Базы Данных' ,
'LBL_REPAIR_DISPLAYSQL' => 'Показ SQL' ,
'LBL_REPAIR_ENTRY_POINTS_DESC' => 'Восстановление точек входа.  Запустите этот скрипт, если вы получите ошибку: \'Not A Valid Entry Point\' .',
'LBL_REPAIR_ENTRY_POINTS' => 'Восстановление точек входа',
'LBL_REPAIR_EXECUTESQL' => 'Запуск SQL' ,
'LBL_REPAIR_EXPORTSQL' => 'Экспорт SQL' ,
'LBL_REPAIR_IE_DESC' => 'Восстановление учётных записей входящей почты и шифрование паролей',
'LBL_REPAIR_IE_FAILURE' => 'Следующие учётные записи входящей почты должны быть восстановлены вручную - укажите  ещё раз логин, пароль вводить не нужно:',
'LBL_REPAIR_IE_SUCCESS' => 'Все учётные записи входящей почты успешно восстановлены!',
'LBL_REPAIR_IE' => 'Восстановление учётных записей входящей почты',
'LBL_REPAIR_INDEX'=> 'Восстановление индексов',
'LBL_REPAIR_INDEX_DROPPING'=> '<BR>Dropping constraints/indexes.',
'LBL_REPAIR_INDEX_EXECUTING'=> '<BR> Выполнение ',
'LBL_REPAIR_INDEX_DROP'=> '<BR>Drop these constraints/indexes.',
'LBL_REPAIR_INDEX_ADDING'=> '<BR>Adding constraints/indexes.',
'LBL_REPAIR_INDEX_ADD'=> '<BR><BR>Add these constraints/indexes.',
'LBL_REPAIR_INDEX_ALTERING'=> '<BR>Altering constraints/indexes.',
'LBL_REPAIR_INDEX_ALTER'=> '<BR><BR>Alter these constraints/indexes.',
'LBL_REPAIR_INDEX_SYNC'=> '<BR><BR><BR> Index definitions are in sync.',
'LBL_REPAIR_ORACLE_COMMIT_DONE'         => 'All SQL queries commited.', ///
'LBL_REPAIR_ORACLE_COMMIT'              => 'Commit', ///
'LBL_REPAIR_ORACLE_VARCHAR_DESC_LONG_1' => 'The following queries should be run against your database.  Run them manually with the client of your choice or click the "Commit" button to have SugarCRM run the queries immediately.', ///
'LBL_REPAIR_ORACLE_VARCHAR_DESC_LONG_2' => 'No columns were discovered needing the VARCHAR2 char semantic change.', ///
'LBL_REPAIR_ORACLE_VARCHAR_DESC'        => 'Changes the semantics of VARCHAR2 columns from byte to char; necessary for UTF-8, MBCS support.', ///
'LBL_REPAIR_ORACLE_VARCHAR'             => 'Repair Oracle VARCHAR2 Columns', ///
'LBL_REPAIR_ROLES_DESC'=> 'Восстановление ролей путём добавления новых модулей, поддерживающих  контроль доступа, а так же путём добавления контроля доступа к уже существующим модулям',
'LBL_REPAIR_ROLES'=> 'Восстановление ролей',
'LBL_REPAIR_TEAMS_DESC'=> 'Rebuild private team memeberships based on user reporting hierarchy.', ///
'LBL_REPAIR_TEAMS'=> 'Repair Teams', ///
'LBL_REPAIR_TEAMS_PROCESS_USER'=> '<BR> Processing user=', ///
'LBL_REPAIR_TEAMS_REPORT'=> ' reports to=', ///
'LBL_REPAIR_TEAMS_SKIP_USER'=> '<BR> Skipping user=', ///
'LBL_REPAIR_TEAMS_NO_PROC'=> '<BR><BR>Nothing to process...', ///
'LBL_REPAIR_THEME_IMAGES'               => 'Оптимизация тем',
'LBL_REPAIR_THEME_IMAGES_DESC'          => 'Оптимизация тем путём удаления дублирующихся изображений.',
'LBL_REPAIR_XSS'                        => 'Удаление XSS',
'LBL_REPAIR_ACTIVITIES_DESC' => 'Восстановление мероприятий (звонков, встреч) и дат',
'LBL_REPAIR_ACTIVITIES_TEXT'=> 'Эта утилита позволяет исправить дату окончания звонков и встреч.',
'LBL_REPAIR_ACTIVITIES' => 'Восстановление мероприятий',
'LBL_CHECK_REPORTS_DESC' => 'Проверка корректности отчётов после обновления системы и показ списка некорректных отчётов, обнаруженных в процессе проверки',
'LBL_CHECK_REPORTS_TEXT'=> 'Эта утилита позволяет вам проверить корректность ваших отчётов.',
'LBL_CHECK_REPORTS' => 'Проверка отчётов',

'LBL_ALL'                               => 'Все',
'LBL_REPAIRXSS_COUNT'                   => 'объектов обнаружено',
'LBL_REPAIRXSS_INSTRUCTIONS'            => 'Выберите модуль для удаления потенциальных XSS-строк.  Выберите "Все" для обработки каждого модуля. <br>Нажмите кнопку <b>Выполнить</b> для начала процесса обнаружения / удаления уязвимостей.',
'LBL_REPAIRXSS_REPAIRED'                => 'объектов восстановлено',
'LBL_REPAIRXSS_TITLE'                   => 'Удаление XSS-уязвимостей из базы данных',

'LBL_RESERVE_OC_SPOT' => 'Reserve an Offline Client Position', ///
'LBL_RESTORE_BUTTON_LABEL' => 'Восстановить',
'LBL_RETURN' => 'Возврат' ,
'LBL_REVALIDATE'=> 'Повторная проверка' ,
'LBL_SEARCH_MODULE_NAME'    => 'Укажите полностью или частично название модуля:',
'LBL_SELECT_USER' => 'Выбор пользователя:',
'LBL_SEND_STAT'=> '<B>Отправлять анонимную статистику использования данного программного продукта</B>',
'LBL_SHIPPERS_TITLE' => 'Shipping Providers', ///
'LBL_SHIPPERS' => 'Set up the list of available shipment methods', ///
'LBL_SHOW_ADVANCED_OPTIONS' => 'Показать дополнительные настройки',
'LBL_STATUS'=> 'Статус ' ,
'LBL_TOOLS_DESC' => 'Создание и редактирование макетов модулей, управление стандартными и пользовательскими полями, настройка закладок. ',
'LBL_STUDIO_DESC' => 'Настройка существующих модулей: изменение макетов, добавление комбобоксов и пользовательских полей',
'LBL_STUDIO_TITLE' => 'Инструментарий разработчика' ,
'LBL_STUDIO' => 'Студия',
'LBL_SUGAR_NETWORK_TITLE' => 'Поддержка' ,
'LBL_SUGAR_NETWORK_DESC' => 'Доступ к порталу тех. поддержки, форумам SuiteCRM, Suite Wiki, просмотр FAQs (часто задаваемых вопросов), загрузка последних версий Suite, возможность сообщения о найденных в системе ошибках и многое другое...',
'LBL_SUGAR_SCHEDULER_TITLE' => 'Планировщик' ,
'LBL_SUGAR_SCHEDULER' => 'Настройка плановых заданий' ,
'LBL_SUGAR_SERVER_URL_DESC'          => '- The URL of the server this client will connect to (e.g., http://localhost/sugarserver).',  ///
'LBL_SUGAR_SERVER_URL'                => 'URL сервера:',
'LBL_SUGAR_UPDATE_TITLE'=> 'Обновление SuiteCRM' ,
'LBL_SUGAR_UPDATE'=> 'Проверить наличие свежей версии SuiteCRM.' ,
'LBL_SUGARCRM_HELP' => 'Справка по SuiteCRM ',
'LBL_SUPPORT_TITLE' => 'Suite  - портал технической поддержки' ,
'LBL_SUPPORT' => 'Доступ к технической поддержке',
'LBL_SYSTEM_NAME' => 'Название системы',
'LBL_TAXRATES_TITLE' => 'Tax Rates',
'LBL_TAXRATES' => 'Configure the list of available tax rates for quotes', ///
'LBL_TEAM_HIERARCHY' => 'Rebuild team hierarchy. Implicit access to all teams for all users will be rebuilt. <Br/>Let\'s say User A reports to User B who reports to User C. If explicit access to Team 1 is provided to User A, then User B and User C will acquire implicit access to this team.', ///
'LBL_TEAMS_TITLE' => 'Teams', ///
'LBL_TERMS_AND_CONDITIONS' => 'Условия соглашения',
'LBL_THEME_SETTINGS' => 'Темы',
'LBL_THEME_SETTINGS_DESC' => 'Настройка доступных пользователям тем',
'LBL_THEME_SETTINGS_AVAILABLE_THEMES' => 'Доступные темы',
'LBL_THEME_SETTINGS_UNAVAILABLE_THEMES' => 'Скрытые темы',
'LBL_TIMEZONE' => 'Часовой пояс' ,
'LBL_TO'    => ' to ',   ///
'LBL_TRACKER_SETTINGS' => 'Трекер',
'LBL_TRACKER_SETTINGS_DESC' => 'Включить/Отключить трекинг',
'LBL_SUGARFEED_SETTINGS' => 'Лента событий',
'LBL_SUGARFEED_SETTINGS_DESC' => 'Включение ленты событий и выбор контролируемых модулей',
'LBL_UPDATE_CHECK_AUTO'=> 'Автоматически' ,
'LBL_UPDATE_CHECK_MANUAL'=> 'Вручную' ,
'LBL_UPDATE_CHECK_TYPE'=> 'Автоматически проверять доступные обновления' ,
'LBL_UPDATE_DESCRIPTIONS'=> 'Описание' ,
'LBL_UPDATE_TITLE'=> 'Доступные обновления Suite:' ,
'LBL_UPGRADE_ADDED_TO_GROUP' => 'Добавлен в группу',
'LBL_UPGRADE_ALREADY_EXISTS_GROUP' => 'группа уже существует',
'LBL_UPGRADE_ALREADY_EXISTS_IN_GROUP' => 'Уже присутствуют в группе:',
'LBL_UPGRADE_CONVERT_DISC_CLIENT_TITLE' => 'Convert to Offline Client', ///
'LBL_UPGRADE_CONVERT_DISC_CLIENT'      => 'Convert this Sugar installation to an Offline Client', ///
'LBL_UPGRADE_CONVERT_DISC_DESCRIPTION'  => '<b>Warning: Please ensure this is a fresh install with no seed data.</b><br>Enter the following information and press Save to convert this system into an offline client.', ///
'LBL_UPGRADE_CURRENCY' => 'Обновление валютной суммы в модуле ' ,
'LBL_UPGRADE_CUSTOM_LABELS_DESC'=> 'Обновление форматов пользовательских меток полей в каждом языковом файле.' ,
'LBL_UPGRADE_CUSTOM_LABELS_TITLE'=> 'Обновление пользовательских меток' ,
'LBL_UPGRADE_DB_BEGIN' => 'Начало обновления' ,
'LBL_UPGRADE_DB_COMPLETE' => 'Обновление завершено' ,
'LBL_UPGRADE_DB_FAIL' => 'Ошибка обновления' ,
'LBL_UPGRADE_DB_TITLE' => 'Обновление базы данных' ,
'LBL_UPGRADE_DB' => 'Обновление БД с версии 2.0.x до 2.5 ' ,
'LBL_UPGRADE_FOR_PRODUCT'=> 'for Product',
'LBL_UPGRADE_NEW_GROUP' => 'Создана новая группа',
'LBL_UPGRADE_NOT_UPGRADING' => 'Not attempting to upgrade',   ///
'LBL_UPGRADE_STUDIO_DESC'=> ' Обновление файлов предыдущих версий до версии 4.5',
'LBL_UPGRADE_STUDIO_TITLE'=> 'Обновление',
'LBL_UPGRADE_SYNC_DISC_CLIENT_TITLE'    => 'Синхронизация',
'LBL_UPGRADE_SYNC_DISC_CLIENT'        => 'Синхронизация клиентских файлов с даными на сервере',
'LBL_UPGRADE_TEAM_CREATE' => 'Created Teams for -', ///
'LBL_UPGRADE_TEAM_EXISTS'=> 'Team Already Exists', ///
'LBL_UPGRADE_TEAM_TITLE' => 'Upgrade teams', ///
'LBL_UPGRADE_TEAMS' => 'Creates teams for users ', ///
'LBL_UPGRADE_TITLE' => 'Восстановление' ,
'LBL_UPGRADE_VERSION'=> 'Информация о версии обновления' ,
'LBL_UPGRADE_WIZARD_TITLE' => 'Мастер обновления' ,
'LBL_UPGRADE_WIZARD' => 'Управление обновлениями' ,
'LBL_UPGRADE' => 'Проверка и восстановление Suite' ,
'LBL_UPLOAD_UPGRADE' => 'Загрузка обновления: ' ,
'LBL_UPTODATE'=> 'У вас установлена самая последняя версия' ,
'LBL_USER_NAME' => 'Имя пользователя:',
'LBL_USERNAME'             => 'Логин',
'LBL_USERS_TITLE' => 'Пользователи' ,
'LBL_HISTORY_CONTACTS_EMAILS' => 'Настройка субпанели "История"',
'LBL_HISTORY_CONTACTS_EMAILS_DESC' => 'Настройка отображения писем контактов в субпанели истории',

'LBL_USERS_DESC' => 'Создание, редактирование, включение/отключение профилей пользователей системы.',



'LBL_UW_BTN_BACK_TO_MOD_LOADER'         => 'Возврат на страницу загрузки модулей',
'LBL_UW_BTN_BACK_TO_UW'                     => 'Возврат на страницу мастера обновления',
'LBL_UW_BTN_DELETE_PACKAGE'             => 'Удалить пакет',
'LBL_UW_BTN_DOWNLOAD' => 'Загрузить',
'LBL_UW_BTN_INSTALL'                        => 'Установить',
'LBL_UW_BTN_UPLOAD'                         => 'Загрузить',
'LBL_UW_CHECK_ALL'=> 'Проверить все',
'LBL_UW_DESC_MODULES_INSTALLED'         => 'Расширения, установленные в систему:',
'LBL_UW_DESC_MODULES_QUEUED'                => 'Следующие модули готовы к установке:',
'LBL_UW_DISABLE'    => 'Отключить',
'LBL_UW_ENABLE' => 'Включить',
'LBL_UW_FOLLOWING_FILES'                    => 'Следующие файлы были',
'LBL_UW_HIDE_DETAILS'=> 'Скрыть подробности',
'LBL_UW_INCLUDING'                          => 'Включая',
'LBL_UW_MODULE_READY_DISABLE'   => 'Модуль может быть отключён.',
'LBL_UW_MODULE_READY_ENABLE' => 'Модуль может быть включён.',
'LBL_UW_LANGPACK_READY_DISABLE'   => 'Языковой пакет может быть отключён.',
'LBL_UW_LANGPACK_READY_ENABLE' => 'Языковой пакет может быть включён.',
'LBL_UW_MODULE_READY_UNISTALL'          => 'Модуль готов к деинсталляции.',
'LBL_UW_LANGPACK_READY_UNISTALL'          => 'Языковой пакет готов к деинсталляции.',
'LBL_UW_MODULE_READY'           => 'Модуль готов к установке.',
'LBL_UW_LANGPACK_READY'           => 'Языковой пакет готов к установке.',
'LBL_UW_NO_FILES_SELECTED'                  => 'Не выбраны файлы',
'LBL_UW_NO_INSTALLED_UPGRADES'              => "<i>Нет установленных обновлений.</i><br>\n",
'LBL_UW_NONE'                               => 'Нет',
'LBL_UW_NOT_AVAILABLE'                      => "Не доступно",
'LBL_UW_OP_MODE'                            => 'Режим операции:',
'LBL_UW_PACKAGE_REMOVED'                    => " был удалён.<br>\n",
'LBL_UW_PATCH_READY'=> '<h2>Все готово к установке</h2>',
'LBL_UW_UNINSTALL_READY'=> '<h2>Все готово к деинсталляции</h2>',
'LBL_UW_DISABLE_READY'=> '<h2>Все готово к отключению</h2>',
'LBL_UW_ENABLE_READY'=> '<h2>Все готово к включению</h2>',
'LBL_UW_SHOW_DETAILS'=> 'Показать подробности',
'LBL_UW_SUCCESSFUL' => 'успешно установлен',
'LBL_UW_SUCCESSFULLY' => 'успешно',
'LBL_UW_UNINSTALL'                          => 'Деинсталляция',
'LBL_UW_UPGRADE_SUCCESSFUL'             => "<b>Обновление успешно применено!</b><br>\n",
'LBL_UW_UPLOAD_MODULE'                      => 'Модуль',
'LBL_UW_TYPE_FULL'                          => 'Обновление',
'LBL_UW_TYPE_LANGPACK'                      => 'Языковой пакет',
'LBL_UW_TYPE_MODULE'                        => 'Модуль',
'LBL_UW_TYPE_PATCH'                         => 'Патч',
'LBL_UW_TYPE_THEME'                         => 'Тема',
'LBL_UW_MODE_INSTALL'                       => 'установлен',
'LBL_UW_MODE_UNINSTALL'                     => 'деинсталлирован',
'LBL_UW_MODE_DISABLE'                       => 'отключён',
'LBL_UW_MODE_ENABLE'                        => 'включён',
'LBL_UW_UPLOAD_SUCCESS'                     => " успешно загружен<br>",
'LBL_VALIDATION_FAIL_DATE'=> 'Последняя неудачная проверка: ' ,
'LBL_VALIDATION_FILE'=> 'Файл лицензионного ключа' ,
'LBL_VALIDATION_SUCCESS_DATE'=> 'Последняя удачная проверка: ' ,
'LBL_VISIBLE_PANELS'=> 'Отображаемые субпанели',
'LBL_VISIBLE_TABS'=> 'Отображаемые закладки модулей',
'LBL_WORKFLOW_DESC'                     => 'Manage workflow conditions, alerts and actions', ///
'LBL_WORKFLOW_TITLE'                    => 'Workflow Management', ///
'LBL_WORKBENCH' => 'Workbench', ///
'LBL_WORKBENCH_DESC' => 'Customize the application and create new modules.', ///

'LNK_DISABLE'   => 'Отключить',
'LNK_ENABLE'   => 'Включить',
'LNK_FORGOT_PASS' => 'Забыли ваш пароль?',
'LNK_NEW_ACCOUNT' => 'Создание учётной записи',
'LNK_NEW_PRODUCT' => 'Create Product', ///
'LNK_NEW_TEAM' => 'Create Team', ///
'LNK_NEW_USER' => 'Создание пользователей' ,
'LNK_REPAIR_CUSTOM_FIELD' => 'Восстановление пользовательских полей',
'LNK_SELECT_CUSTOM_FIELD' => 'Редактирование / Удаление пользовательского поля',
'LNK_NEW_PORTAL_USER'=> 'Создать нового пользователя Портала',
'LNK_NEW_GROUP_USER'=> 'Создать нового группового пользователя',
'MI_LBL_DISABLE_DEPEDENCIES' => 'Модуль не может быть отключён, поскольку существуют другие модули, зависящие от данного модуля.',
'MI_REDIRECT_TO_UPGRADE_WIZARD' => 'Вы будете перенаправлены на страницу <b>Мастера обновлений</b> для выполнения необходимых проверок системы. Продолжить?',
'ML_DESC_DOCUMENTATION'     => 'Нажмите на узле дерева для просмотра детальной информации и документации',
'ML_LBL_DETAIILS'           => 'Подробности',
'ML_LBL_DO_NOT_REMOVE_TABLES' => 'Не удалять таблицы',
'ML_LBL_DOCUMENTATION'      => 'Документация',
'ML_LBL_INSTALL_FROM_LOCAL'=> 'Установить из локальной папки',
'ML_LBL_INSTALL_FROM_SERVER' => 'Установить с сервера Suite',
'ML_LBL_OVERWRITE_FILES'    => 'Со времени вашей последней работы с модулем файлы изменились. Что вы хотите предпринять?',
'ML_LBL_REMOVE_TABLES' => 'Удалить таблицы',
'ML_LBL_REVIEWS'            => 'Обзоры',
'ML_LBL_SCREENSHOTS'        => 'Скриншоты',
'MSG_CONFIG_FILE_READY_FOR_REBUILD' => 'Файл config.php готов для перестройки.' ,
'MSG_CONFIG_FILE_REBUILD_FAILED' => 'Файл config.php не перестроен.' ,
'MSG_CONFIG_FILE_REBUILD_SUCCESS' => 'Файл config.php успешно перестроен.' ,
'MSG_INCREASE_UPLOAD_MAX_FILESIZE' => 'Предупреждение: Ваша PHP-конфигурация должна быть изменена таким образом, чтобы была возможность загрузки файлов размером не менее 6МБ. Пожалуйста, исправьте значение переменной upload_max_filesize в файле php.ini находящемся в:' ,
'MSG_MAKE_CONFIG_FILE_WRITABLE' => 'Пожалуйста, сделайте  файл config.php доступным для записи и попробуйте  ещё раз.' ,
'MSG_REBUILD_EXTENSIONS' => 'Пожалуйста, перейдите по ссылке "Восстановление" в панели администратора и кликните на ссылке "Восстановление расширений".' ,
'MSG_REBUILD_RELATIONSHIPS' => 'Пожалуйста, перейдите по ссылке "Восстановление" в панели администратора и кликните на ссылке "Восстановление связей".' ,
'NO_ENABLED_OFFLINE_CLIENTS' => 'There currently are no enabled Offline Clients.',  ///
'NTC_DISABLE_OFFLINE_CLIENT_ALERT' => 'Are you sure you want to disable this Offline Client?',     ///
'NTC_ENABLE_OFFLINE_CLIENT_ALERT' => 'Are you sure you want to enable this Offline Client?', ///
'NTC_OC_NOT_AVAILABLE' => 'Не доступно',
'NTC_OC_RESERVED' => 'Reserved',
'REMOVE_QUESTION'           => 'Вы действительно хотите удалить выбранные пакеты?',
'WARN_POSSIBLE_JS_OVERWRITE'=> 'Осторожно, это приведёт к перезаписи всех изменений, которые вы могли сделать в файлах javascript. Продолжить?',
'WARN_INSTALLER_LOCKED'=> 'Предупреждение: Для сохранения ваших данных инсталлятор должен быть заблокирован путём установки переменной installer_locked в значение "true" в файле config.php.' ,
'WARN_LICENSE_EXPIRED'=> 'Сообщение: До истечения срока действия вашей лицензии осталось дней: ' ,
'WARN_LICENSE_EXPIRED2' => " Пожалуйста, перейдите к <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a>  в панели администратора.",
'WARN_LICENSE_SEATS'=> "Warning: User licenses exceeded by ", ///
'WARN_LICENSE_SEATS2' => ".  Please contact your sales representative or email <a href='mailto:sales@sugarcrm.com'>sales@sugarcrm.com</a>.", ///
'WARN_LICENSE_SEATS_MAXED'=> "Warning: The number of active users is already the maximum number of licenses allowed: ", ///
'WARN_LICENSE_SEATS_EDIT_USER'=> "Warning: The number of active users is already the maximum number of licenses allowed", ///
'WARN_LICENSE_SEATS_USER_CREATE'=> "Warning: The number of active users allowed by your license matches the number of active users in the system. You will not be able to create additional active users.", ///
'WARN_REPAIR_CONFIG' => 'Предупреждение: Файл config.php должен быть перестроен. В панели администратора перейдите по ссылке  "<a href=\'index.php?module=Administration&action=RebuildConfig\'>Перестройка файла конфигурации</a>".' ,
'WARN_UPGRADE_APP'=> 'В данный момент доступна обновлённая версия приложения.' ,
'WARN_UPGRADE' => 'Внимание: система может быть обновлена до версии ' ,
'WARN_UPGRADENOTE' => 'Примечание: ',
'WARN_UPGRADE2'=> ', используя ссылку "Восстановление" в панели администратора' ,
'WARN_VALIDATION_EXPIRED'=> 'Предупреждение: действие вашего лицензионного ключа истечёт через ' ,
'WARN_VALIDATION_EXPIRED2' => " day(s). Please update information in the <a href='index.php?action=LicenseSettings&module=Administration'>'\"License Management\"</a> page in the Admin area.", ///
'WARN_NO_SMTP_SERVER_AVAILABLE_ERROR' => "Примечание: для отправки уведомлений должен быть настроен SMTP-сервер в разделе <a href='index.php?module=EmailMan&action=config'>Настройка параметров E-mail</a>.",
'LBL_MODULEBUILDER'=> 'Конструктор модулей',
'LBL_MODULEBUILDER_DESC'=> 'Создание новых модулей для расширения функциональности SuiteCRM' ,
'LBL_SUGARPORTAL'=> 'Портал',
'LBL_SUGARPORTAL_DESC' => 'Управление порталом',
'LBL_CLEAR_TEMPLATE_DATA_CACHE_DESC' => 'Удаление кэшированных файлов шаблонов',
'LBL_CLEAR_TEMPLATE_DATA_CACHE_TITLE'=> 'Очистка кэша шаблонов',
'LBL_CLEAR_VARDEFS_DATA_CACHE_TITLE'=> 'Очистка кэша Vardefs',
'LBL_CLEAR_VARDEFS_DATA_CACHE_DESC'=> 'Удаление vardefs из кэша',
'LBL_CLEAR_UNIFIED_SEARCH_CACHE_TITLE'=> 'Очистка кэша общего поиска',
'LBL_CLEAR_UNIFIED_SEARCH_CACHE_DESC'=> 'Удаление файла unified_search_modules.php из кэша',
'LBL_QUICK_REPAIR_AND_REBUILD'=> 'Быстрое восстановление',
'LBL_QUICK_REPAIR_TITLE'=> 'Выберите модули для восстановления:',
'LBL_FAILED_CONNECTION'=> 'Невозможно установить соединение:',
'LBL_QUICK_REPAIR_AND_REBUILD_DESC'=> 'Синхронизация таблиц с Vardefs, очистка кэша, восстановление таблиц аудита, расширений, дашлетов' ,
'LBL_ALL_MODULES'=> 'Все модули',
'LBL_CAMPAIGN_CONFIG_TITLE'=> 'Параметры рассылки E-mail',
'LBL_CAMPAIGN_CONFIG_DESC'=> 'Настройка параметров рассылки E-mail.',
'LBL_REPAIR_ORACLE_FULLTEXT'             => 'Rebuild fulltext indices', ///
'LBL_REPAIR_ORACLE_FULLTEXT_DESC'        => 'Triggers a rebuild of fulltext indices. Oracle 9i owners should run this frequently.', ///
'LBL_REPAIR'=> 'Восстановить',
'LBL_QR_CBOX_DATAB'=> 'Восстановление БД',
'LBL_QR_CBOX_CLEARTPL'=> 'Очистка кэша файлов .tpl',
'LBL_QR_CBOX_CLEARJS'=> 'Очистка кэша файлов Javascript',
'LBL_QR_CBOX_CLEARVARDEFS'=> 'Очистка кэша Vardefs',
'LBL_QR_CBOX_CLEARJSLANG'=> 'Очистка кэша языковых файлов Javascript',
'LBL_QR_CBOX_CLEARDASHLET'=> 'Очистка кэша дашлетов',
'LBL_QR_CBOX_REBUILDAUDIT'=> 'Перестройка таблиц аудита',
'LBL_QR_CBOX_REBUILDEXT'=> 'Перестройка расширений',
'LBL_QR_CBOX_CLEARLANG'=> 'Очистка кэша языковых файлов',
'LBL_QR_CBOX_CLEARSEARCH'=> 'Очистка кэша общего поиска',
'LBL_QR_REBUILDEXT'=> '<h3> Перестройка расширений...</h3>',
'LBL_QR_CLEARSMARTY'=> 'Очистка кэша Smarty-шаблонов...готово',
'LBL_QR_XMLFILES'=> 'Очистка кэша файлов XML...готово',
'LBL_QR_CLEARDASHLET'=> 'Очистка кэша дашлетов...готово',
'LBL_QR_CLEARTEMPLATE'=> 'Очистка кэша файлов шаблонов...готово',
'LBL_QR_CLEARVADEFS'=> 'Очистка кэша Vardefs...готово',
'LBL_QR_CLEARJS'=> 'Очистка кэша файлов JS...готово',
'LBL_QR_CLEARJSLANG'=> 'Очистка кэша языковых файлов JS...готово',
'LBL_QR_CLEARLANG'=> 'Очистка кэша языковых файлов...готово',
'LBL_QR_CLEARSEARCH'=> 'Очистка кэша общего поиска...готово',
'LBL_QR_REBUILDAUDIT'=> 'Перестройка таблиц аудита...',
'LBL_QR_CBOX_CLEARSUGARFEEDCACHE'=> 'Очистка кэша ленты событий',
'LBL_QR_CLEARSUGARFEEDCACHE'=> 'Очистка кэша ленты событий...готово',
'LBL_QR_CBOX_CLEARTHEMECACHE'=> 'Очистка кэша тем',
'LBL_QR_CLEARTHEMECACHE'=> 'Очистка кэша тем...готово',
'LBL_REPAIR_DB_FOR'=> 'Восстановление БД для',
'LBL_QR_CREATING_TABLE'=> 'создание таблицы',
'LBL_QR_NOT_AUDIT_ENABLED'=> ' - аудит не включён...<br/>',
'LBL_FOR'=> 'для',
'LBL_QR_CBOX_CLEARPDFFONT'=> 'Clear PDF Font Cache File', ///
'LBL_QR_CLEARPDFFONT'=> 'Clearing PDF Font Cache File...done', ///
'LBL_QR_CLEAR_EXT_API'=> 'Очистка кэша внешнего API...готово',
'LBL_TRACKER_SETTINGS' => 'Трекер',
'LBL_TRACKER_SETTINGS_DESC' => 'Включить/Отключить трекинг',
'LBL_REPAIR_SEED_USERS_TITLE'=> 'Включить/Отключить демо-пользователей',
'LBL_REPAIR_SEED_USERS_ACTIVATE'=> 'Включить',
'LBL_REPAIR_SEED_USERS_DECACTIVATE'=> 'Отключить',
'LBL_REPAIR_SEED_USERS_DESC' => 'Быстрое включение/отключение пользователей, добавленных в систему при заполнении БД демонстрационными данными в процессе установки системы',
'LBL_UW_FILES_REMOVED'=> "Следующие файлы будут удалены из системы:<br>\n",
'LBL_TEAM_SETS' => 'Clean up unused combinations of teams.', ///

'LBL_MODULE_UPLOAD_DISABLE_HELP_TEXT' => 'Возможность загрузки новых модулей напрямую ограничена. Перечисленные ниже модули загружены в специальную директорию и при необходимости могут быть проверены перед установкой в систему.',

'ML_PACKAGE_SCANNING'=> 'Сканирование {PACKAGE}',
'ML_INSTALLATION_FAILED'=> 'Установка прервана!',
'ML_PACKAGE_NOT_CONFIRM'=> 'Пакет, который вы пытаетесь установить, не соответствует политике в рамках <b>Suite Open Cloud</b> или политике, установленной вашим системным администратором.',
'ML_TO_RESOLVE'=> 'Для решения данной проблемы:',
'ML_OBTAIN_NEW_PACKAGE'=> 'Клиенты <b>Suite Open Cloud</b> должны получить новый установочный пакет от поставщика для устранения нижеописанных проблем.',
'ML_RELAX_LOCAL'=> 'Если Suite используется только в локальной сети, вы можете уменьшить ограничения Загрузчика Модулей на разрешение установки пакета.',
'ML_SUGAR_LOADING_POLICY'=> 'Политики загрузки пакета <b>Suite Open Cloud</b> подробно изложены в',
'ML_SUGAR_KB'=> 'База знаний SuiteCRM',
'ML_SUGAR_DZ'=> 'Зона разработчика SuiteCRM',
'ML_AVAIL_RESTRICTION'=> 'Имеющиеся ограничения и исключения подробно изложены в',
'ML_OVERRIDE_CORE_FILES'=> 'Переопределение основных файлов SuiteCRM не допускается ',
'ML_PATH_MAY_NOT_CONTAIN'=> 'Путь к файлу может не содержать',
'ML_INVALID_ACTION_IN_MANIFEST'=> 'Ошибка в файле манифеста:',
'ML_NO_MANIFEST'=> 'Установочный пакет не содержит файл манифеста',
'ML_INVALID_FUNCTION'=> 'Неверное использование функции ',
'ML_INVALID_METHOD'=>'Неверное использование зарезервированного названия метода ',
'ML_INVALID_EXT'=> 'Неверное расширение файла ',
'ML_ISSUES'=> 'Проблемы',
'ML_MANIFEST_ISSUE'=> 'Проблема с файлом манифеста',
'ML_CONFIG_OVERRIDE'=>'Файл конфигурации был изменён, изменения подобного рода недопустимы',

'LBL_ACTIVE_MODULES' => 'Отображаемые модули',
'LBL_DISABLED_MODULES' => 'Скрытые модули',
'LBL_SAVE_SUCCESS' => '<h4>Изменения успешно сохранены</h4><br/>Сейчас вы будете перенаправлены на главную страницу панели администрирования.',
'LBL_SAVE_FAILED' => 'Не удалось сохранить изменения.<br/> Проверьте права доступа к файлам.',
'LBL_SAVING' => 'Сохранение...',
'LBL_ACTIVE_THEMES' => 'Доступные темы',
'LBL_DISABLED_THEMES' => 'Скрытые темы',
'DEFAULT_THEME'=> 'Стандартная тема',
'LBL_DEFAULT_THEME_IS_DISABLED' => 'Тема, выбранная в качестве стандартной, скрыта. Нажмите на кнопку "OK" для сохранения выполненных изменений или на кнопку "Отказаться" для выбора другой стандартной темы.',
'LBL_ENABLED_LANGS' => 'Доступные языковые пакеты',
'LBL_DISABLED_LANGS' => 'Скрытые языковые пакеты',

//language changed
'LBL_CURRENT_LANGUAGE_CHANGE' => 'Your current language is changed to ',
'LBL_DEFAULT_LANGUAGE_CHANGE' => 'System\'s default language is changed to ',
'ACLActions'     => 'ACLAction',
'ACLFields'      => 'ACLField',
'ACLRoles'       => 'ACLRole',
'Administration' => 'Administration',
'Audit'  => 'Audit',
'CampaignTrackers' => 'CampaignTracker',
'Connectors'     => 'Connectors',
'ContractTypes'  => 'ContractType',
'Currencies'     => 'Currency',
'CustomFields'   => 'CustomFields',
'CustomQueries'  => 'CustomQuery',
'DataSets'  => 'DataSet',
'DocumentRevisions'  => 'DocumentRevision',
'DynamicFields'  => 'DynamicField',
'EditCustomFields' => 'FieldsMetaData',
'EmailMan' => 'EmailMan',
'Employees'      => 'Employee',
'Expressions'  => 'Expression',
'Feeds'          => 'Feed',
'ForecastOpportunities'  => 'ForecastOpportunities',
'ForecastSchedule'  => 'ForecastSchedule',
'Groups' => 'Group',
'Holidays' => 'Holiday',
'Import_1'       => 'ImportMap',
'Import_2'       => 'UsersLastImport',
'InboundEmail' => 'InboundEmail',

'KBContents' => 'KBContent',
'KBDocumentKBTags' => 'KBDocumentKBTag',
'KBDocumentRevisions' => 'KBDocumentRevision',
'KBTags' => 'KBTag',
'Manufacturers'  => 'Manufacturer',
'ProductBundleNotes' => 'ProductBundleNote',
'ProductBundles'   => 'ProductBundle',
'ProjectResources' => 'ProjectResource',

'Relationships' => 'Relationship',
'Releases'       => 'Release',
'ReportMaker'  => 'Advanced Reports',
'Reports_1'      => 'SavedReport',
'Roles'  => 'Role',
'Schedulers'  => 'Scheduler',
'SchedulersJobs'  => 'SchedulersJob',
'Shippers'       => 'Shipper',
'TaxRates'       => 'TaxRate',
'TeamHierarchies'  => 'TeamHierarchy',
'TeamMemberships'   => 'TeamMembership',
'TeamNotices'    => 'TeamNotice',
'TeamSetModules'   => 'TeamSetModule',
'TeamSets'         => 'TeamSet',
'TimePeriods'    => 'TimePeriod',
'TrackerPerfs'   => 'TrackerPerf',
'TrackerQueries' => 'TrackerQuery',
'TrackerSessions'=> 'TrackerSession',
'UserPreferences'  => 'UserPreference',
'Versions'       => 'Version',
'WorkFlowActions'  => 'WorkFlowAction',
'WorkFlowActionShells'  => 'WorkFlowActionShell',
'WorkFlowAlerts'  => 'WorkFlowAlert',
'WorkFlowAlertShells'  => 'WorkFlowAlertShell',
'WorkFlowTriggerShells'  => 'WorkFlowTriggerShell',
'Worksheet'  => 'Worksheet',
'LBL_SAML_ENABLE' => 'Включить SAML-аутентификацию',
'LBL_SAML_HELP_TXT' => 'При использовании SAML-аутентификации пароли будут обрабатываться только через SAML. Все дополнительные настройки, указанные в этом разделе, будут проигнорированы.',
'LBL_SAML_TITLE' => 'SAML-аутентификация',
'LBL_SAML_CERT' => 'X509-сертификат',
'LBL_SAML_CERT_DESC' => 'Введите X509-сертификат',
'LBL_SAML_LOGIN_URL' => 'SAML URL',
'LBL_SAML_LOGIN_URL_DESC' => 'Укажите Login URL',

'LBL_GLOBAL_SEARCH_SETTINGS_TITLE' => 'Выберите модули, в которых будет осуществляться глобальный поиск.',
'LBL_SELECT_MODULES' => 'Дополнительно',
'LBL_SELECT_MODULES_TITLE' => 'Модули, перемещённые в левую колонку, будут задействованы в процессе глобального поиска. В этой же колонке вы можете сортировать модули для отображения результатов поиска в необходимой вам последовательности.',
'LBL_SELECT_FTS_MODULES_TITLE' => 'Drag and drop to select modules to be used in the Global Search. Click Save to apply the changes.', ///
'LBL_EAPM_SETTINGS' => 'Внешние учётные записи',
'LBL_EAPM_SETTINGS_DESC' => 'Выберите  приложения, доступ к которым из Suite возможен с использованием указанных учётных данных.',
	'LBL_LANGUAGE_PACKS' => 'Языковые пакеты' /*for 508 compliance fix*/,
	'LBL_PATCH_UPGRADES' => 'Обновления' /*for 508 compliance fix*/,
	'LBL_ADVANCED_SEARCH' => 'Расширенный поиск' /*for 508 compliance fix*/,
	'LBL_BASIC_SEARCH' => 'Базовый поиск' /*for 508 compliance fix*/,
	'LBL_PROCESSING' => 'Обработка' /*for 508 compliance fix*/,

'LBL_MI_IN_ACTIONVIEWMAP' => 'Установка Action View Map',
'LBL_MI_UN_ACTIONVIEWMAP' => 'Удаление Action View Map',
// OAuth
'LBL_OAUTH_TITLE' => "Ключи OAuth",
'LBL_OAUTH' => "Управление ключами OAuth",
'LBL_SAML_LOGIN_URL_DESC' => 'Укажите Login URL',

// SNIP / Sugar Ease / Email Archiving
'LBL_SNIP_TITLE' => 'Email Archiving', ///
'LBL_SNIP_DESC' => 'Configure offline archiving (Email Archiving)', ///
'LBL_CONFIGURE_SNIP' => 'Email Archiving', ///
'LBL_CONFIGURE_SNIP_DESC' => 'Enable/disable the Sugar Email Archiving Service', ///

    //Sprites Support
    'LBL_SPRITES_NOT_SUPPORTED' => 'Ошибка: Создание спрайтов невозможно: функция  imagecreatetruecolor не может быть загружена',
    'LBL_SPRITES_CREATING_NAMESPACE' => 'Создание пространства имён спрайтов {0}',
    'LBL_SPRITES_PROCESSING_DIR' => 'Обработка папок {0}',
    'LBL_SPRITES_ADDED' => 'Спрайтов добавлено {0}',
    'LBL_SPRITES_EXCLUDING_FILE' => 'Не обработано файлов: {0}',
	
	    //FTS
    'LBL_FTS_TYPE' => 'System Type', ///
    'LBL_FTS_HOST' => 'Host',
    'LBL_FTS_PORT' => 'Port',
    'LBL_FTS_TYPE_HELP' => 'Select the engine to use for full text searching. The system detects the engines that are supported and displays them within this list. Sugar includes built-in support for the elasticsearch engine.',
    'LBL_FTS_HOST_HELP' => 'Enter the name of the host where the full text search engine resides.',
    'LBL_FTS_PORT_HELP' => 'Enter the number of the port where the full text search engine resides.',

    'LBL_AVAILABLE_FTS_MODULES' => 'Select the module(s) for indexing.',
    'LBL_FTS_INDEX_BUTTON' => 'Index',
    'LBL_DELETE_FTS_DATA' => 'Delete existing data when index is performed. Only data in the selected modules will be indexed.',
    'LBL_CONNECT_STATUS' => 'Connection Status',
    'LBL_FTS_SETTINGS_TITLE' => 'Full Text Search Settings',
    'LBL_FTS_TEST' => 'Test',
    'LBL_SAVE_SCHED_BUTTON' => 'Save and Schedule System Index',
    'LBL_SAVE_SCHED_WARNING' => 'Are you sure you would like to perform a system index at this time? The system performance could be impacted while the index is being performed.',
    'LBL_FTS_NO_MODULES' => 'Select at least one module to search.',
    'LBL_FTS_NO_MODULES_FOR_SCHED' => 'Select at least one module to schedule.',
    'LBL_FTS_ADVANCED_LINK' => 'Enable Modules',
    'LBL_FTS_ADVANCED_LINK_HELP' => 'Select the module(s) that users will be able to search against using the Full Text Search.',
    'LBL_FTS_CONN_SUCCESS' => 'The connection was successfully made. You will need to perform a system index for full-text searching to work for the enabled modules and module fields.',
	'LBL_FTS_CONN_SUCCESS_SHORT' => 'A system index operation has been scheduled to run within the next several minutes.',
    'LBL_FTS_CONN_FAILURE_SHORT' => 'Unable to schedule an index operation.',
    'LBL_FTS_PAGE_DESC' => 'To enable full text searching:<br>
1) Select the search engine that will be used<br>
2) Enter the host and port of the search engine<br>
3) Click Test to make sure Sugar can connect to the search engine<br>
4) Click Schedule System Index. Make sure that crontab is set up to run cron.php. This will handle indexing as well as the fallback mechanism when the connection to the search engine is interrupted.', ///
    'LBL_FTS_DISABLED' => 'Full Text Search has been disabled because the system is not able to connect to the search engine.', ///
    'LBL_FTS_CONNECTION_INVALID' => 'The Full Text Search Settings you have entered are invalid and may slow down system performance.  Please change or clear your settings.', ///
    'MSG_RECONNECT_LOTUSLIVE' => 'You are currently not connected to IBM SmartCloud. Connect to IBM SmartCloud within your Profile to be able to access IBM SmartCloud meetings and files.', ///   
	'LBL_REPAIR_UPLOAD_FOLDER' => 'Удаление неиспользуемых файлов из папки "upload"',
    'LBL_REPAIR_UPLOAD_FOLDER_DESC' => 'Удаление файлов, ссылки на которые были удалены из БД; удаление может занять продолжительное время',
    'LBL_TOTAL_FILES' => 'Всего файлов',
    'LBL_REMOVED_FILES' => 'Удалено файлов',
	
	);

//Suite***************


$mod_strings['LBL_UPDATE_QUICKCRM_TITLE'] = "Настройка QuickCRM"; 
$mod_strings['LBL_UPDATE_QUICKCRM'] = "Настройка приложения для работы через мобильные устройства";
$mod_strings['LBL_QUICKCRM'] = 'QuickCRM Mobile';
$mod_strings['LBL_CONFIG_QUICKCRM_TITLE'] = "Configuration of QuickCRM Mobile";
$mod_strings['LBL_CONFIG_QUICKCRM'] = "Definition of visible modules and fields";
$mod_strings['LBL_UPDATE_MSG'] = '<strong>Приложение настроено для работы через мобильные устройства.</strong><br/> Мобильная версия доступна по ссылке:';
$mod_strings['LBL_ERR_DIR_MSG'] = 'Некоторые файлы не могут быть созданы. Проверьте права доступа для: '; 




    
$mod_strings['LBL_RESCHEDULE_REBUILD'] = 'Восстановить отложенные звонки';
$mod_strings['LBL_RESCHEDULE_REBUILD_DESC'] = 'Восстановление модуля отложенных звонков';
$mod_strings['LBL_RESCHEDULE_ADMIN'] = 'Отложенные звонки';
$mod_strings['LBL_RESCHEDULE_ADMIN_DESC'] = 'Настройка отложенных звонков';
$mod_strings['LBL_REPAIR_RESCHEDULE_DONE'] = 'Отложенные звонки успешно восстановлены';
$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';






$mod_strings['LBL_JJWG_MAPS_ADMIN_HEADER'] = 'Карты Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DESC'] = 'Управление геокодированием, тестирование геокодирования, просмотр результатов геокодирования, настройка параметров карт';
$mod_strings['LBL_JJWG_MAPS_ADMIN_CONFIG_TITLE'] = 'Настройка карт Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_CONFIG_DESC'] = 'Настройка параметров карт Google';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODED_COUNTS_TITLE'] = 'Результаты геокодирования';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODED_COUNTS_DESC'] = 'Просмотр статистики геокодирования, данные по каждому модулю сгруппированы в зависимости от полученных результатов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DONATE_TITLE'] = 'Поддержка проекта';
$mod_strings['LBL_JJWG_MAPS_ADMIN_DONATE_DESC'] = ' ';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODE_ADDRESSES_TITLE'] = 'Геокодирование адресов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODE_ADDRESSES_DESC'] = 'Геокодирование адресов системы, этот процесс может занять продолжительное время!';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODING_TEST_TITLE'] = 'Тестирование геокодирования';
$mod_strings['LBL_JJWG_MAPS_ADMIN_GEOCODING_TEST_DESC'] = 'Запуск геокодирования введённого адреса с детальным просмотром результатов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_ADDRESS_CACHE_TITLE'] = 'Кэш адресов';
$mod_strings['LBL_JJWG_MAPS_ADMIN_ADDRESS_CACHE_DESC'] = 'Доступ к кэшу адресов. Обратите внимание: это только кеш!';



$mod_strings['LBL_MANAGE_SECURITYGROUPS_TITLE'] = 'Создание Групп пользователей';
$mod_strings['LBL_MANAGE_SECURITYGROUPS'] = 'Создание Групп пользователей и включение в них Пользователей и Ролей';

$mod_strings['LBL_CONFIG_SECURITYGROUPS_TITLE'] = 'Управление Группами пользователей';
$mod_strings['LBL_CONFIG_SECURITYGROUPS'] = 'Настройка Групп пользователей';
$mod_strings['LBL_SECURITYGROUPS'] = 'Security Suite';
$mod_strings['LBL_SECURITYGROUPS_UPGRADE_INFO_TITLE'] = "Upgrade and General Info"; ///
$mod_strings['LBL_SECURITYGROUPS_INFO_TITLE'] = "Security Suite Info"; ///
$mod_strings['LBL_SECURITYGROUPS_INFO'] = "General information";
$mod_strings['LBL_SECURITYGROUPS_DASHLETPUSH_TITLE'] = "Push Message Dashlet"; ///
$mod_strings['LBL_SECURITYGROUPS_DASHLETPUSH'] = "Push the Message Dashlet to the Home page for all users. This process may take some time to complete depending on the number of users"; ///
$mod_strings['LBL_SECURITYGROUPS_HOOKUP_TITLE'] = "Hookup Module"; ///
$mod_strings['LBL_SECURITYGROUPS_HOOKUP'] = "Hookup Security Suite to work with your custom modules"; ///
$mod_strings['LBL_SECURITYGROUPS_SUGAROUTFITTERS_TITLE'] = "SugarOutfitters";
$mod_strings['LBL_SECURITYGROUPS_SUGAROUTFITTERS'] = "Grab the latest version of SecuritySuite and find other SugarCRM modules, themes, and integrations along with reviews, docs, support, and community verified versions.";





/**
 *
 * @package Advanced OpenPortal
 * @copyright SalesAgility Ltd http://www.salesagility.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
 * along with this program; if not, see http://www.gnu.org/licenses
 * or write to the Free Software Foundation,Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA 02110-1301  USA
 *
 * @author Salesagility Ltd <support@salesagility.com>
 */
$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';
$mod_strings['LBL_AOP_ADMIN_MANAGE_AOP'] = 'Настройки портала';
$mod_strings['LBL_AOP_JOOMLA_SETTINGS'] = 'Настройка портала';
$mod_strings['LBL_AOP_JOOMLA_URL'] = 'Joomla URL';
$mod_strings['LBL_AOP_JOOMLA_ACCESS_KEY'] = 'Ключ доступа к Joomla';
$mod_strings['LBL_AOP_CASE_ASSIGNMENT'] = 'Распределение обращений';
$mod_strings['LBL_AOP_DISTRIBUTION_METHOD'] = 'Метод распределения';
$mod_strings['LBL_AOP_ASSIGNMENT_USER'] = 'Пользователь';

$mod_strings['LBL_AOP_EMAIL_SETTINGS'] = 'Настройка шаблонов E-mail для обращений';
$mod_strings['LBL_AOP_CONTACT_EMAIL_TEMPLATE'] = 'Шаблон письма при ответе контактам';
$mod_strings['LBL_AOP_USER_EMAIL_TEMPLATE'] = 'Шаблон письма при ответе пользователям';
$mod_strings['LBL_AOP_CASE_CREATION_EMAIL_TEMPLATE'] = 'Шаблон письма при создании обращения';
$mod_strings['LBL_AOP_CASE_CLOSURE_EMAIL_TEMPLATE'] = 'Шаблон письма при создании обращения';
$mod_strings['LBL_AOP_CASE_REMINDER_EMAIL_TEMPLATE'] = 'Шаблон письма для напоминаний';
$mod_strings['LBL_AOP_JOOMLA_ACCOUNT_CREATION_EMAIL_TEMPLATE'] = 'Шаблон письма при создании учётной записи Joomla';

$mod_strings['LBL_AOP_BUSINESS_HOURS_SETTINGS'] = 'Business Hours';
$mod_strings['LBL_AOP_OPENING_DAYS'] = 'Opening Days';
$mod_strings['LBL_AOP_OPENING_HOURS'] = 'Opening Hours';
$mod_strings['LBL_AOP_CLOSING_HOURS'] = 'Closing Hours';
$mod_strings['LBL_SUPPORT_FROM_ADDRESS'] = 'В качестве адреса отправителя указывать';
$mod_strings['LBL_SUPPORT_FROM_NAME'] = 'В качестве имени отправителя указывать';
$mod_strings['LBL_CREATE_EMAIL_TEMPLATE']  = 'Создать';
$mod_strings['LBL_EDIT_EMAIL_TEMPLATE']  = 'Изменить';
$mod_strings['LBL_AOP_SINGLE_USER']  = 'Указанный пользователь';
$mod_strings['LBL_AOP_SETTINGS'] = 'Настройка портала';

$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';
$mod_strings['LBL_AOS_ADMIN_CONTRACT_SETTINGS'] = 'Параметры договоров';
$mod_strings['LBL_AOS_ADMIN_CONTRACT_RENEWAL_REMINDER'] = 'Период действия договора';
$mod_strings['LBL_AOS_ADMIN_MANAGE_AOS'] = 'Параметры модулей продаж';
$mod_strings['LBL_AOS_ADMIN_INVOICE_SETTINGS'] = 'Параметры счетов';
$mod_strings['LBL_AOS_ADMIN_INITIAL_INVOICE_NUMBER'] = 'Начинать нумерацию с';
$mod_strings['LBL_AOS_ADMIN_QUOTE_SETTINGS'] = 'Параметры предложений';
$mod_strings['LBL_AOS_ADMIN_INITIAL_QUOTE_NUMBER'] = 'Начинать нумерацию с';
$mod_strings['LBL_AOS_ADMIN_LINE_ITEM_SETTINGS'] = 'Настройка позиций в бланках';
$mod_strings['LBL_AOS_ADMIN_ENABLE_LINE_ITEM_GROUPS'] = 'Возможность группировки позиций';
$mod_strings['LBL_AOS_ADMIN_ENABLE_LINE_ITEM_TOTAL_TAX'] = 'Включать НДС в сумму<br>(для каждой позиции)';
$mod_strings['LBL_AOS_SETTINGS'] = 'Настройка модулей продаж';
$mod_strings['LBL_AOS_PRODUCTS'] = 'AOS Products';
$mod_strings['LBL_AOS_EDIT'] = 'edit';
$mod_strings['LBL_AOS_DAYS'] = 'дней';
$mod_strings['LBL_CHANGE_SETTINGS'] = 'Настройка параметров договоров, счетов, предложений';

$mod_strings['LBL_COLOUR_SETTINGS'] = 'Настройка темы';
$mod_strings['LBL_COLOUR_DESC'] = 'Настройка цветовой схемы и параметров темы';
$mod_strings['LBL_COLOUR_ADMIN_INTRO'] = 'Настройка цветовой схемы и параметров темы.'.' <strong>Обратите внимание:</strong> Для отображения сохранённых изменений рекомендуется обновить страницу сочетанием клавиш Ctrl + F5.';

$mod_strings['LBL_COLOUR_ADMIN_CUSTOM'] = 'Custom code config';///
$mod_strings['LBL_COLOUR_ADMIN_MENU'] = 'Настройка цветовой схемы меню';
$mod_strings['LBL_COLOUR_ADMIN_PAGE'] = 'Настройка цветовой схемы страниц';
$mod_strings['LBL_COLOUR_ADMIN_PAGEHEADER'] = 'Цвет заголовков на странице';
$mod_strings['LBL_COLOUR_ADMIN_PAGELINK'] = 'Цвет гиперссылок на странице';
$mod_strings['LBL_COLOUR_ADMIN_DASHLET'] = 'Настройка цветовой схемы дашлетов';
$mod_strings['LBL_COLOUR_ADMIN_BUTTON'] = 'Настройка цветовой схемы кнопок';

$mod_strings['LBL_COLOUR_ADMIN_BASE'] = 'Основной цвет меню: ';
$mod_strings['LBL_COLOUR_ADMIN_TOPGR'] = 'Градиент, верхний цвет меню: ';
$mod_strings['LBL_COLOUR_ADMIN_BTMGR'] = 'Градиент, нижний цвет меню: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUBRD'] = 'Цвет границы меню: ';
$mod_strings['LBL_COLOUR_ADMIN_VISITED'] = 'Цвет надписи у просмотренных закладок: ';
$mod_strings['LBL_COLOUR_ADMIN_MENUHOVER'] = 'Цвет меню при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_DDLINK'] = 'Цвет надписей выпадающего меню: ';
$mod_strings['LBL_COLOUR_ADMIN_DDMENU'] = 'Цвет фона выпадающего меню: ';

$mod_strings['LBL_COLOUR_ADMIN_MENUFONT'] = 'Цвет надписи закладок';
$mod_strings['LBL_COLOUR_ADMIN_MENULNKHVR'] = 'Цвет надписи закладок при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNTOP'] = 'Градиент, верхний цвет кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNMID1'] = 'Градиент, верхний средний цвет кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNMID2'] = 'Градиент, нижний средний цвет кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNBTM'] = 'Градиент, нижний цвет кнопки: ';
$mod_strings['LBL_COLOUR_ADMIN_BTNHOVER'] = 'Цвет кнопки при наведении курсора: ';
$mod_strings['LBL_COLOUR_ADMIN_DASHHEAD'] = 'Цвет заголовка дашлета: ';

$mod_strings['LBL_COLOUR_ADMIN_TABS'] = 'Настройка закладок модулей';
$mod_strings['LBL_COLOUR_ADMIN_TABSNUM'] = 'Количество отображаемых закладок модулей: ';

$mod_strings['LBL_DEFAULT_ADMIN_DASHLET'] = 'Настройка колонок дашлетов';
$mod_strings['LBL_DASHLET_COLUMNS'] = 'Количество колонок для расположения дашлетов: ';

$mod_strings['LBL_SALESAGILITY_ADMIN'] = 'OpenAdmin';
$mod_strings['LBL_AOD_ADMIN_MANAGE_AOD'] = 'Настройка полнотекстового поиска';
$mod_strings['LBL_AOD_ENABLE'] = 'Включить полнотекстовый поиск';
$mod_strings['LBL_AOD_SETTINGS'] = 'Настройка полнотекстового поиска';

?>