<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

/**
 * ListView - list of many objects
 * @api
 */
class ListViewSubPanel extends ListView
{
    public function __construct() {
    }


    function setDataArray($value) {

        parent::setDataArray($value); // TODO: Change the autogenerated stub
    }

    function processListViewMulti($seed, $xTemplateSection, $html_varName) {

        parent::processListViewMulti($seed, $xTemplateSection, $html_varName); // TODO: Change the autogenerated stub
    }

    function processListView($seed, $xTemplateSection, $html_varName) {

        return parent::processListView($seed, $xTemplateSection, $html_varName); // TODO: Change the autogenerated stub
    }

    function process_dynamic_listview($source_module, $sugarbean, $subpanel_def) {

        return parent::process_dynamic_listview($source_module, $sugarbean, $subpanel_def); // TODO: Change the autogenerated stub
    }

    function process_dynamic_listview_rows($data, $parent_data, $xtemplateSection, $html_varName, $subpanel_def) {

        parent::process_dynamic_listview_rows($data, $parent_data, $xtemplateSection, $html_varName, $subpanel_def); // TODO: Change the autogenerated stub
    }

    function setDisplayHeaderAndFooter($bool) {

        parent::setDisplayHeaderAndFooter($bool); // TODO: Change the autogenerated stub
    }

    function setRecordsPerPage($count) {

        parent::setRecordsPerPage($count); // TODO: Change the autogenerated stub
    }

    function setHeaderTitle($value) {

        parent::setHeaderTitle($value); // TODO: Change the autogenerated stub
    }

    function setHeaderText($value) {

        parent::setHeaderText($value); // TODO: Change the autogenerated stub
    }

    function setXTemplatePath($value) {

        parent::setXTemplatePath($value); // TODO: Change the autogenerated stub
    }

    function initNewXTemplate($XTemplatePath, $modString, $imagePath = null) {

        parent::initNewXTemplate($XTemplatePath, $modString, $imagePath); // TODO: Change the autogenerated stub
    }

    function getOrderBy($varName, $defaultOrderBy = '', $force_sortorder = '') {

        return parent::getOrderBy($varName, $defaultOrderBy, $force_sortorder); // TODO: Change the autogenerated stub
    }

    function setQuery($where, $limit, $orderBy, $varName, $allowOrderByOveride = true) {

        return parent::setQuery($where, $limit, $orderBy, $varName, $allowOrderByOveride); // TODO: Change the autogenerated stub
    }

    function displayArrow() {

        parent::displayArrow(); // TODO: Change the autogenerated stub
    }

    function setTheme($theme) {

        parent::setTheme($theme); // TODO: Change the autogenerated stub
    }

    function setAppStrings($app_strings) {

        parent::setAppStrings($app_strings); // TODO: Change the autogenerated stub
    }

    function setModStrings($mod_strings) {

        parent::setModStrings($mod_strings); // TODO: Change the autogenerated stub
    }

    function setImagePath($image_path) {

        parent::setImagePath($image_path); // TODO: Change the autogenerated stub
    }

    function setCurrentModule($currentModule) {

        parent::setCurrentModule($currentModule); // TODO: Change the autogenerated stub
    }

    function createXTemplate() {

        parent::createXTemplate(); // TODO: Change the autogenerated stub
    }

    function setXTemplate($newXTemplate) {

        parent::setXTemplate($newXTemplate); // TODO: Change the autogenerated stub
    }

    function getXTemplate() {

        return parent::getXTemplate(); // TODO: Change the autogenerated stub
    }

    function xTemplateAssign($name, $value) {

        parent::xTemplateAssign($name, $value); // TODO: Change the autogenerated stub
    }

    function getOffset($localVarName) {

        return parent::getOffset($localVarName); // TODO: Change the autogenerated stub
    }

    function setOffset($localVarName, $value) {

        parent::setOffset($localVarName, $value); // TODO: Change the autogenerated stub
    }

    function setSessionVariable($localVarName, $varName, $value) {

        parent::setSessionVariable($localVarName, $varName, $value); // TODO: Change the autogenerated stub
    }

    function setUserVariable($localVarName, $varName, $value) {

        return parent::setUserVariable($localVarName, $varName, $value); // TODO: Change the autogenerated stub
    }

    function getSessionVariable($localVarName, $varName) {

        return parent::getSessionVariable($localVarName, $varName); // TODO: Change the autogenerated stub
    }

    function getUserVariable($localVarName, $varName) {

        return parent::getUserVariable($localVarName, $varName); // TODO: Change the autogenerated stub
    }

    function calculateSortOrder($sortOrderList) {

        return parent::calculateSortOrder($sortOrderList); // TODO: Change the autogenerated stub
    }

    function getSessionVariableName($localVarName, $varName) {

        return parent::getSessionVariableName($localVarName, $varName); // TODO: Change the autogenerated stub
    }

    function processSugarBean($xtemplateSection, $html_varName, $seed) {

        return parent::processSugarBean($xtemplateSection, $html_varName, $seed); // TODO: Change the autogenerated stub
    }

    function processUnionBeans($sugarbean, $subpanel_def, $html_var = 'CELL') {

        return parent::processUnionBeans($sugarbean, $subpanel_def, $html_var); // TODO: Change the autogenerated stub
    }

    function getBaseURL($html_varName) {

        return parent::getBaseURL($html_varName); // TODO: Change the autogenerated stub
    }

    function processListNavigation($xtemplateSection, $html_varName, $current_offset, $next_offset, $previous_offset, $row_count, $sugarbean = null, $subpanel_def = null, $col_count = 20) {

        parent::processListNavigation($xtemplateSection, $html_varName, $current_offset, $next_offset, $previous_offset, $row_count, $sugarbean, $subpanel_def, $col_count); // TODO: Change the autogenerated stub
    }

    function processOrderBy($html_varName) {

        return parent::processOrderBy($html_varName); // TODO: Change the autogenerated stub
    }

    function getAdditionalHeader() {

        parent::getAdditionalHeader(); // TODO: Change the autogenerated stub
    }

    function processListRows($data, $xtemplateSection, $html_varName) {

        parent::processListRows($data, $xtemplateSection, $html_varName); // TODO: Change the autogenerated stub
    }

    function getLayoutManager() {

        return parent::getLayoutManager(); // TODO: Change the autogenerated stub
    }

    function process_dynamic_listview_header($source_module, $subpanel_def, $html_var = 'CELL') {

        parent::process_dynamic_listview_header($source_module, $subpanel_def, $html_var); // TODO: Change the autogenerated stub
    }

    function processListViewTwo($seed, $xTemplateSection, $html_varName) {

        parent::processListViewTwo($seed, $xTemplateSection, $html_varName); // TODO: Change the autogenerated stub
    }

    function getArrowStart() {

        return parent::getArrowStart(); // TODO: Change the autogenerated stub
    }

    function getArrowUpDownStart($upDown) {

        return parent::getArrowUpDownStart($upDown); // TODO: Change the autogenerated stub
    }

    function getArrowEnd() {

        return parent::getArrowEnd(); // TODO: Change the autogenerated stub
    }

    function getArrowUpDownEnd($upDown) {

        return parent::getArrowUpDownEnd($upDown); // TODO: Change the autogenerated stub
    }

    function getArrowImageSize() {

        return parent::getArrowImageSize(); // TODO: Change the autogenerated stub
    }

    function getArrowUpDownImageSize($upDown) {

        return parent::getArrowUpDownImageSize($upDown); // TODO: Change the autogenerated stub
    }

    function getOrderByInfo($html_varName) {

        return parent::getOrderByInfo($html_varName); // TODO: Change the autogenerated stub
    }

    function processSortArrows($html_varName) {

        parent::processSortArrows($html_varName); // TODO: Change the autogenerated stub
    }

    function loadListFieldDefs(&$subpanel_fields, &$child_focus) {

        parent::loadListFieldDefs($subpanel_fields, $child_focus); // TODO: Change the autogenerated stub
    }

    function unique_id() {

        return parent::unique_id(); // TODO: Change the autogenerated stub
    }

    function setLocalSessionVariable($localVarName, $varName, $value) {

        parent::setLocalSessionVariable($localVarName, $varName, $value); // TODO: Change the autogenerated stub
    }

    function getLocalSessionVariable($localVarName, $varName) {

        return parent::getLocalSessionVariable($localVarName, $varName); // TODO: Change the autogenerated stub
    }

    function setAdditionalDetails($value = true, $function = '') {

        parent::setAdditionalDetails($value, $function); // TODO: Change the autogenerated stub
    }

}
?>
