<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
//DON'T CONVERT THESE THEY ARE MAPPINGS
'db_last_name' => 'LBL_LIST_LAST_NAME',
'db_first_name' => 'LBL_LIST_FIRST_NAME',
'db_title' => 'LBL_LIST_TITLE',
'db_email1' => 'LBL_LIST_EMAIL_ADDRESS',
'db_account_name' => 'LBL_LIST_ACCOUNT_NAME',
'db_email2' => 'LBL_LIST_EMAIL_ADDRESS',

//END DON'T CONVERT
'ERR_DELETE_RECORD' => 'Перед удалением предварительного контакта должен быть определён номер записи.' ,
'LBL_ACCOUNT_DESCRIPTION'=> 'Описание контрагента' ,
'LBL_ACCOUNT_ID'=> 'ID контрагента' ,
'LBL_ACCOUNT_NAME' => 'Контрагент:' ,
'LBL_ACTIVITIES_SUBPANEL_TITLE'=> 'Мероприятия' ,
'LBL_ADD_BUSINESSCARD' => 'Добавить визитку' ,
'LBL_ADDRESS_INFORMATION' => 'Адресная информация' ,
'LBL_ALT_ADDRESS_CITY' => 'Другой адрес - город' ,
'LBL_ALT_ADDRESS_COUNTRY' => 'Другой адрес - страна' ,
'LBL_ALT_ADDRESS_POSTALCODE' => 'Другой адрес - индекс' ,
'LBL_ALT_ADDRESS_STATE' => 'Другой адрес - область' ,
'LBL_ALT_ADDRESS_STREET_2' => 'Другой адрес улицы 2' ,
'LBL_ALT_ADDRESS_STREET_3' => 'Другой адрес улицы 3' ,
'LBL_ALT_ADDRESS_STREET' => 'Другой адрес - улица' ,
'LBL_ALTERNATE_ADDRESS' => 'Другой адрес:' ,
'LBL_ALT_ADDRESS' => 'Другой адрес:' ,
'LBL_ANY_ADDRESS' => 'Любой адрес:' ,
'LBL_ANY_EMAIL' => 'Любой E-mail:' ,
'LBL_ANY_PHONE' => 'Любой тел.:' ,
'LBL_ASSIGNED_TO_NAME' => 'Ответственный(ая)' ,
'LBL_ASSIGNED_TO_ID' => 'Ответственный(ая):',
'LBL_BACKTOLEADS' => 'Вернуться к предварительным контактам' ,
'LBL_BUSINESSCARD' => 'Преобразовать предв. контакт' ,
'LBL_CITY' => 'Город:' ,
'LBL_CONTACT_ID' => 'Идентификатор контакта' ,
'LBL_CONTACT_INFORMATION' => 'Основная информация' ,
'LBL_CONTACT_NAME' => 'ФИО:' ,
'LBL_CONTACT_OPP_FORM_TITLE' => 'Предварительные контакты:' ,
'LBL_CONTACT_ROLE' => 'Роль:' ,
'LBL_CONTACT' => 'Предварительный контакт:' ,
'LBL_CONVERTED_ACCOUNT'=> 'Преобразован в контрагента:' ,
'LBL_CONVERTED_CONTACT' => 'Преобразован в контакт:' ,
'LBL_CONVERTED_OPP'=> 'Преобразован в сделку:' ,
'LBL_CONVERTED'=> 'Преобразован' ,
'LBL_CONVERTLEAD_BUTTON_KEY' => 'V' ,
'LBL_CONVERTLEAD_TITLE' => 'Преобразовать предв. контакт' ,
'LBL_CONVERTLEAD' => 'Преобразовать предв. контакт' ,
'LBL_CONVERTLEAD_WARNING' => 'Предупреждение: Статус данного предварительного контакта установлен в значение "Преобразован". Возможно, соответствующие контакт и/или контрагент уже были созданы. Если вы хотите продолжить преобразование, нажмите на кнопку "Сохранить", в противном случае нажмите на кнопку "Отказаться".',
'LBL_CONVERTLEAD_WARNING_INTO_RECORD' => ' Возможный контакт ',
'LBL_COUNTRY' => 'Страна:' ,
'LBL_CREATED_NEW' => 'Создан новый ',
'LBL_CREATED_ACCOUNT' => 'Создан новый контрагент' ,
'LBL_CREATED_CALL' => 'Создан новый звонок' ,
'LBL_CREATED_CONTACT' => 'Создан новый контакт' ,
'LBL_CREATED_MEETING' => 'Создана новая встреча' ,
'LBL_CREATED_OPPORTUNITY' => 'Создана новая сделка' ,
'LBL_DEFAULT_SUBPANEL_TITLE' => 'Предварительные контакты' ,
'LBL_DEPARTMENT' => 'Отдел:' ,
'LBL_DESCRIPTION_INFORMATION' => 'Описание' ,
'LBL_DESCRIPTION' => 'Описание:' ,
'LBL_DO_NOT_CALL' => 'Не звонить:' ,
'LBL_DUPLICATE' => 'Дублирующиеся предварительные контакты' ,
'LBL_EMAIL_ADDRESS' => 'E-mail:' ,
'LBL_EMAIL_OPT_OUT' => 'Не писать на E-mail' ,
'LBL_EXISTING_ACCOUNT' => 'Использован существующий контрагент' ,
'LBL_EXISTING_CONTACT' => 'Использован существующий контакт' ,
'LBL_EXISTING_OPPORTUNITY' => 'Использована существующая сделка' ,
'LBL_FAX_PHONE' => 'Факс:' ,
'LBL_FIRST_NAME' => 'Имя:' ,
'LBL_FULL_NAME' => 'Полное имя:' ,
'LBL_HISTORY_SUBPANEL_TITLE'=> 'История' ,
'LBL_HOME_PHONE' => 'Тел. (дом.) :' ,
'LBL_IMPORT_VCARD' => 'Импортирование vCard' ,
'LBL_VCARD' => 'vCard' ,
'LBL_IMPORT_VCARDTEXT' => 'Автоматическое создание новой записи предварительного контакта при импорте файла vCard.' ,
'LBL_INVALID_EMAIL'=> 'Неверный E-mail:' ,
'LBL_INVITEE' => 'Отчёты' ,
'LBL_LAST_NAME' => 'Фамилия:' ,
'LBL_LEAD_SOURCE_DESCRIPTION' => 'Описание источника предв. контакта:' ,
'LBL_LEAD_SOURCE' => 'Источник предв. контакта:' ,
'LBL_LIST_ACCEPT_STATUS' => 'Статус',
'LBL_LIST_ACCOUNT_NAME' => 'Контрагент' ,
'LBL_LIST_CONTACT_NAME' => 'ФИО предв. контакта' ,
'LBL_LIST_CONTACT_ROLE' => 'Роль' ,
'LBL_LIST_DATE_ENTERED' => 'Дата создания' ,
'LBL_LIST_EMAIL_ADDRESS' => 'E-mail' ,
'LBL_LIST_FIRST_NAME' => 'Имя' ,
'LBL_VIEW_FORM_TITLE' => 'Просмотр предварительного контакта',
'LBL_LIST_FORM_TITLE' => 'Список предварительных контактов' ,
'LBL_LIST_LAST_NAME' => 'Фамилия' ,
'LBL_LIST_LEAD_SOURCE_DESCRIPTION' => 'Описание источника предварительного контакта' ,
'LBL_LIST_LEAD_SOURCE' => 'Источник предварительных контактов' ,
'LBL_LIST_MY_LEADS' => 'Мои предварительные контакты' ,
'LBL_LIST_NAME' => 'ФИО' ,
'LBL_LIST_PHONE' => 'Тел.' ,
'LBL_LIST_REFERED_BY' => 'Передан от' ,
'LBL_LIST_STATUS' => 'Статус' ,
'LBL_LIST_TITLE' => 'Должность' ,
'LBL_MOBILE_PHONE' => 'Тел. (моб.) :' ,
'LBL_MODULE_NAME' => 'Предварит. контакты' ,
'LBL_MODULE_TITLE' => 'Предварительные контакты - ГЛАВНАЯ' ,
'LBL_NAME' => 'ФИО:' ,
'LBL_NEW_FORM_TITLE' => 'Новый предв. контакт' ,
'LBL_NEW_PORTAL_PASSWORD' => 'Новый пароль портала:' ,
'LBL_OFFICE_PHONE' => 'Тел. (раб.) :' ,
'LBL_OPP_NAME' => 'Название сделки:' ,
'LBL_OPPORTUNITY_AMOUNT' => 'Сумма сделки:' ,
'LBL_OPPORTUNITY_ID'=> 'ID сделки' ,
'LBL_OPPORTUNITY_NAME' => 'Название сделки:' ,
'LBL_OTHER_EMAIL_ADDRESS' => 'Другой E-mail:' ,
'LBL_OTHER_PHONE' => 'Другой тел.:' ,
'LBL_PHONE' => 'Тел.:' ,
'LBL_PORTAL_ACTIVE' => 'Портал включён:' ,
'LBL_PORTAL_APP'=> 'Портальное приложение' ,
'LBL_PORTAL_INFORMATION' => 'Портальная информация' ,
'LBL_PORTAL_NAME' => 'Название портала:' ,
'LBL_PORTAL_PASSWORD_ISSET' => 'Портальный пароль установлен:' ,
'LBL_POSTAL_CODE' => 'Индекс:' ,
'LBL_STREET' => 'Улица',
'LBL_PRIMARY_ADDRESS_CITY' => 'Основной адрес - город' ,
'LBL_PRIMARY_ADDRESS_COUNTRY' => 'Основной адрес - страна' ,
'LBL_PRIMARY_ADDRESS_POSTALCODE' => 'Основной адрес - индекс' ,
'LBL_PRIMARY_ADDRESS_STATE' => 'Основной адрес - область' ,
'LBL_PRIMARY_ADDRESS_STREET_2'=> 'Основной адрес - улица 2' ,
'LBL_PRIMARY_ADDRESS_STREET_3'=> 'Основной адрес - улица 3' ,
'LBL_PRIMARY_ADDRESS_STREET' => 'Основной адрес - улица' ,
'LBL_PRIMARY_ADDRESS' => 'Основной адрес:' ,
'LBL_REFERED_BY' => 'Передан от:' ,
'LBL_REPORTS_TO_ID'=> 'Руководитель (ID)' ,
'LBL_REPORTS_TO' => 'Руководитель:' ,
'LBL_REPORTS_FROM' => 'Подчинённый:',
'LBL_SALUTATION' => 'Приветствие' ,
'LBL_MODIFIED'=> 'Изменено',
'LBL_MODIFIED_ID' => 'Изменено(ID)',
'LBL_CREATED'=> 'Создано',
'LBL_CREATED_ID' => 'Создано(ID)',
'LBL_SEARCH_FORM_TITLE' => 'Поиск предварительных контактов' ,
'LBL_SELECT_CHECKED_BUTTON_LABEL' => 'Выбрать отмеченные предварительные контакты' ,
'LBL_SELECT_CHECKED_BUTTON_TITLE' => 'Выбрать отмеченные предварительные контакты' ,
'LBL_STATE' => 'Область:' ,
'LBL_STATUS_DESCRIPTION' => 'Описание статуса:' ,
'LBL_STATUS' => 'Статус:' ,
'LBL_TITLE' => 'Должность:' ,
'LNK_IMPORT_VCARD' => 'Создать предв. контакт из vCard' ,
'LNK_LEAD_LIST' => 'Предв. контакты' ,
'LNK_NEW_ACCOUNT' => 'Создать контрагента' ,
'LNK_NEW_APPOINTMENT' => 'Назначить встречу/звонок' ,
'LNK_NEW_CONTACT' => 'Создать контакт' ,
'LNK_NEW_LEAD' => 'Создать предв. контакт' ,
'LNK_NEW_NOTE' => 'Создать заметку' ,
'LNK_NEW_TASK' => 'Создать задачу',
'LNK_NEW_CASE' => 'Создать обращение',
'LNK_NEW_CALL' => 'Назначить звонок',
'LNK_NEW_MEETING' => 'Назначить встречу',
'LNK_NEW_OPPORTUNITY' => 'Создать сделку' ,
'LNK_SELECT_ACCOUNTS' => ' <b>ИЛИ</b> выбрать существующего контрагента',
'LNK_SELECT_CONTACTS' => ' <b>ИЛИ</b> выбрать существующий контакт',
'NTC_COPY_ALTERNATE_ADDRESS' => 'Копировать дополнительный адрес в основной' ,
'NTC_COPY_PRIMARY_ADDRESS' => 'Копировать основной адрес в дополнительный' ,
'NTC_DELETE_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись?' ,
'NTC_OPPORTUNITY_REQUIRES_ACCOUNT' => 'Сделка должна быть связана с контрагентом.\n Пожалуйста, создайте нового контрагента или выберите из списка уже существующих.' ,
'NTC_REMOVE_CONFIRMATION' => 'Вы уверены, что хотите удалить этот предварительный контакт из данного обращения?' ,
'NTC_REMOVE_DIRECT_REPORT_CONFIRMATION' => 'Вы уверены, что хотите удалить эту запись из личных отчётов?' ,
'LBL_CAMPAIGN_LIST_SUBPANEL_TITLE'=> 'Маркетинговые кампании' ,
'LBL_TARGET_OF_CAMPAIGNS'=> 'Успешная маркет. кампания:' ,
'LBL_TARGET_BUTTON_LABEL'=> 'Targeted' ,
'LBL_TARGET_BUTTON_TITLE'=> 'Targeted' ,
'LBL_TARGET_BUTTON_KEY'=> 'T' ,
'LBL_CAMPAIGN_ID'=> 'ID маркет. кампании',
'LBL_CAMPAIGN' => 'Маркет. кампания:',
'LBL_LIST_ASSIGNED_TO_NAME' => 'Ответственный(ая)',
'LBL_PROSPECT_LIST' => 'Список адресатов',
'LBL_CAMPAIGN_LEAD' => 'Маркет. кампании',
'LBL_BIRTHDATE' => 'День рождения:',
'LBL_THANKS_FOR_SUBMITTING_LEAD' => 'Благодарим Вас за отправку регистрационных данных.',
'LBL_SERVER_IS_CURRENTLY_UNAVAILABLE' => 'Извините, но в данный момент сервер недоступен. Попробуйте ещё раз немного позже.',
'LBL_ASSISTANT_PHONE' => 'Тел. помощника',
'LBL_ASSISTANT' => 'Помощник',
'LBL_REGISTRATION' => 'Регистрация',
'LBL_MESSAGE' => 'Please enter your information below. Information and/or an account will be created for you pending approval.', ///
'LBL_SAVED' => 'Thank you for registering. Your account will be created and someone will contact you shortly.', ///
'LBL_CLICK_TO_RETURN' => 'Return to Portal', ///
'LBL_CREATED_USER' => 'Создано',
'LBL_MODIFIED_USER' => 'Изменено',
'LBL_CAMPAIGNS' => 'Маркет. кампании',
'LBL_CAMPAIGNS_SUBPANEL_TITLE' => 'Маркет. кампании',
'LBL_CONVERT_MODULE_NAME' => 'Модуль',
'LBL_CONVERT_REQUIRED' => 'Требуется',
'LBL_CONVERT_SELECT' => 'Разрешить выбор',
'LBL_CONVERT_COPY' => 'Копировать данные',
'LBL_CONVERT_EDIT' => 'Править',
'LBL_CONVERT_DELETE' => 'Удалить',
'LBL_CONVERT_ADD_MODULE' => 'Добавить модуль',
'LBL_CREATE' => 'Создать',
'LBL_SELECT' => ' <b>ИЛИ</b> выбрать',
'LBL_WEBSITE' => 'Веб-сайт',
'LNK_IMPORT_LEADS' => 'Импорт предв. контактов',
'LBL_NOTICE_OLD_LEAD_CONVERT_OVERRIDE' => 'Notice: The current Convert Lead screen contains custom fields. When you customize the Convert Lead screen in Studio for the first time, you will need to add custom fields to the layout, as necessary. The custom fields will not automatically appear in the layout, as they did previously.', ///
//Convert lead tooltips
'LBL_MODULE_TIP' => 'Модуль, в котором будет создана новая запись.',
'LBL_REQUIRED_TIP' => 'Необходимые модули должны быть созданы или выбраны до процесса конвертации предварительного контакта.',
'LBL_COPY_TIP'=> 'Если опция отмечена, то данные из полей предварительного контакта будут скопированы в соответствующие поля создаваемых записей.',
'LBL_SELECTION_TIP' => 'Записи других модулей, связанные с модулем "Контакты", могут быть либо созданы в процессе конвертации, либо выбраны из списка уже существующих записей.',
'LBL_EDIT_TIP'=> 'Правка макета страницы конвертации для данного модуля.',
'LBL_DELETE_TIP'=> 'Удаление данного модуля из макета страницы конвертации.',
'LBL_ACTIVITIES_MOVE'   => 'Переместить мероприятия в',
'LBL_ACTIVITIES_COPY'   => 'Копировать мероприятия в',
'LBL_ACTIVITIES_MOVE_HELP'   => "Выберите запись, в которую будут перемещены существующие мероприятия предварительного контакта.<br>Будут перемещены все Задачи, Звонки, Встречи, Заметки и электронные письма.",
'LBL_ACTIVITIES_COPY_HELP'   => "Выберите записи, в которых будут созданы копии существующих мероприятий предварительного контакта.<br>Создаваемые Задачи, Звонки, Встречи, Заметки и электронные письма будут связаны со всеми выбранными записями.",
//For export labels
'LBL_PHONE_HOME' => 'Тел. (дом.)',
'LBL_PHONE_MOBILE' => 'Тел. (моб.)',
'LBL_PHONE_WORK' => 'Тел. (раб.)',
'LBL_PHONE_OTHER' => 'Другой тел.',
'LBL_PHONE_FAX' => 'Факс',
'LBL_CAMPAIGN_ID' => 'ID маркет. кампании',
'LBL_EXPORT_ASSIGNED_USER_NAME' => 'Ответственный(ая)',
'LBL_EXPORT_ASSIGNED_USER_ID' => 'Ответственный(ая)-ID',
'LBL_EXPORT_MODIFIED_USER_ID' => 'Изменено(ID)',
'LBL_EXPORT_CREATED_BY' => 'Создано (ID)',
'LBL_EXPORT_PHONE_MOBILE' => 'Тел. (моб.)',
'LBL_EXPORT_EMAIL2'=> 'Другой E-mail',
'LBL_EDITLAYOUT' => 'Изменить макет' /*for 508 compliance fix*/,
'LBL_ENTERDATE' => 'Укажите дату' /*for 508 compliance fix*/,
'LBL_LOADING' => 'Загрузка' /*for 508 compliance fix*/,
'LBL_EDIT_INLINE' => 'Править' /*for 508 compliance fix*/,
);


?>
