<?php

$popupMeta = [
    'moduleMain' => 'jjwg_Markers',
    'varName' => 'jjwg_Markers',
    'orderBy' => 'jjwg_markers.name',
    'whereClauses' => [
        'name' => 'jjwg_markers.name',
        'city' => 'jjwg_markers.city',
        'state' => 'jjwg_markers.state',
        'country' => 'jjwg_markers.country',
        'marker_image' => 'jjwg_markers.marker_image',
        'assigned_user_name' => 'jjwg_markers.assigned_user_name',
        'date_entered' => 'jjwg_markers.date_entered',
    ],
    'searchInputs' => [
        1 => 'name',
        4 => 'city',
        5 => 'state',
        6 => 'country',
        7 => 'marker_image',
        8 => 'assigned_user_name',
        9 => 'date_entered',
    ],
    'searchdefs' => [
        'name' => [
            'type' => 'name',
            'label' => 'LBL_NAME',
            'width' => '10%',
            'name' => 'name',
        ],
        'city' => [
            'type' => 'varchar',
            'label' => 'LBL_CITY',
            'width' => '10%',
            'name' => 'city',
        ],
        'state' => [
            'type' => 'varchar',
            'label' => 'LBL_STATE',
            'width' => '10%',
            'name' => 'state',
        ],
        'country' => [
            'type' => 'varchar',
            'label' => 'LBL_COUNTRY',
            'width' => '10%',
            'name' => 'country',
        ],
        'marker_image' => [
            'type' => 'enum',
            'studio' => 'visible',
            'label' => 'LBL_MARKER_IMAGE',
            'sortable' => false,
            'width' => '10%',
            'name' => 'marker_image',
        ],
        'assigned_user_name' => [
            'link' => 'assigned_user_link',
            'type' => 'relate',
            'label' => 'LBL_ASSIGNED_TO_NAME',
            'width' => '10%',
            'name' => 'assigned_user_name',
        ],
        'date_entered' => [
            'type' => 'datetime',
            'label' => 'LBL_DATE_ENTERED',
            'width' => '10%',
            'name' => 'date_entered',
        ],
    ],
    'listviewdefs' => [
        'NAME' => [
            'type' => 'name',
            'label' => 'LBL_NAME',
            'width' => '10%',
            'default' => true,
            'name' => 'name',
        ],
        'CITY' => [
            'type' => 'varchar',
            'label' => 'LBL_CITY',
            'width' => '10%',
            'default' => true,
            'name' => 'city',
        ],
        'STATE' => [
            'type' => 'varchar',
            'label' => 'LBL_STATE',
            'width' => '10%',
            'default' => true,
            'name' => 'state',
        ],
        'COUNTRY' => [
            'type' => 'varchar',
            'label' => 'LBL_COUNTRY',
            'width' => '10%',
            'default' => true,
            'name' => 'country',
        ],
        'MARKER_IMAGE' => [
            'type' => 'enum',
            'default' => true,
            'studio' => 'visible',
            'label' => 'LBL_MARKER_IMAGE',
            'sortable' => false,
            'width' => '10%',
        ],
        'ASSIGNED_USER_NAME' => [
            'link' => 'assigned_user_link',
            'type' => 'relate',
            'label' => 'LBL_ASSIGNED_TO_NAME',
            'width' => '10%',
            'default' => true,
            'name' => 'assigned_user_name',
        ],
    ],
];
