<?php

$dictionary['jjwg_Markers'] = array(
	'table'=>'jjwg_markers',
	'audited'=>true,
	'fields'=>array (
  'city' => 
  array (
    'required' => false,
    'name' => 'city',
    'vname' => 'LBL_CITY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'City',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'state' => 
  array (
    'required' => false,
    'name' => 'state',
    'vname' => 'LBL_STATE',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'State',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'country' => 
  array (
    'required' => false,
    'name' => 'country',
    'vname' => 'LBL_COUNTRY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => 'Country',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '255',
    'size' => '20',
  ),
  'jjwg_maps_lat' => 
  array (
    'required' => false,
    'name' => 'jjwg_maps_lat',
    'vname' => 'LBL_JJWG_MAPS_LAT',
    'type' => 'float',
    'massupdate' => 0,
    'default' => '0.00000000',
    'comments' => '',
    'help' => 'Latitude',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '26',
    'size' => '20',
    'precision' => '8',
  ),
  'jjwg_maps_lng' => 
  array (
    'required' => false,
    'name' => 'jjwg_maps_lng',
    'vname' => 'LBL_JJWG_MAPS_LNG',
    'type' => 'float',
    'massupdate' => 0,
    'default' => '0.00000000',
    'comments' => '',
    'help' => 'Longitude',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => '26',
    'size' => '20',
    'precision' => '8',
  ),
  'marker_image' => 
  array (
    'required' => false,
    'name' => 'marker_image',
    'vname' => 'LBL_MARKER_IMAGE',
    'type' => 'enum',
    'massupdate' => '1',
    'default' => 'company',
    'comments' => '',
    'help' => 'Marker Image Type',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'len' => 100,
    'size' => '20',
    'options' => 'marker_image_list',
    'studio' => 'visible',
    'dependency' => false,
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('jjwg_Markers','jjwg_Markers', array('basic','assignable'));
