<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Group_Opportunities'] = array(
    'table' => 'stic_group_opportunities',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_group_opportunities_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'document_status' => array(
            'required' => false,
            'name' => 'document_status',
            'vname' => 'LBL_DOCUMENT_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_group_opportunities_doc_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'amount_requested' => array(
            'required' => false,
            'name' => 'amount_requested',
            'vname' => 'LBL_AMOUNT_REQUESTED',
            'type' => 'decimal',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 26,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
        ),
        'amount_awarded' => array(
            'required' => false,
            'name' => 'amount_awarded',
            'vname' => 'LBL_AMOUNT_AWARDED',
            'type' => 'decimal',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 26,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
        ),
        'amount_received' => array(
            'required' => false,
            'name' => 'amount_received',
            'vname' => 'LBL_AMOUNT_RECEIVED',
            'type' => 'decimal',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 26,
            'size' => '20',
            'enable_range_search' => false,
            'precision' => 2,
        ),
        'start_date' => array(
            'required' => false,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'validation_date' => array(
            'required' => false,
            'name' => 'validation_date',
            'vname' => 'LBL_VALIDATION_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'presentation_date' => array(
            'required' => false,
            'name' => 'presentation_date',
            'vname' => 'LBL_PRESENTATION_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'resolution_date' => array(
            'required' => false,
            'name' => 'resolution_date',
            'vname' => 'LBL_RESOLUTION_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'popupHelp' => 'LBL_RESOLUTION_DATE_DESC',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'advance_date' => array(
            'required' => false,
            'name' => 'advance_date',
            'vname' => 'LBL_ADVANCE_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'justification_date' => array(
            'required' => false,
            'name' => 'justification_date',
            'vname' => 'LBL_JUSTIFICATION_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'payment_date' => array(
            'required' => false,
            'name' => 'payment_date',
            'vname' => 'LBL_PAYMENT_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'enable_range_search' => false,
        ),
        'folder' => array(
            'required' => false,
            'name' => 'folder',
            'vname' => 'LBL_FOLDER',
            'type' => 'url',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'dbType' => 'varchar',
            'gen' => '',
            'link_target' => '_blank',
        ),
        'contact_id' => array(
            'required' => false,
            'name' => 'contact_id',
            'vname' => 'LBL_CONTACT_CONTACT_ID',
            'type' => 'id',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'inline_edit' => true,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 36,
            'size' => '20',
        ),
        'contact' => array(
            'required' => false,
            'source' => 'non-db',
            'name' => 'contact',
            'vname' => 'LBL_CONTACT',
            'type' => 'relate',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
            'id_name' => 'contact_id',
            'ext2' => 'Contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);

$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_accounts"] = array(
    'name' => 'stic_group_opportunities_accounts',
    'type' => 'link',
    'relationship' => 'stic_group_opportunities_accounts',
    'source' => 'non-db',
    'module' => 'Accounts',
    'bean_name' => 'Account',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_ACCOUNTS_NAME',
    'id_name' => 'stic_group_opportunities_accountsaccounts_ida',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_accounts_name"] = array(
    'name' => 'stic_group_opportunities_accounts_name',
    'required' => true,
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_ACCOUNTS_NAME',
    'save' => true,
    'id_name' => 'stic_group_opportunities_accountsaccounts_ida',
    'link' => 'stic_group_opportunities_accounts',
    'table' => 'accounts',
    'module' => 'Accounts',
    'rname' => 'name',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_accountsaccounts_ida"] = array(
    'name' => 'stic_group_opportunities_accountsaccounts_ida',
    'type' => 'link',
    'relationship' => 'stic_group_opportunities_accounts',
    'source' => 'non-db',
    'reportable' => false,
    'side' => 'right',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_ACCOUNTS_FROM_STIC_GROUP_OPPORTUNITIES_TITLE',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_opportunities"] = array(
    'name' => 'stic_group_opportunities_opportunities',
    'type' => 'link',
    'relationship' => 'stic_group_opportunities_opportunities',
    'source' => 'non-db',
    'module' => 'Opportunities',
    'bean_name' => 'Opportunity',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_OPPORTUNITIES_NAME',
    'id_name' => 'stic_group_opportunities_opportunitiesopportunities_ida',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_opportunities_name"] = array(
    'name' => 'stic_group_opportunities_opportunities_name',
    'required' => true,
    'type' => 'relate',
    'source' => 'non-db',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_OPPORTUNITIES_NAME',
    'save' => true,
    'id_name' => 'stic_group_opportunities_opportunitiesopportunities_ida',
    'link' => 'stic_group_opportunities_opportunities',
    'table' => 'opportunities',
    'module' => 'Opportunities',
    'rname' => 'name',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_opportunitiesopportunities_ida"] = array(
    'name' => 'stic_group_opportunities_opportunitiesopportunities_ida',
    'type' => 'link',
    'relationship' => 'stic_group_opportunities_opportunities',
    'source' => 'non-db',
    'reportable' => false,
    'side' => 'right',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_OPPORTUNITIES_FROM_STIC_GROUP_OPPORTUNITIES_TITLE',
);
$dictionary["stic_Group_Opportunities"]["fields"]["stic_group_opportunities_documents_1"] = array(
    'name' => 'stic_group_opportunities_documents_1',
    'type' => 'link',
    'relationship' => 'stic_group_opportunities_documents_1',
    'source' => 'non-db',
    'module' => 'Documents',
    'bean_name' => 'Document',
    'vname' => 'LBL_STIC_GROUP_OPPORTUNITIES_DOCUMENTS_1_FROM_DOCUMENTS_TITLE',
);

if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}

VardefManager::createVardef('stic_Group_Opportunities', 'stic_Group_Opportunities', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Group_Opportunities']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_Group_Opportunities']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_Group_Opportunities']['fields']['name']['inline_edit'] = false; // Name is not inline editable
$dictionary['stic_Group_Opportunities']['fields']['assigned_user_name']['required'] = true; // Assigned user is required in this module
$dictionary['stic_Group_Opportunities']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
