<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
/*********************************************************************************
* SugarCRM Community Edition is a customer relationship management program developed by
* SugarCRM, Inc. Copyright (C) 2004-2012 SugarCRM Inc.
*
* This program is free software; you can redistribute it and/or modify it under
* the terms of the GNU Affero General Public License version 3 as published by the
* Free Software Foundation with the addition of the following permission added
* to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
* IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
* OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
* details.
*
* You should have received a copy of the GNU Affero General Public License along with
* this program; if not, see http://www.gnu.org/licenses or write to the Free
* Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
* 02110-1301 USA.
*
* You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
* SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
*
* The interactive user interfaces in modified source and object code versions
* of this program must display Appropriate Legal Notices, as required under
* Section 5 of the GNU Affero General Public License version 3.
*
* In accordance with Section 7(b) of the GNU Affero General Public License version 3,
* these Appropriate Legal Notices must retain the display of the "Powered by
* SugarCRM" logo. If the display of the logo is not reasonably feasible for
* technical reasons, the Appropriate Legal Notices must display the words
* "Powered by SugarCRM".
     // Replaced by RAPIRA -->
 ********************************************************************************/
  /*********************************************************************************
  *
  * This file was generated by the RAPIRA Translation Suite ----------
  *
  ***********************************************************************likhobory*/

  /*********************************************************************************
  * Description : Defines the Russian language pack for the base application.
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Contributor(s):
  *********************************************************************************/
 // Replaced by RAPIRA <--
$mod_strings = array (
'LBL_EDIT_LAYOUT'=> 'Правка расположения' ,
'LBL_EDIT_ROWS'=> 'Правка строк' ,
'LBL_EDIT_COLUMNS'=> 'Правка столбцов' ,
'LBL_EDIT_LABELS'=> 'Правка меток' ,
'LBL_EDIT_FIELDS'=> 'Правка пользовательских полей' ,
'LBL_ADD_FIELDS'=> 'Добавить пользовательское полей' ,
'LBL_DISPLAY_HTML'=> 'Показ HTML-кода' ,
'LBL_SELECT_FILE'=> 'Выбор файла' ,
'LBL_SAVE_LAYOUT'=> 'Сохранить макет' ,
'LBL_SELECT_A_SUBPANEL' => 'Выбор субпанели' ,
'LBL_SELECT_SUBPANEL' => 'Выбор субпанели' ,
'LBL_MODULE_TITLE' => 'Студия',
'LBL_TOOLBOX' => 'Инструментарий' ,
'LBL_STAGING_AREA' => 'Стартовая область (переместите элементы сюда)' ,
'LBL_SUGAR_FIELDS_STAGE' => 'Элементы <br> (выберите категорию из списка для отображения соответствующих элементов)' ,
'LBL_SUGAR_BIN_STAGE' => 'Бинарные файлы <br> (выберите категорию из списка для отображения соответствующих элементов)' ,
'LBL_VIEW_SUGAR_FIELDS' => 'Просмотр элементов',
'LBL_VIEW_SUGAR_BIN' => 'Просмотр бинарных файлов',
'LBL_FAILED_TO_SAVE' => 'Сохранение невозможно',
'LBL_CONFIRM_UNSAVE' => 'Изменения не будут сохранены. Вы действительно хотите продолжить?',
'LBL_PUBLISHING' => 'Публикация...',
'LBL_PUBLISHED' => 'Опубликовано',
'LBL_FAILED_PUBLISHED' => 'Публикация невозможна',
'LBL_DROP_HERE' => '[Переместить сюда]',

//CUSTOM FIELDS
'LBL_NAME'=> 'Название',
'LBL_LABEL'=> 'Надпись',
'LBL_MASS_UPDATE'=> 'Массовое обновление',
'LBL_AUDITED'=> 'Аудит',
'LBL_CUSTOM_MODULE'=> 'Модуль',
'LBL_DEFAULT_VALUE'=> 'Значение по умолчанию',
'LBL_REQUIRED'=> 'Необходимо',
'LBL_DATA_TYPE'=> 'Тип',


'LBL_HISTORY'=> 'История',

//WIZARDS
//STUDIO WIZARD
'LBL_SW_WELCOME'=> '<h2>Добро пожаловать в студию!</h2><br> Что бы вы хотели сделать?<br><b> Пожалуйста, выберите необходимую опцию.</b>',
'LBL_SW_EDIT_MODULE'=> 'Редактирование модуля',
'LBL_SW_EDIT_DROPDOWNS'=> 'Редактирование комбобоксов',
'LBL_SW_EDIT_TABS'=> 'Настройка закладок модулей',
'LBL_SW_RENAME_TABS'=> 'Переименование закладок',
'LBL_SW_EDIT_GROUPTABS'=> 'Настройка сгруппированных модулей',
'LBL_SW_EDIT_PORTAL'=> 'Редактирование портала',
'LBL_SW_EDIT_WORKFLOW'=> 'Edit Workflow',
'LBL_SW_REPAIR_CUSTOMFIELDS'=> 'Восстановление пользовательских полей',
'LBL_SW_MIGRATE_CUSTOMFIELDS'=> 'Перемещение пользовательских полей',


//SELECT MODULE WIZARD
'LBL_SMW_WELCOME'=> '<h2> Добро пожаловать в студию!</h2><br><b>Пожалуйста, выберите модуль.',

//SELECT MODULE ACTION
'LBL_SMA_WELCOME'=> '<h2>Редактирование модуля</h2>Что именно вы хотите сделать с модулем?<br><b>Пожалуйста, выберите необходимое действие.',
'LBL_SMA_EDIT_CUSTOMFIELDS'=> 'Создание / Редактирование пользовательских полей',
'LBL_SMA_EDIT_LAYOUT'=> 'Редактирование макета',
'LBL_SMA_EDIT_LABELS' => 'Редактирование меток',

//Manager Backups History
'LBL_MB_PREVIEW'=> 'Предварительный обзор',
'LBL_MB_RESTORE'=> 'Восстановить',
'LBL_MB_DELETE'=> 'Удалить',
'LBL_MB_COMPARE'=> 'Сравнить',
'LBL_MB_WELCOME'=> '<h2>История</h2><br> История позволяет вам просмотреть предыдущие сохранённые версии редактируемого в данный момент файла. Вы можете сравнить текущую версию с предыдущей, а так же восстановить предыдущую версию. Восстановленный файл станет вашим рабочим файлом. Вы должны опубликовать его для того, чтобы он стал доступен всем пользователям.<br> Что бы вы хотели сделать?<br><b> Пожалуйста, выберите необходимую опцию.</b>',

//EDIT DROP DOWNS
'LBL_ED_CREATE_DROPDOWN'=> 'Создать комбобокс',
'LBL_ED_WELCOME'=> '<h2>Редактор комбобоксов</h2><br><b>Вы можете отредактировать существующий комбобокс или создать новый.',
'LBL_DROPDOWN_NAME' => 'Название комбобокса:',
'LBL_DROPDOWN_LANGUAGE' => 'Язык содержимого комбобокса:',
'LBL_TABGROUP_LANGUAGE' => 'Выберите язык:',

//EDIT CUSTOM FIELDS
'LBL_EC_WELCOME'=> '<h2>Редактор пользовательских полей</h2><br><b>Вы можете просмотреть или отредактировать существующее пользовательское поле, создать новое пользовательское поле или очистить кэш пользовательского поля.',
'LBL_EC_VIEW_CUSTOMFIELDS'=> 'Обзор пользовательских полей',
'LBL_EC_CREATE_CUSTOMFIELD'=> 'Создать пользовательское поле',
'LBL_EC_CLEAR_CACHE'=> 'Очистить кэш',

//SELECT MODULE
'LBL_SM_WELCOME'=> '<h2>История</h2><br><b>Пожалуйста, выберите файл, который вы хотите просмотреть.</b>',
//END WIZARDS

//DROP DOWN EDITOR
'LBL_DD_DISPALYVALUE'=> 'Отображаемое значение',
'LBL_DD_DATABASEVALUE'=> 'Значение в базе',
'LBL_DD_ALL'=> 'Все',

//BUTTONS
'LBL_BTN_SAVE'=> 'Сохранить',
'LBL_BTN_CANCEL'=> 'Отказаться',
'LBL_BTN_SAVEPUBLISH'=> 'Сохранить и установить',
'LBL_BTN_HISTORY'=> 'История',
'LBL_BTN_NEXT'=> 'Вперёд',
'LBL_BTN_BACK'=> 'Назад',
'LBL_BTN_ADDCOLS'=> 'Добавить колонку',
'LBL_BTN_ADDROWS'=> 'Добавить строку',
'LBL_BTN_UNDO'=> 'Отменить',
'LBL_BTN_REDO'=> 'Вернуть',
'LBL_BTN_ADDCUSTOMFIELD'=> 'Добавить пользовательское поле',
'LBL_BTN_TABINDEX'=> 'Редактировать порядок перемещения по элементам макета',

//TABS
'LBL_TAB_SUBTABS'=> 'Подчинённые закладки',
'LBL_MODULES'=> 'Модули',
//nsingh: begin bug#15095 fix
'LBL_MODULE_NAME' => 'Администрирование',
'LBL_CONFIGURE_GROUP_TABS' => 'Настройка сгруппированных модулей',
//end bug #15095 fix
'LBL_GROUP_TAB_WELCOME'=> 'Сгруппированные модули будут использоваться всякий раз, как только пользователь выберет на странице настроек параметров пользователя в качестве принципа навигации сгруппированные модули вместо обычных модулей. Вы можете перемещать закладки модулей между группами для настройки их расположения. Пустые группы не будут отображаться в панели закладок.',
'LBL_RENAME_TAB_WELCOME'=> ' Нажмите на необходимом названии закладки для её переименования.',
'LBL_DELETE_MODULE'=> 'Удалить&nbsp;модуль<br />из&nbsp;группы',
'LBL_DISPLAY_OTHER_TAB_HELP' => 'Установите эту опцию для отображения закладки "Разное" в панели закладок. По умолчанию данная закладка содержит все модули, не вошедшие в другие группы.',
'LBL_TAB_GROUP_LANGUAGE_HELP' => 'Выберите необходимый язык, отредактируйте закладки сгруппированных модулей и нажмите на кнопку <b>Сохранить и установить</b>.',
'LBL_ADD_GROUP'=> 'Добавить группу',
'LBL_NEW_GROUP'=> 'Новая группа',
'LBL_RENAME_TABS'=> 'Переименование закладок модулей',
'LBL_DISPLAY_OTHER_TAB' => 'Отображать закладку "Разное"',

//LIST VIEW EDITOR
'LBL_DEFAULT'=> 'По умолчанию',
'LBL_ADDITIONAL'=> 'Дополнительно',
'LBL_AVAILABLE'=> 'Доступно',
'LBL_LISTVIEW_DESCRIPTION'=> 'Перед вами три колонки. Первая колонка содержит отображаемые поля, вторая колонка содержит дополнительные поля, которые пользователь может выбрать для создания собственного макета формы при настройке Расширенного поиска, третья колонка содержит поля, доступные только администратору, их он может добавлять в первую и вторую колонки по своему усмотрению.',
'LBL_LISTVIEW_EDIT'=> 'Редактор Формы списка',

//ERRORS
'ERROR_ALREADY_EXISTS'=> 'Ошибка: Поле уже существует',
'ERROR_INVALID_KEY_VALUE'=> "Ошибка: Неверное значение ключа: [']",

//SUGAR PORTAL
'LBL_SW_SUGARPORTAL'=> 'Портал SuiteCRM',
'LBL_SMP_WELCOME'=> 'Пожалуйста, выберите из списка модуль, который вы желаете отредактировать',
'LBL_SP_WELCOME'=> 'Добро пожаловать в студию портала SuiteCRM. Здесь вы можете как отредактировать модули , так и синхронизировать соответствующий портал.<br> Выберите необходимый пункт из списка.',
'LBL_SP_SYNC'=> 'Синхронизация портала',
'LBL_SYNCP_WELCOME'=> 'Пожалуйста, укажите адрес портала, который вы хотите обновить и нажмите кнопку "Далее".<br> Вам будет предложено ввести имя пользователя и пароль. <br> Пожалуйста, введите необходимые данные и нажмите соответствующую кнопку для начала процесса синхронизации.',
'LBL_LISTVIEWP_DESCRIPTION'=> 'Перед вами две колонки: в первой расположены отображаемые поля, во второй - поля, доступные для отображения. Вы можете перемещать поля между колонками. Вы так же можете изменять порядок расположения полей внутри каждой колонки путём их перемещения.',
'LBL_SP_STYLESHEET'=> 'Загрузить таблицу стилей',
'LBL_SP_UPLOADSTYLE'=> 'Нажмите на кнопку \"Обзор\" и выберите необходимый файл таблицы стилей для загрузки.<br> Следующий раз при синхронизации портала будет использована указанная таблица стилей.',
'LBL_SP_UPLOADED'=> 'Загружена',
'ERROR_SP_UPLOADED'=> 'Пожалуйста, убедитесь, что вы загружаете css-файл.',
'LBL_SP_PREVIEW'=> 'Предварительный просмотр результата  форматирования с применением указанной таблицы стилей.',

'LBL_SAVE' => 'Сохранить' /*for 508 compliance fix*/,
'LBL_UNDO' => 'Отменить' /*for 508 compliance fix*/,
'LBL_REDO' => 'Повторить' /*for 508 compliance fix*/,
'LBL_INLINE' => 'Inline'  /*for 508 compliance fix*/,
'LBL_DELETE' => 'Удалить' /*for 508 compliance fix*/,
'LBL_ADD_FIELD' => 'Добавить поле' /*for 508 compliance fix*/,
'LBL_MAXIMIZE' => 'Развернуть' /*for 508 compliance fix*/,
'LBL_MINIMIZE' => 'Свернуть' /*for 508 compliance fix*/,
'LBL_PUBLISH' => 'Опубликовать' /*for 508 compliance fix*/,
'LBL_ADDROWS' => 'Добавить строки' /*for 508 compliance fix*/,
'LBL_ADDFIELD' => 'Добавить поле' /*for 508 compliance fix*/,
'LBL_EDIT' => 'Править' /*for 508 compliance fix*/,

'LBL_LANGUAGE_TOOLTIP' => 'Выберите язык для редактирования.',
'LBL_SINGULAR' => 'Singular Label', ///
'LBL_PLURAL' => 'Plural Label', ///
'LBL_RENAME_MOD_SAVE_HELP' => 'Нажмите на кнопку <b>Сохранить</b> для применения внесённых изменений.'
);
?>
