<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Payments'] = array(
    'table' => 'stic_payments',
    'audited' => 1,
    'inline_edit' => 1,
    'duplicate_merge' => 1,
    'fields' => array(
        'payment_type' => array(
            'required' => 1,
            'name' => 'payment_type',
            'vname' => 'LBL_PAYMENT_TYPE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_types_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
        ),
        'bank_account' => array(
            'required' => 0,
            'name' => 'bank_account',
            'vname' => 'LBL_BANK_ACCOUNT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
            'inline-edit' => 1,
            'validationType' => true,            
        ),
        'amount' => array(
            'required' => 1,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'decimal',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 26,
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => 1,
            'precision' => 2,
            'inline-edit' => 1,
        ),
        'payment_method' => array(
            'required' => 1,
            'name' => 'payment_method',
            'vname' => 'LBL_PAYMENT_METHOD',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_methods_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
        ),
        'transaction_type' => array(
            'required' => 0,
            'name' => 'transaction_type',
            'vname' => 'LBL_TRANSACTION_TYPE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_transaction_types_list',
            'studio' => 'visible',
            'dependency' => 0,
            'inline_edit' => 1,
        ),
        'mandate' => array(
            'required' => 0,
            'name' => 'mandate',
            'vname' => 'LBL_MANDATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 1,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
        ),
        'segmentation' => array(
            'required' => 0,
            'name' => 'segmentation',
            'vname' => 'LBL_SEGMENTATION',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_custom_sorting_list',
            'studio' => 'visible',
            'dependency' => 0,
        ),
        'in_kind_description' => array(
            'required' => 0,
            'name' => 'in_kind_description',
            'vname' => 'LBL_IN_KIND_DESCRIPTION',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
        ),
        'banking_concept' => array(
            'required' => 0,
            'name' => 'banking_concept',
            'vname' => 'LBL_BANKING_CONCEPT',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => '255',
            'size' => '20',
        ),
        'status' => array(
            'required' => 1,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 1,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_status_list',
            'studio' => 'visible',
            'dependency' => 0,
        ),
        'm182_excluded' => array(
            'name' => 'm182_excluded',
            'vname' => 'LBL_M182_EXCLUDED',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'bool',
            'required' => 0,
            'reportable' => 1,
            'audited' => 0,
            'importable' => 1,
            'massupdate' => 1,
        ),

        'sepa_rejected_reason' => array(
            'required' => 0,
            'name' => 'sepa_rejected_reason',
            'vname' => 'LBL_SEPA_REJECTED_REASON',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_sepa_return_reasons_list',
            'studio' => 'visible',
            'dependency' => 0,
        ),
        'rejection_date' => array(
            'required' => 0,
            'name' => 'rejection_date',
            'vname' => 'LBL_REJECTION_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => 1,
        ),
        'c19_rejected_reason' => array(
            'required' => 0,
            'name' => 'c19_rejected_reason',
            'vname' => 'LBL_C19_REJECTED_REASON',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 100,
            'size' => '20',
            'options' => 'stic_payments_c19_return_reasons_list',
            'studio' => 'visible',
            'dependency' => 0,
            'default' => '',
        ),
        'payment_date' => array(
            'required' => 1,
            'name' => 'payment_date',
            'vname' => 'LBL_PAYMENT_DATE',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'date',
            'massupdate' => 1,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'audited' => 1,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => 1,
        ),
        'transaction_code' => array(
            'name' => 'transaction_code',
            'vname' => 'LBL_TRANSACTION_CODE',
            'type' => 'int',
            'readonly' => 1,
            'len' => 11,
            'required' => 1,
            'auto_increment' => 1,
            'comment' => 'Visual unique identifier',
            'duplicate_merge' => 'disabled',
            'disable_num_format' => 1,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
        ),
        'gateway_rejection_reason' => array(
            'required' => 0,
            'name' => 'gateway_rejection_reason',
            'vname' => 'LBL_GATEWAY_REJECTION_REASON',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 1,
            'audited' => 0,
            'inline_edit' => 1,
            'reportable' => 1,
            'unified_search' => 0,
            'len' => 255,
            'size' => '20',
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'dependency' => 0,
        ),
        'aggregated_services_complete' => array(
            'required' => false,
            'name' => 'aggregated_services_complete',
            'vname' => 'LBL_AGGREGATED_SERVICES_COMPLETE',
            'type' => 'bool',
            'no_default' => false,
            'massupdate' => 0,
            'inline_edit' => 0,
            'comments' => '',
            'help' => '',
            'importable' => '1',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'duplicate_merge_dom_value' => '2',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
        ),
        'gateway_log' => array(
            'required' => 0,
            'name' => 'gateway_log',
            'vname' => 'LBL_GATEWAY_LOG',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'enabled',
            'type' => 'text',
            'massupdate' => 0,
            'no_default' => 0,
            'comment' => '',
            'help' => '',
            'importable' => 0,
            'audited' => 0,
            'inline_edit' => 0,
            'rows' => '2',
            'cols' => 80,
            'unified_search' => 0,
            'studio' => array(
                'quickcreate' => false,
                'editview' => false,
            ),
            'popupHelp' => 'LBL_GATEWAY_LOG_INFO',
        ),
        'stic_payments_contacts' => array(
            'name' => 'stic_payments_contacts',
            'type' => 'link',
            'relationship' => 'stic_payments_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_PAYMENTS_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_payments_contactscontacts_ida',
        ),
        'stic_payments_contacts_name' => array(
            'name' => 'stic_payments_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => true,
            'inline_edit' => 0,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'id_name' => 'stic_payments_contactscontacts_ida',
            'link' => 'stic_payments_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
            'massupdate' => 0,
        ),
        'stic_payments_contactscontacts_ida' => array(
            'name' => 'stic_payments_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_payments_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_CONTACTS_FROM_STIC_PAYMENTS_TITLE',
        ),
        'stic_payments_accounts' => array(
            'name' => 'stic_payments_accounts',
            'type' => 'link',
            'relationship' => 'stic_payments_accounts',
            'source' => 'non-db',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'vname' => 'LBL_STIC_PAYMENTS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'id_name' => 'stic_payments_accountsaccounts_ida',
        ),
        'stic_payments_accounts_name' => array(
            'name' => 'stic_payments_accounts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'save' => true,
            'studio' => array(
                'editview' => false,
                'quickcreate' => false,
            ),
            'inline_edit' => 0,
            'id_name' => 'stic_payments_accountsaccounts_ida',
            'link' => 'stic_payments_accounts',
            'table' => 'accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'massupdate' => 0,
        ),
        'stic_payments_accountsaccounts_ida' => array(
            'name' => 'stic_payments_accountsaccounts_ida',
            'type' => 'link',
            'relationship' => 'stic_payments_accounts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_ACCOUNTS_FROM_STIC_PAYMENTS_TITLE',
        ),

        'stic_payments_stic_payment_commitments' => array(
            'name' => 'stic_payments_stic_payment_commitments',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_payment_commitments',
            'source' => 'non-db',
            'module' => 'stic_Payment_Commitments',
            'bean_name' => 'stic_Payment_Commitments',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_PAYMENT_COMMITMENTS_FROM_STIC_PAYMENT_COMMITMENTS_TITLE',
            'id_name' => 'stic_paymebfe2itments_ida',
        ),
        'stic_payments_stic_payment_commitments_name' => array(
            'name' => 'stic_payments_stic_payment_commitments_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_PAYMENT_COMMITMENTS_FROM_STIC_PAYMENT_COMMITMENTS_TITLE',
            'save' => true,
            'required' => true,
            'importable' => 'required',
            'id_name' => 'stic_paymebfe2itments_ida',
            'link' => 'stic_payments_stic_payment_commitments',
            'table' => 'stic_payment_commitments',
            'module' => 'stic_Payment_Commitments',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'stic_paymebfe2itments_ida' => array(
            'name' => 'stic_paymebfe2itments_ida',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_payment_commitments',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_PAYMENT_COMMITMENTS_FROM_STIC_PAYMENTS_TITLE',
        ),
        'stic_payments_stic_registrations' => array(
            'name' => 'stic_payments_stic_registrations',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_registrations',
            'source' => 'non-db',
            'module' => 'stic_Registrations',
            'bean_name' => 'stic_Registrations',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'id_name' => 'stic_payments_stic_registrationsstic_registrations_idb',
        ),
        'stic_payments_stic_registrations_name' => array(
            'name' => 'stic_payments_stic_registrations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'save' => true,
            'id_name' => 'stic_payments_stic_registrationsstic_registrations_idb',
            'link' => 'stic_payments_stic_registrations',
            'table' => 'stic_registrations',
            'module' => 'stic_Registrations',
            'rname' => 'name',
            'inline_edit' => 1,
            'massupdate' => 0,
        ),
        'stic_payments_stic_registrationsstic_registrations_idb' => array(
            'name' => 'stic_payments_stic_registrationsstic_registrations_idb',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_registrations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'left',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
        ),

        'stic_payments_stic_remittances' => array(
            'name' => 'stic_payments_stic_remittances',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_remittances',
            'source' => 'non-db',
            'module' => 'stic_Remittances',
            'bean_name' => 'stic_Remittances',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REMITTANCES_FROM_STIC_REMITTANCES_TITLE',
            'id_name' => 'stic_payments_stic_remittancesstic_remittances_ida',
        ),
        'stic_payments_stic_remittances_name' => array(
            'name' => 'stic_payments_stic_remittances_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REMITTANCES_FROM_STIC_REMITTANCES_TITLE',
            'save' => true,
            'id_name' => 'stic_payments_stic_remittancesstic_remittances_ida',
            'link' => 'stic_payments_stic_remittances',
            'table' => 'stic_remittances',
            'module' => 'stic_Remittances',
            'rname' => 'name',
            'massupdate' => 1,
            'inline_edit' => 1,
        ),
        'stic_payments_stic_remittancesstic_remittances_ida' => array(
            'name' => 'stic_payments_stic_remittancesstic_remittances_ida',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_remittances',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_REMITTANCES_FROM_STIC_PAYMENTS_TITLE',
        ),
        'stic_payments_activities_calls' => array(
            'name' => 'stic_payments_activities_calls',
            'type' => 'link',
            'relationship' => 'stic_payments_activities_calls',
            'source' => 'non-db',
            'module' => 'Calls',
            'bean_name' => 'Call',
            'vname' => 'LBL_STIC_PAYMENTS_ACTIVITIES_CALLS_FROM_CALLS_TITLE',
        ),
        'stic_payments_activities_emails' => array(
            'name' => 'stic_payments_activities_emails',
            'type' => 'link',
            'relationship' => 'stic_payments_activities_emails',
            'source' => 'non-db',
            'module' => 'Emails',
            'bean_name' => 'Email',
            'vname' => 'LBL_STIC_PAYMENTS_ACTIVITIES_EMAILS_FROM_EMAILS_TITLE',
        ),
        'stic_payments_activities_meetings' => array(
            'name' => 'stic_payments_activities_meetings',
            'type' => 'link',
            'relationship' => 'stic_payments_activities_meetings',
            'source' => 'non-db',
            'module' => 'Meetings',
            'bean_name' => 'Meeting',
            'vname' => 'LBL_STIC_PAYMENTS_ACTIVITIES_MEETINGS_FROM_MEETINGS_TITLE',
        ),
        'stic_payments_activities_notes' => array(
            'name' => 'stic_payments_activities_notes',
            'type' => 'link',
            'relationship' => 'stic_payments_activities_notes',
            'source' => 'non-db',
            'module' => 'Notes',
            'bean_name' => 'Note',
            'vname' => 'LBL_STIC_PAYMENTS_ACTIVITIES_NOTES_FROM_NOTES_TITLE',
        ),
        'stic_payments_activities_tasks' => array(
            'name' => 'stic_payments_activities_tasks',
            'type' => 'link',
            'relationship' => 'stic_payments_activities_tasks',
            'source' => 'non-db',
            'module' => 'Tasks',
            'bean_name' => 'Task',
            'vname' => 'LBL_STIC_PAYMENTS_ACTIVITIES_TASKS_FROM_TASKS_TITLE',
        ),
        'stic_payments_stic_attendances' => array(
            'name' => 'stic_payments_stic_attendances',
            'type' => 'link',
            'relationship' => 'stic_payments_stic_attendances',
            'source' => 'non-db',
            'module' => 'stic_Attendances',
            'bean_name' => 'stic_Attendances',
            'side' => 'right',
            'vname' => 'LBL_STIC_PAYMENTS_STIC_ATTENDANCES_FROM_STIC_ATTENDANCES_TITLE',
        ),
    ),
    'indices' => array(
        'transaction_code_autoincrement' => array(
            'name' => 'transaction_code_autoincrement',
            'type' => 'unique',
            'fields' => array(
                'transaction_code',
            ),
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => 1,
    'unified_search' => true,
    'unified_search_default_enabled' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Payments', 'stic_Payments', array('basic', 'assignable', 'security_groups'));

// Set special values for SuiteCRM base fields
$dictionary['stic_Payments']['fields']['name']['required'] = '0'; // Name is not required in this module
$dictionary['stic_Payments']['fields']['name']['importable'] = true; // Name is importable but not required in this module
$dictionary['stic_Payments']['fields']['name']['audited'] = 1;
$dictionary['stic_Payments']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
