<?php
/**
 * This file is part of SinergiaCRM.
 * SinergiaCRM is a work developed by SinergiaTIC Association, based on SuiteCRM.
 * Copyright (C) 2013 - 2023 SinergiaTIC Association
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SinergiaTIC Association at email address info@sinergiacrm.org.
 */

$dictionary['stic_Training'] = array(
    'table' => 'stic_training',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array(
        'name' => array(
            'name' => 'name',
            'vname' => 'LBL_NAME',
            'type' => 'name',
            'link' => true,
            'dbType' => 'varchar',
            'len' => '255',
            'unified_search' => true,
            'full_text_search' => array(
                'boost' => 3,
            ),
            'required' => false,
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'merge_filter' => 'selected',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'duplicate_merge_dom_value' => '3',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'size' => '20',
        ),
        'level' => array(
            'required' => true,
            'name' => 'level',
            'vname' => 'LBL_LEVEL',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_levels_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'course_year' => array(
            'required' => false,
            'name' => 'course_year',
            'vname' => 'LBL_COURSE_YEAR',
            'type' => 'dynamicenum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_courses_list',
            'studio' => 'visible',
            'dbType' => 'enum',
            'parentenum' => 'level',
        ),
        'scope' => array(
            'required' => false,
            'name' => 'scope',
            'vname' => 'LBL_SCOPE',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_scopes_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'status' => array(
            'required' => true,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_status_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'qualification' => array(
            'required' => false,
            'name' => 'qualification',
            'vname' => 'LBL_QUALIFICATION',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'country' => array(
            'required' => true,
            'name' => 'country',
            'vname' => 'LBL_COUNTRY ',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'required',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_incorpora_country_list',
            'studio' => 'visible',
            'dependency' => false,
            'default' => '011',
        ),
        'previous' => array(
            'required' => false,
            'name' => 'previous',
            'vname' => 'LBL_PREVIOUS',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_previous_list',
            'studio' => 'visible',
            'dependency' => false,
            'popupHelp' => 'LBL_PREVIOUS_HELP',
        ),
        'accredited' => array(
            'required' => false,
            'name' => 'accredited',
            'vname' => 'LBL_ACCREDITED',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'formal' => array(
            'required' => false,
            'name' => 'formal',
            'vname' => 'LBL_FORMAL',
            'type' => 'enum',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_boolean_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'certification' => array(
            'required' => false,
            'name' => 'certification',
            'vname' => 'LBL_CERTIFICATION',
            'type' => 'varchar',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '255',
            'size' => '20',
        ),
        'grant_training' => array(
            'required' => false,
            'name' => 'grant_training',
            'vname' => 'LBL_GRANT_TRAINING',
            'type' => 'enum',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => 100,
            'size' => '20',
            'options' => 'stic_training_grant_origins_list',
            'studio' => 'visible',
            'dependency' => false,
        ),
        'grant_amount' => array(
            'required' => false,
            'name' => 'grant_amount',
            'vname' => 'LBL_GRANT_AMOUNT',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '18',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => true,
            'precision' => '2',
        ),
        'amount' => array(
            'required' => false,
            'name' => 'amount',
            'vname' => 'LBL_AMOUNT',
            'type' => 'decimal',
            'massupdate' => 0,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'len' => '18',
            'size' => '20',
            'options' => 'numeric_range_search_dom',
            'enable_range_search' => true,
            'precision' => '2',
        ),
        'start_date' => array(
            'required' => false,
            'name' => 'start_date',
            'vname' => 'LBL_START_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'end_date' => array(
            'required' => false,
            'name' => 'end_date',
            'vname' => 'LBL_END_DATE',
            'type' => 'date',
            'massupdate' => '1',
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => false,
            'inline_edit' => true,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'size' => '20',
            'options' => 'date_range_search_dom',
            'enable_range_search' => true,
            'dbType' => 'datetime',
        ),
        'stic_training_accounts' => array(
            'name' => 'stic_training_accounts',
            'type' => 'link',
            'relationship' => 'stic_training_accounts',
            'source' => 'non-db',
            'module' => 'Accounts',
            'bean_name' => 'Account',
            'vname' => 'LBL_STIC_TRAINING_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'id_name' => 'stic_training_accountsaccounts_ida',
        ),
        'stic_training_accounts_name' => array(
            'name' => 'stic_training_accounts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_TRAINING_ACCOUNTS_FROM_ACCOUNTS_TITLE',
            'save' => true,
            'id_name' => 'stic_training_accountsaccounts_ida',
            'link' => 'stic_training_accounts',
            'table' => 'accounts',
            'module' => 'Accounts',
            'rname' => 'name',
            'required' => false,
        ),
        'stic_training_accountsaccounts_ida' => array(
            'name' => 'stic_training_accountsaccounts_ida',
            'type' => 'link',
            'relationship' => 'stic_training_accounts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_TRAINING_ACCOUNTS_FROM_STIC_TRAINING_TITLE',
        ),
        'stic_training_contacts' => array(
            'name' => 'stic_training_contacts',
            'type' => 'link',
            'relationship' => 'stic_training_contacts',
            'source' => 'non-db',
            'module' => 'Contacts',
            'bean_name' => 'Contact',
            'vname' => 'LBL_STIC_TRAINING_CONTACTS_FROM_CONTACTS_TITLE',
            'id_name' => 'stic_training_contactscontacts_ida',
        ),
        'stic_training_contacts_name' => array(
            'name' => 'stic_training_contacts_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_TRAINING_CONTACTS_FROM_CONTACTS_TITLE',
            'save' => true,
            'id_name' => 'stic_training_contactscontacts_ida',
            'link' => 'stic_training_contacts',
            'table' => 'contacts',
            'module' => 'Contacts',
            'rname' => 'name',
            'required' => true,
            'db_concat_fields' => array(
                0 => 'first_name',
                1 => 'last_name',
            ),
        ),
        'stic_training_contactscontacts_ida' => array(
            'name' => 'stic_training_contactscontacts_ida',
            'type' => 'link',
            'relationship' => 'stic_training_contacts',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'right',
            'vname' => 'LBL_STIC_TRAINING_CONTACTS_FROM_STIC_TRAINING_TITLE',
        ),
        'stic_training_stic_registrations' => array(
            'name' => 'stic_training_stic_registrations',
            'type' => 'link',
            'relationship' => 'stic_training_stic_registrations',
            'source' => 'non-db',
            'module' => 'stic_Registrations',
            'bean_name' => 'stic_Registrations',
            'vname' => 'LBL_STIC_TRAINING_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'id_name' => 'stic_training_stic_registrationsstic_registrations_idb',
        ),
        'stic_training_stic_registrations_name' => array(
            'name' => 'stic_training_stic_registrations_name',
            'type' => 'relate',
            'source' => 'non-db',
            'vname' => 'LBL_STIC_TRAINING_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
            'save' => true,
            'id_name' => 'stic_training_stic_registrationsstic_registrations_idb',
            'link' => 'stic_training_stic_registrations',
            'table' => 'stic_registrations',
            'module' => 'stic_Registrations',
            'rname' => 'name',
        ),
        'stic_training_stic_registrationsstic_registrations_idb' => array(
            'name' => 'stic_training_stic_registrationsstic_registrations_idb',
            'type' => 'link',
            'relationship' => 'stic_training_stic_registrations',
            'source' => 'non-db',
            'reportable' => false,
            'side' => 'left',
            'vname' => 'LBL_STIC_TRAINING_STIC_REGISTRATIONS_FROM_STIC_REGISTRATIONS_TITLE',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
    require_once 'include/SugarObjects/VardefManager.php';
}
VardefManager::createVardef('stic_Training', 'stic_Training', array('basic', 'assignable', 'security_groups'));
// Set special values for SuiteCRM base fields
$dictionary['stic_Training']['fields']['description']['rows'] = '2'; // Make textarea fields shorter
